from loguru import logger

from ap.api.common.services.show_graph_database import (
    get_all_process_ids,
    get_config_process_and_card_order_per_process,
    get_traces_graph_config_data,
)
from ap.common.jobs.job_info_schema import (
    ComputeAllProcessIdsCacheJobInfo,
    ComputeAllTracesCacheJobInfo,
    ComputeProcessCacheJobInfo,
)
from ap.common.memoize import OptionalCacheConfig
from ap.common.scheduler import scheduler_app_context
from ap.setting_module.models import CfgProcess, JobManagement
from ap.setting_module.services.background_process import send_processing_info


class CacheFunctions:
    """Provides cache computation functions for processes and trace data.

    This class contains static methods for computing and updating various
    caches used throughout the application, including process configurations,
    card orders, and trace graph data.

    Methods:
        get_config_process_and_card_order_per_process_job: Compute cache for process configurations and card orders.
        get_all_process_ids_job: Compute cache for all process IDs.
        get_traces_graph_config_data_job: Compute cache for trace graph configuration data.

    Generated by Duo
    """

    @staticmethod
    @scheduler_app_context
    def get_config_process_and_card_order_per_process_job(
        job_management: JobManagement,
        process_ids: list[int] | None = None,
        optional_cache_config=OptionalCacheConfig(),
    ):
        if process_ids is None:
            # Truly get a list of process's id in Database (not in cache) to calculate cache for real processes
            process_ids = CfgProcess.get_all_ids(with_parent=True)

        def generator():
            cache_job_info = ComputeProcessCacheJobInfo()
            job_management.info = cache_job_info

            if not process_ids:
                yield 100
                return

            progress_percent = 0
            yield progress_percent

            increase_step = 100 / len(process_ids)
            for process_id in process_ids:
                logger.debug(f'[COMPUTE_CACHE] process_id: {process_id}')
                cfg_process, *_ = get_config_process_and_card_order_per_process(
                    process_id,
                    optional_cache_config=optional_cache_config,
                )
                cache_job_info.cached_processes.append(
                    ComputeProcessCacheJobInfo.CachedProcess(
                        id=cfg_process.id,
                        name=cfg_process.name,
                    )
                )
                progress_percent += increase_step
                yield progress_percent

        send_processing_info(generator(), job_management=job_management)

    @staticmethod
    @scheduler_app_context
    def get_all_process_ids_job(job_management: JobManagement, optional_cache_config=OptionalCacheConfig()):
        def generator():
            cache_job_info = ComputeAllProcessIdsCacheJobInfo()
            job_management.info = cache_job_info
            yield 0
            logger.debug('[COMPUTE_CACHE] get_all_process_ids')
            process_ids = get_all_process_ids(optional_cache_config=optional_cache_config)
            for process_id in process_ids:
                cache_job_info.cached_process_ids.append(
                    ComputeAllProcessIdsCacheJobInfo.CachedProcessId(
                        id=process_id,
                    )
                )

            yield 100

        send_processing_info(generator(), job_management=job_management)

    @staticmethod
    @scheduler_app_context
    def get_traces_graph_config_data_job(
        job_management: JobManagement,
        optional_cache_config=OptionalCacheConfig(),
    ):
        def generator():
            cache_job_info = ComputeAllTracesCacheJobInfo()
            job_management.info = cache_job_info
            yield 0
            logger.debug('[COMPUTE_CACHE] trace config')
            trace_graph = get_traces_graph_config_data(optional_cache_config=optional_cache_config)
            cache_job_info.leaf_start_nodes.extend(
                [ComputeAllTracesCacheJobInfo.TraceNode(id=x) for x in trace_graph.leaf_start_nodes]
            )
            cache_job_info.leaf_end_nodes.extend(
                [ComputeAllTracesCacheJobInfo.TraceNode(id=x) for x in trace_graph.leaf_end_nodes]
            )
            yield 100

        send_processing_info(generator(), job_management=job_management)
