import logging
import os
from typing import Any, ClassVar

from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from sqlalchemy import NullPool

from ap.common.common_utils import resource_path
from ap.common.jobs.executor import CustomizeProcessPoolExecutor, CustomizeThreadPoolExecutor

logger = logging.getLogger(__name__)

basedir = os.getcwd()


class Config(object):
    """Base configuration class with app settings.

    Provides base configuration settings for the application including
    paths, database settings, scheduler configuration, and various
    application parameters.

    Attributes:
        SECRET_KEY: Secret key for Flask application.
        POSTS_PER_PAGE: Number of posts per page.
        PORT: Application port number.
        R_PORTABLE: Path to R-Portable installation.
        ORACLE_PATH: Path to Oracle client installation.
        BABEL_DEFAULT_LOCALE: Default locale for Babel.
        DB_SECRET_KEY: Secret key for database encryption.
        CREATE_ENGINE_PARAMS: Parameters for SQLAlchemy engine creation.
        SQLALCHEMY_ENGINE_OPTIONS: SQLAlchemy engine options.
        SCHEDULER_EXECUTORS: APScheduler executor configuration.
        SCHEDULER_JOB_DEFAULTS: Default settings for scheduled jobs.
        VERSION_FILE_PATH: Path to version file.
        BASE_DIR: Base directory path.
        COMPRESS_MIMETYPES: MIME types for compression.
        COMPRESS_LEVEL: Compression level.
        COMPRESS_MIN_SIZE: Minimum size for compression.
        INIT_CONFIG_DIR: Initial configuration directory.
        INIT_LOG_DIR: Initial log directory.
        INIT_APP_DB_FILE: Initial app database file path.
        INIT_BASIC_CFG_FILE: Initial basic config file path.
        IS_SEND_GOOGLE_ANALYTICS: Flag for Google Analytics.

    Generated by Duo
    """

    SECRET_KEY = '736670cb10a600b695a55839ca3a5aa54a7d7356cdef815d2ad6e19a2031182b'
    POSTS_PER_PAGE = 10
    PORT = 80
    os.environ['FLASK_ENV'] = os.environ.get('FLASK_ENV', 'production')
    CICD_BASE_DIR = os.environ.get('CICD_BASE_DIR')
    parent_dir = CICD_BASE_DIR if CICD_BASE_DIR else os.path.dirname(basedir)

    R_PORTABLE = os.path.join(parent_dir, 'R-Portable', 'bin')
    os.environ['PATH'] = '{};{}'.format(R_PORTABLE, os.environ.get('PATH', ''))

    # R-PORTABLEを設定する。
    os.environ['R-PORTABLE'] = os.path.join(parent_dir, 'R-Portable')

    ORACLE_PATH = os.path.join(parent_dir, 'Oracle-Portable')
    os.environ['PATH'] = '{};{}'.format(ORACLE_PATH, os.environ.get('PATH', ''))

    ORACLE_PATH_WITH_VERSION = os.path.join(ORACLE_PATH, 'instantclient_21_3')
    os.environ['PATH'] = '{};{}'.format(ORACLE_PATH_WITH_VERSION, os.environ.get('PATH', ''))

    logger.info(os.environ['PATH'])
    logger.info(R_PORTABLE)

    BABEL_DEFAULT_LOCALE = 'en'

    # run `python ap/script/generate_db_secret_key.py` to generate DB_SECRET_KEY
    DB_SECRET_KEY = '4hlAxWLWt8Tyqi5i1zansLPEXvckXR2zrl_pDkxVa-A='

    CREATE_ENGINE_PARAMS: ClassVar[dict[str, Any]] = {'timeout': 60 * 5}
    # timeout
    SQLALCHEMY_ENGINE_OPTIONS: ClassVar[dict[str, Any]] = {'connect_args': CREATE_ENGINE_PARAMS}
    # SQLALCHEMY_POOL_SIZE = 20
    # SQLALCHEMY_MAX_OVERFLOW = 0

    # APScheduler
    SCHEDULER_EXECUTORS: ClassVar[dict[str, Any]] = {
        'default': CustomizeProcessPoolExecutor(5),
        'threadpool': CustomizeThreadPoolExecutor(100),
    }

    # misfire_grace_time set to None so that jobs will execute no matter how late they are
    # if set to any integer value x, jobs will be missed if they are late for x seconds
    # References: https://apscheduler.readthedocs.io/en/3.x/modules/job.html
    # https://apscheduler.readthedocs.io/en/3.x/userguide.html#missed-job-executions
    SCHEDULER_JOB_DEFAULTS: ClassVar[dict[str, Any]] = {
        'coalesce': True,
        'max_instances': 1,
        'misfire_grace_time': None,
    }
    VERSION_FILE_PATH = resource_path('VERSION')
    BASE_DIR = basedir

    COMPRESS_MIMETYPES: ClassVar[list[str]] = [
        'text/html',
        'text/css',
        'text/xml',
        'text/csv',
        'text/tsv',
        'application/json',
        'application/javascript',
    ]
    COMPRESS_LEVEL = 6
    COMPRESS_MIN_SIZE = 500

    INIT_CONFIG_DIR = os.path.join(basedir, 'init')
    INIT_LOG_DIR = os.path.join(basedir, 'log')
    INIT_APP_DB_FILE = os.path.join(INIT_CONFIG_DIR, 'app.sqlite3')
    INIT_BASIC_CFG_FILE = os.path.join(INIT_CONFIG_DIR, 'basic_config.yml')

    IS_SEND_GOOGLE_ANALYTICS = True


class ProdConfig(Config):
    """Production configuration extending Config.

    Production-specific configuration settings with debugging disabled
    and production database paths.

    Attributes:
        DEBUG: Debug mode flag (False for production).
        SQLALCHEMY_TRACK_MODIFICATIONS: SQLAlchemy modification tracking flag.
        SQLITE_CONFIG_DIR: SQLite configuration directory.
        APP_DB_FILE: Application database file path.
        SQLALCHEMY_DATABASE_URI: SQLAlchemy database URI.
        SCHEDULER_FULL_PATH: Scheduler database full path.
        SCHEDULER_JOBSTORES: APScheduler job store configuration.
        YAML_CONFIG_DIR: YAML configuration directory.
        UNIVERSAL_DB_FILE: Universal database file path.

    Generated by Duo
    """

    DEBUG = False
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLITE_CONFIG_DIR = os.path.join(basedir, 'instance')
    APP_DB_FILE = os.path.join(SQLITE_CONFIG_DIR, 'app.sqlite3')
    SQLALCHEMY_DATABASE_URI = 'sqlite:///' + APP_DB_FILE
    SCHEDULER_FULL_PATH = os.path.join(SQLITE_CONFIG_DIR, 'scheduler.sqlite3')
    # set to NullPool until we know how to handle QueuePool
    SCHEDULER_JOBSTORES: ClassVar[dict[str, Any]] = {
        'default': SQLAlchemyJobStore(url='sqlite:///' + SCHEDULER_FULL_PATH, engine_options={'poolclass': NullPool}),
    }
    YAML_CONFIG_DIR = os.path.join(basedir, 'ap', 'config')
    UNIVERSAL_DB_FILE = os.path.join(SQLITE_CONFIG_DIR, 'transaction')


class DevConfig(Config):
    """Development configuration extending Config.

    Development-specific configuration settings with debugging enabled
    and development database paths.

    Attributes:
        DEBUG: Debug mode flag (True for development).
        SQLALCHEMY_TRACK_MODIFICATIONS: SQLAlchemy modification tracking flag.
        SQLITE_CONFIG_DIR: SQLite configuration directory.
        APP_DB_FILE: Application database file path.
        SQLALCHEMY_DATABASE_URI: SQLAlchemy database URI.
        SCHEDULER_FULL_PATH: Scheduler database full path.
        SCHEDULER_JOBSTORES: APScheduler job store configuration.
        YAML_CONFIG_DIR: YAML configuration directory.
        UNIVERSAL_DB_FILE: Universal database file path.

    Generated by Duo
    """

    DEBUG = True
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    SQLITE_CONFIG_DIR = os.path.join(basedir, 'instance')
    APP_DB_FILE = os.path.join(SQLITE_CONFIG_DIR, 'app.sqlite3')
    SQLALCHEMY_DATABASE_URI = 'sqlite:///' + APP_DB_FILE
    SCHEDULER_FULL_PATH = os.path.join(SQLITE_CONFIG_DIR, 'scheduler.sqlite3')
    # set to NullPool until we know how to handle QueuePool
    SCHEDULER_JOBSTORES: ClassVar[dict[str, Any]] = {
        'default': SQLAlchemyJobStore(url='sqlite:///' + SCHEDULER_FULL_PATH, engine_options={'poolclass': NullPool}),
    }
    YAML_CONFIG_DIR = os.path.join(basedir, 'ap', 'config')
    UNIVERSAL_DB_FILE = os.path.join(SQLITE_CONFIG_DIR, 'transaction')
