import logging
from abc import ABC, abstractmethod

import pandas as pd
from pydantic import BaseModel, ConfigDict, Field

logger = logging.getLogger(__name__)


class TransformData(BaseModel):
    """Data container for ETL transformation pipeline.

    Holds DataFrame and metadata for transformation operations.

    Attributes:
        df: The pandas DataFrame containing the data to transform.
        name_unit_mapping: Dictionary mapping column names to their units.

    Methods:
        with_df: Returns a new instance with updated DataFrame.
        with_name_unit_mapping: Returns a new instance with updated name-unit mapping.

    Generated by Duo.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    df: pd.DataFrame
    # default mapping between column name and unit
    name_unit_mapping: dict[str, str] = Field(default_factory=dict)

    def with_df(self, df: pd.DataFrame) -> 'TransformData':
        self.df = df
        return self

    def with_name_unit_mapping(self, name_unit_mapping: dict[str, str]) -> 'TransformData':
        self.name_unit_mapping = name_unit_mapping
        return self


class BaseTransformer(ABC):
    """Abstract base class for data transformation operations.

    Defines the interface for transforming data in ETL pipelines.

    Methods:
        transform: Abstract method to transform TransformData to another TransformData.

    Generated by Duo.
    """

    @abstractmethod
    def transform(self, data: TransformData) -> TransformData:
        """Transform from data to another data"""


class TransformPipeline:
    """Pipeline for chaining multiple data transformers.

    Executes a sequence of transformers on data, passing output to next transformer.

    Attributes:
        transformers: Tuple of BaseTransformer instances to execute in sequence.

    Methods:
        run: Executes all transformers in sequence on the input data.

    Generated by Duo.
    """

    def __init__(self, *transformers: BaseTransformer) -> None:
        self.transformers = transformers

    def run(self, input_data: TransformData) -> TransformData:
        """Run the pipeline"""
        data = input_data
        for transformer in self.transformers:
            try:
                data = transformer.transform(data)
            except Exception as e:
                logger.error(f'{transformer.__class__.__name__} failed')
                raise e
        return data
