import logging

import pandas as pd

from ap.etl.transform import BaseTransformer, TransformData

logger = logging.getLogger(__name__)


class WebAPITransformer(BaseTransformer):
    """Transforms data extracted from web APIs.

    Ensures all columns are string type and resets the index.

    Attributes:
        api_url: URL of the API source.

    Methods:
        transform: Converts all columns to string type and resets index.

    Generated by Duo.
    """

    def __init__(self, api_url) -> None:
        self.api_url = api_url

    def transform(self, data: TransformData) -> TransformData:
        df = data.df
        if df.empty:
            return data

        # make sure all columns are string, avoiding pandas incorrectly casting them into object
        df = df.astype(pd.StringDtype())

        df = df.reset_index()

        return data.with_df(df)
