from __future__ import annotations

import datetime
import logging
import re
from typing import Final

import arrow
import pandas as pd

from ap import log_execution_time
from ap.common.common_utils import SQLiteFormatStrings
from ap.common.constants import (
    COMMA_BETWEEN_NUMBERS_REGEX,
    DATE_TYPE_REGEX,
    DATETIME_TYPE_MD,
    DATETIME_TYPE_YMD,
    DATETIME_TYPE_YMD_HMS,
    DEFAULT_NONE_VALUE,
    TIME_TYPE_REGEX,
    DataType,
)

logger = logging.getLogger(__name__)


class DateTimeFormatUtils(object):
    """Utility class for parsing and managing datetime format strings.

    Provides functionality to parse datetime format strings and separate them
    into date and time components based on format codes. Supports various
    datetime format patterns and validates format correctness.

    Attributes:
        datetime_format: Complete datetime format string.
        date_format: Date-only portion of the format string.
        time_format: Time-only portion of the format string.
        TIME_FORMAT_CODES: List of time-related format codes.
        DATE_FORMAT_CODES: List of date-related format codes.

    Methods:
        get_datetime_format: Static method to parse and split datetime format string.
        notify_invalid_format: Static method to raise exception for invalid formats.

    Generated by Duo
    """

    datetime_format: str
    date_format: str
    time_format: str

    def __init__(self, dic: dict) -> None:
        self.datetime_format = dic['datetime']
        self.date_format = dic['date']
        self.time_format = dic['time']

    TIME_FORMAT_CODES: Final[list[str]] = ['%H', '%I', '%M', '%S', '%p', '%f', '%z', '%Z']
    DATE_FORMAT_CODES: Final[list[str]] = [
        '%a',
        '%A',
        '%w',
        '%d',
        '%b',
        '%B',
        '%m',
        '%y',
        '%Y',
        '%z',
        '%Z',
        '%j',
        '%U',
        '%W',
        '%c',
        '%x',
        '%G',
        '%u',
        '%V',
    ]

    @staticmethod
    def get_start_index_by_codes(datetime_format_str: str, format_codes: list[str]):
        indexes = [datetime_format_str.index(code) for code in format_codes if code in datetime_format_str]
        return min(indexes) if indexes else None

    @staticmethod
    def get_datetime_format(datetime_format_str: str):
        format_dict = {
            'datetime': datetime_format_str if datetime_format_str is not None and datetime_format_str != '' else None,
            'date': None,
            'time': None,
        }

        if format_dict['datetime'] is None:
            return DateTimeFormatUtils(format_dict)

        time_start_index = DateTimeFormatUtils.get_start_index_by_codes(
            datetime_format_str, DateTimeFormatUtils.TIME_FORMAT_CODES
        )
        date_start_index = DateTimeFormatUtils.get_start_index_by_codes(
            datetime_format_str, DateTimeFormatUtils.DATE_FORMAT_CODES
        )

        if time_start_index is not None and date_start_index is not None:
            # These are valid indexes if and only if one of them is zero
            if time_start_index == 0:
                format_dict['time'] = datetime_format_str[:date_start_index].strip()
                format_dict['date'] = datetime_format_str[date_start_index:].strip()
            elif date_start_index == 0:
                format_dict['time'] = datetime_format_str[time_start_index:].strip()
                format_dict['date'] = datetime_format_str[:time_start_index].strip()
        elif time_start_index is not None and date_start_index is None:
            format_dict['time'] = datetime_format_str[time_start_index:]
        elif time_start_index is None and date_start_index is not None:
            format_dict['date'] = datetime_format_str[date_start_index:]
        else:
            DateTimeFormatUtils.notify_invalid_format()

        return DateTimeFormatUtils(format_dict)

    @staticmethod
    def notify_invalid_format():
        raise Exception('Invalid datetime format!!!')


def format_datetime(series: pd.Series, datetime_formula_format: str, client_timezone: str | None = None) -> pd.Series:
    # Convert datetime base on datetime format
    if datetime_formula_format:
        datetime_series = pd.to_datetime(series, errors='coerce', format=datetime_formula_format)

        if client_timezone:
            series = convert_client_timezone(datetime_series, client_timezone)
        else:
            series = datetime_series.dt.strftime(SQLiteFormatStrings.DATETIME.value).astype(pd.StringDtype())

        return series

    if pd.api.types.is_object_dtype(series):
        series = series.astype(pd.StringDtype())

    if not pd.api.types.is_string_dtype(series):
        return series

    series = datetime_transform(series)
    if client_timezone:
        series = pd.to_datetime(series, errors='coerce', format='mixed')
        series = convert_client_timezone(series, client_timezone)

    return series


def convert_client_timezone(series: pd.Series, client_timezone: str) -> pd.Series:
    if pd.api.types.is_object_dtype(series):
        series = pd.to_datetime(series, errors='coerce', utc=True)
    if series.dt.tz:
        series = series.dt.tz_convert(client_timezone).astype(pd.StringDtype())
    else:
        series = series.dt.tz_localize(client_timezone).astype(pd.StringDtype())

    return series


def format_date(series: pd.Series, date_format: str | None = None) -> pd.Series:
    # Convert date base on date format
    if date_format:
        return (
            pd.to_datetime(series, errors='coerce', format=date_format)
            .dt.strftime(SQLiteFormatStrings.DATE.value)
            .astype(pd.StringDtype())
        )

    if pd.api.types.is_datetime64_dtype(series):
        return series.dt.strftime(SQLiteFormatStrings.DATE.value).astype(pd.StringDtype())

    # try to convert to date using pandas, and replaced those cannot be converted with old values
    date_series = pd.to_datetime(series, errors='coerce').dt.strftime(SQLiteFormatStrings.DATE.value)
    is_na = date_series.isna()
    date_series.loc[is_na] = series.loc[is_na].astype(pd.StringDtype())

    return date_transform(date_series)


def format_time(series: pd.Series, time_format: str | None = None) -> pd.Series:
    # Convert time base on time format
    if time_format:
        return (
            pd.to_datetime(series, errors='coerce', format=time_format)
            .dt.strftime(SQLiteFormatStrings.TIME.value)
            .astype(pd.StringDtype())
        )

    if pd.api.types.is_datetime64_dtype(series):
        return series.dt.strftime(SQLiteFormatStrings.TIME.value).astype(pd.StringDtype())

    # try to convert to time using pandas, and replaced those cannot be converted with old values
    time_series = pd.to_datetime(series, errors='coerce').dt.strftime(SQLiteFormatStrings.TIME.value)
    is_na = time_series.isna()
    time_series.loc[is_na] = series.loc[is_na].astype(pd.StringDtype())

    return time_transform(time_series)


@log_execution_time()
def datetime_transform(datetime_series, date_only=False) -> pd.Series:
    current_year = datetime.datetime.now().strftime('%Y')

    def without_year_datetime(m: re.Match[str]) -> str:
        result = f'{current_year}-{m.group("m")}-{m.group("d")}'
        if not date_only:
            result += ' 00:00:00'
        return result

    def full_datetime(m: re.Match[str]) -> str:
        if len(m.group('y')) == 4:
            result = f'{m.group("y")}-{m.group("m")}-{m.group("d")}'
        else:
            # if there is 2 digit of year, convert to full year
            result = f'{current_year[0:2]}{m.group("y")}-{m.group("m")}-{m.group("d")}'
        if not date_only:
            result += ' 00:00:00'
        return result

    def actual_datetime(m: re.Match[str]) -> str:
        result = f'{m.group("y")}-{m.group("m")}-{m.group("d")}'
        if not date_only:
            result += f' {m.group("h")}:{m.group("min")}:{m.group("s")}'
        return result

    # convert special datetime string to iso-format
    datetime_series = datetime_series.str.replace(DATETIME_TYPE_MD, without_year_datetime, regex=True)
    datetime_series = datetime_series.str.replace(DATETIME_TYPE_YMD, full_datetime, regex=True)
    datetime_series = datetime_series.str.replace(DATETIME_TYPE_YMD_HMS, actual_datetime, regex=True)

    # convert comma to dot for barcelona data
    # this is a workaround for <https://github.com/pandas-dev/pandas/issues/59256>
    datetime_series = datetime_series.str.replace(COMMA_BETWEEN_NUMBERS_REGEX, '.', regex=True)

    return datetime_series


@log_execution_time()
def date_transform(date_series) -> pd.Series:
    """
    Convert date series to standard date format

    Support input formats:

    - YYYY/MM/DD
    - YYYY-MM-DD
    - YYYY年MM月DD日

    Args:
        date_series (pd.Series): a series of time

    Returns:
        A series of date with standard format YYYY-MM-DD
    """
    separate_char = '-'
    begin_part_of_year = datetime.datetime.now().year.__str__()[:2]
    return date_series.str.replace(
        DATE_TYPE_REGEX,
        lambda m: (
            f'{m.group("year") if len(m.group("year")) == 4 else begin_part_of_year + m.group("year")}'
            f'{separate_char}'
            f'{m.group("month").rjust(2, "0")}'
            f'{separate_char}'
            f'{m.group("day").rjust(2, "0")}'
        ),
        regex=True,
    )


@log_execution_time()
def time_transform(time_series) -> pd.Series:
    """
    Convert time series to standard time format

    Support input formats:

    - HH:mm:ss
    - HH-mm-ss
    - HH.mm.ss
    - HH mm ss
    - HH時mm分ss秒

    Args:
        time_series (pd.Series): a series of time

    Returns:
        A series of time with standard format HH:MM:SS
    """
    separate_char = ':'
    return time_series.str.replace(
        TIME_TYPE_REGEX,
        lambda m: (
            f'{m.group("hour").rjust(2, "0")}'
            f'{separate_char}'
            f'{m.group("minute").rjust(2, "0")}'
            f'{separate_char}'
            f'{m.group("second").rjust(2, "0")}'
        ),
        regex=True,
    )


@log_execution_time()
def convert_datetime_format(
    df,
    dic_data_type: dict[str, str],  # {str, DataType.name}
    datetime_format: str | None = None,
    client_timezone: str | None = None,
) -> pd.DataFrame:
    datetime_format_obj = DateTimeFormatUtils.get_datetime_format(datetime_format)
    for col, data_type in dic_data_type.items():
        if col not in df.columns:
            continue
        try:
            if data_type == DataType.DATETIME.name:
                df[col] = format_datetime(
                    series=df[col],
                    datetime_formula_format=datetime_format_obj.datetime_format,
                    client_timezone=client_timezone,
                )

            elif data_type == DataType.DATE.name:
                df[col] = format_date(df[col], date_format=datetime_format_obj.date_format)

            elif data_type == DataType.TIME.name:
                df[col] = format_time(df[col], time_format=datetime_format_obj.time_format)

            df[col] = df[col].replace({pd.NaT: DEFAULT_NONE_VALUE})

        except Exception as e:
            logger.exception(e)
            df[col] = DEFAULT_NONE_VALUE

    return df


# Regex patterns
FORMAT_PATTERNS = [
    # ISO 8601 with Z (timezone)
    (r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z$', 'YYYY-MM-DDTHH:mm:ss.SSSSSS[Z]'),
    (r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$', 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'),
    (r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$', 'YYYY-MM-DDTHH:mm:ss[Z]'),
    (r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$', 'YYYY-MM-DDTHH:mm:ss'),
    # With timezone offset
    (r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}$', 'YYYY-MM-DDTHH:mm:ssZZ'),
    (r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}$', 'YYYY-MM-DD HH:mm:ssZZ'),
    # Datetime with microseconds
    (r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{6}$', 'YYYY-MM-DD HH:mm:ss.SSSSSS'),
    (r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}$', 'YYYY-MM-DD HH:mm:ss.SSS'),
    (r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$', 'YYYY-MM-DD HH:mm:ss'),
    # Common formats
    (r'^\d{2}/\d{2}/\d{4} \d{2}:\d{2}:\d{2}$', 'DD/MM/YYYY HH:mm:ss'),
    (r'^\d{2}-\d{2}-\d{4} \d{2}:\d{2}$', 'DD-MM-YYYY HH:mm'),
    # Date only
    (r'^\d{4}-\d{2}-\d{2}$', 'YYYY-MM-DD'),
    (r'^\d{8}$', 'YYYYMMDD'),
    (r'^\d{2}/\d{2}/\d{4}$', 'DD/MM/YYYY'),
    (r'^\d{2}-\d{2}-\d{4}$', 'DD-MM-YYYY'),
    # New case: microseconds only (added)
    (r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{2}$', 'YYYY-MM-DD HH:mm:ss.SS'),  # microseconds with 2 digits
]


def detect_datetime_format(value: str) -> str | None:
    """Detect datetime format from a string value.

    Analyzes the input string and matches it against predefined regex patterns
    to identify the datetime format. Supports ISO 8601, common date/time formats,
    and formats with timezone information.

    Args:
        value: String value to analyze for datetime format detection.

    Returns:
        Format string (e.g., 'YYYY-MM-DD HH:mm:ss') if a match is found,
        None if no pattern matches the input.

    Examples:
        >>> detect_datetime_format('2024-12-19T10:30:45.123456Z')
        'YYYY-MM-DDTHH:mm:ss.SSSSSS[Z]'
        >>> detect_datetime_format('2024-12-19T10:30:45.123Z')
        'YYYY-MM-DDTHH:mm:ss.SSS[Z]'
        >>> detect_datetime_format('2024-12-19T10:30:45Z')
        'YYYY-MM-DDTHH:mm:ss[Z]'
        >>> detect_datetime_format('2024-12-19T10:30:45')
        'YYYY-MM-DDTHH:mm:ss'
        >>> detect_datetime_format('2024-12-19T10:30:45+10:00')
        'YYYY-MM-DDTHH:mm:ssZZ'
        >>> detect_datetime_format('2024-12-19 10:30:45+10:00')
        'YYYY-MM-DD HH:mm:ssZZ'
        >>> detect_datetime_format('2024-12-19T10:30:45-10:00')
        'YYYY-MM-DDTHH:mm:ssZZ'
        >>> detect_datetime_format('2024-12-19 10:30:45-10:00')
        'YYYY-MM-DD HH:mm:ssZZ'
        >>> detect_datetime_format('2024-12-19')
        'YYYY-MM-DD'
        >>> detect_datetime_format('invalid')

    """
    value = value.strip()

    # Loop through all patterns and match the input string
    for pattern, fmt in FORMAT_PATTERNS:
        if re.match(pattern, value):
            return fmt

    # Return None if no pattern matches
    return None


def format_datetime_to_str(dt: datetime.datetime, input_format_str):
    """
    Convert a Python datetime object to a formatted string.

    Parameters:
    - dt: Python datetime object
    - input_format_str: A string specifying the desired format (e.g., 'YYYY-MM-DDTHH:mm:ss.SSSSSS[Z]')

    Returns:
    - Formatted datetime string

    Examples:
        >>> format_datetime_to_str(\
                datetime.datetime(year=2025, month=12, day=12, hour=12, minute=12, second=12, microsecond=123456),\
                'YYYY-MM-DDTHH:mm:ss.SSSSSS[Z]'\
            )
        '2025-12-12T12:12:12.123456Z'
        >>> format_datetime_to_str(\
                datetime.datetime(year=2025, month=12, day=12, hour=12, minute=12, second=12, microsecond=123456),\
                'YYYY-MM-DDTHH:mm:ss.SSS[Z]'\
            )
        '2025-12-12T12:12:12.123Z'
        >>> format_datetime_to_str(\
                datetime.datetime(year=2025, month=12, day=12, hour=12, minute=12, second=12, microsecond=123456),\
                'YYYY-MM-DDTHH:mm:ss[Z]'\
            )
        '2025-12-12T12:12:12Z'
        >>> format_datetime_to_str(\
                datetime.datetime(year=2025, month=12, day=12, hour=12, minute=12, second=12, microsecond=123456),\
                'YYYY-MM-DDTHH:mm:ss'\
            )
        '2025-12-12T12:12:12'
        >>> format_datetime_to_str(\
                datetime.datetime(year=2025, month=12, day=12, hour=12, minute=12, second=12, microsecond=123456,\
                    tzinfo=datetime.timezone(datetime.timedelta(hours=7, minutes=30))),\
                'YYYY-MM-DDTHH:mm:ssZZ'\
            )
        '2025-12-12T12:12:12+07:30'
        >>> format_datetime_to_str(\
                datetime.datetime(year=2025, month=12, day=12, hour=12, minute=12, second=12, microsecond=123456,\
                    tzinfo=datetime.timezone(datetime.timedelta(hours=7, minutes=30))),\
                'YYYY-MM-DD HH:mm:ssZZ'\
            )
        '2025-12-12 12:12:12+07:30'
        >>> format_datetime_to_str(\
                datetime.datetime(year=2025, month=12, day=12, hour=12, minute=12, second=12, microsecond=123456,\
                    tzinfo=datetime.timezone(datetime.timedelta(hours=-7, minutes=0))),\
                'YYYY-MM-DDTHH:mm:ssZZ'\
            )
        '2025-12-12T12:12:12-07:00'
        >>> format_datetime_to_str(\
                datetime.datetime(year=2025, month=12, day=12, hour=12, minute=12, second=12, microsecond=123456,\
                    tzinfo=datetime.timezone(datetime.timedelta(hours=-7, minutes=0))),\
                'YYYY-MM-DD HH:mm:ssZZ'\
            )
        '2025-12-12 12:12:12-07:00'
    """
    dt_arrow = arrow.get(dt)
    return dt_arrow.format(input_format_str)
