# This file contains specific google analytic.
# This file should never import other files rather than `contansts.py`, or `commons_utils.py`
import dataclasses
import os
import platform
from enum import Enum
from typing import Union

from loguru import logger

from ap.common.constants import APP_TYPE_ENV, EMPTY_STRING, BaseEnum
from ap.common.memoize import CustomCache

GTAG_DEFAULT_TIMEOUT = 3

# GA tracking ID
GA_TRACKING_ID = 'G-9DJ9TV72B5'

VERSION_FILE_NAME = 'VERSION'


class StrEnumWithLowerCase(str, Enum):
    """String enum for insensitive cases"""

    def __eq__(self, other: Union[str, BaseEnum]) -> bool:
        """Compare enum values case-insensitively.

        Compares this enum value with another value by converting both to lowercase
        and stripping whitespace before comparison.

        Args:
            other: The value to compare with. Can be a string or BaseEnum instance.

        Returns:
            True if the lowercase, stripped values are equal, False otherwise.

        Generated by Duo.
        """
        return self.lower().strip() == other.lower().strip()

    def __hash__(self) -> int:
        """Return hash of the lowercase, stripped string value.

        Computes the hash based on the lowercase, stripped version of the enum value
        to ensure consistency with the __eq__ method.

        Returns:
            The hash value of the lowercase, stripped string.

        Generated by Duo.
        """
        return hash(self.lower().strip())

    @classmethod
    def get(cls, value, default=None):
        for v in cls:
            if v == value:
                return v
        return default


class AppGroup(StrEnumWithLowerCase):
    """Application group enumeration for categorizing application instances.

    Defines the different groups an application can belong to:
    - DN: Production/DN group
    - Dev: Development group
    - Ext: External group

    Generated by Duo.
    """

    DN = 'DN'
    Dev = 'Dev'
    Ext = 'Ext'


class AppSource(StrEnumWithLowerCase):
    """Application source enumeration for identifying the origin of the application.

    Defines the source types:
    - OSS: Open Source Software
    - DN: DN source

    Generated by Duo.
    """

    OSS = 'OSS'
    DN = 'DN'


class AppType(StrEnumWithLowerCase):
    """Application type enumeration for deployment environment classification.

    Defines the deployment types:
    - Edge: Edge deployment
    - Cloud: Cloud deployment

    Generated by Duo.
    """

    Edge = 'Edge'
    Cloud = 'Cloud'


class OsSystem(StrEnumWithLowerCase):
    """Operating system enumeration for platform identification.

    Defines the supported operating systems:
    - WINDOWS: Windows operating system
    - LINUX: Linux operating system
    - MACOS: macOS operating system (Darwin)

    Generated by Duo.
    """

    WINDOWS = 'Windows'
    LINUX = 'Linux'
    MACOS = 'Darwin'


@dataclasses.dataclass
class AppOs:
    """Application operating system information dataclass.

    Captures the operating system details of the application environment.

    Attributes:
        system: The operating system type (Windows, Linux, or macOS).
        release: The OS release version.
        machine: The machine hardware architecture.

    Methods:
        value: Returns the string value of the operating system.

    Generated by Duo.
    """

    system: OsSystem = dataclasses.field(default_factory=lambda: OsSystem(platform.system()))
    release: str = platform.release()
    machine: str = platform.machine()

    @property
    def value(self) -> str:
        return self.system.value


@dataclasses.dataclass
class GA:
    """Info that we send to google analytics"""

    # app_file: str
    app_group: AppGroup
    app_source: AppSource
    app_type: AppType

    app_version: str
    config_version: str

    app_os: AppOs

    @classmethod
    @CustomCache.memoize()
    def get_ga_info(cls, version_file: str) -> 'GA':
        """Get all application configuration and cache it so that we can get all of them later without querying"""
        version_info = []
        if not os.path.exists(version_file):
            logger.error('VERSION file does not exist')
        else:
            with open(version_file) as f:
                # version file structure
                # `VERSION`
                # `config version`
                # `App source`
                version_info = f.readlines()

        app_version = version_info[0].strip() if version_info else EMPTY_STRING
        if '%%VERSION%%' in app_version:
            app_version = 'v00.00.000.00000000'

        config_version = version_info[1].strip() if len(version_info) > 1 else EMPTY_STRING
        if config_version == EMPTY_STRING:
            config_version = '0'

        app_source = version_info[2].strip() if len(version_info) > 2 else EMPTY_STRING
        # default to DN
        app_source = AppSource.get(app_source, default=AppSource.DN)

        app_type = os.environ.get(APP_TYPE_ENV, EMPTY_STRING)
        # default Edge
        app_type = AppType.get(app_type, default=AppType.Edge)

        app_group_str = os.environ.get('group', EMPTY_STRING)
        app_group = get_app_group(app_source, app_group_str)

        app_os = AppOs()

        return GA(
            app_group=app_group,
            app_source=app_source,
            app_type=app_type,
            app_version=app_version,
            config_version=config_version,
            app_os=app_os,
        )


def get_app_group(app_source: AppSource | None, app_group_str: str) -> AppGroup:
    """
    Get app group from app source and app group str (sepcified by environment variable `group`)
    if app group is specified correctly, use it.
    if app group is not specified correctly, check based on app source
    """
    # force return to dev if app_group is set
    if AppGroup.Dev == app_group_str:
        return AppGroup.Dev

    # force return to dn if app_source is set
    if app_source is not None and app_source == AppSource.DN:
        return AppGroup.DN

    # infer based on string
    return AppGroup.get(app_group_str, AppGroup.Ext)
