from __future__ import annotations

import datetime as dt
import glob
import math
import os
import sys
from collections.abc import Mapping
from datetime import date as ddate
from datetime import datetime, timedelta
from functools import wraps
from pathlib import Path
from time import perf_counter
from typing import Any, TextIO, Union
from zipfile import ZipFile

import loguru
from loguru import logger

LOG_FORMAT = '{time:YYYY-MM-DD HH:mm:ss,SSSZZ} {level} {name}:{function}:{line} - {message}'

ROTATE_BY_SIZE = 50 * 1024 * 1024  # 50MB
DELETE_ZIPPED_FILE_OLDER_THAN = 5  # weeks
LOG_MEMORY_BATCH_SIZE = 100  # keep 100 messages in memory

BASE_FILENAME_FORMAT = '%Y%m%d_%H%M%S'
ZIP_FILENAME_FORMAT = '%Yw%W_%m%d'

ZIP_LOG_INTERVAL = 60 * 60 * 24 * 7  # 7 day
CLEAN_ZIP_INTERVAL = 60 * 60 * 24 * 7 * 4  # 4 weeks


def shift_date_to_monday(dt: datetime) -> datetime:
    week_day = dt.weekday()
    return dt - timedelta(days=week_day)


def get_filename_without_ext_from_abspath(absolute_path: str) -> str | None:
    path, filename = os.path.split(absolute_path)
    if not filename:
        return None
    filename = filename.split('.')[0]
    return filename


def get_datetime_from_file(filename: str, fmt: str) -> datetime:
    file_without_ext = get_filename_without_ext_from_abspath(filename)

    # datetime string always put at the beginning of the filename
    datetime_str_example = datetime.now().strftime(fmt)
    prefix_file_without_ext = file_without_ext[: len(datetime_str_example)]

    return datetime.strptime(prefix_file_without_ext, fmt)


def get_datetime_from_zip_log_file(filename: str) -> tuple[datetime | None, datetime | None]:
    """
    Input:  2026w09_0302
    Output: (start_date, end_date)  # end = start + 7 days
    """
    try:
        year_part, rest = filename.split('w', 1)
        md_part = rest.split('_', 1)[1]

        year = int(year_part)
        month = int(md_part[:2])
        day = int(md_part[2:4])

        start_date = datetime(year, month, day)
        end_date = start_date + timedelta(days=7)

        return start_date, end_date

    except Exception:
        return None, None


def create_log_filename_from_datetime(dt: Union[datetime, ddate], suffix=None) -> str:
    file_name = dt.strftime(BASE_FILENAME_FORMAT)
    if suffix:
        file_name = f'{file_name}_{suffix}'

    return file_name + '.log'


def get_base_filename(basedir, suffix=None):
    """Generate log file basename"""
    if not basedir:
        basedir = 'log'
    return os.path.join(basedir, create_log_filename_from_datetime(datetime.now(), suffix))


class ZipFileHandler:
    """Handler for zipping and managing archived log files.

    Provides utilities for compressing old log files into weekly zip archives
    and cleaning up old archives to manage disk space.

    Methods:
        create_zip_filename_from_datetime: Creates a zip filename based on datetime.
        create_zip_filename_from_logfile: Creates a zip filename from a log file path.
        zip_all_files: Compresses multiple files into a single zip archive.
        should_zip_file: Determines if a file should be zipped based on its age.
        zip_all_previous_files: Zips all log files from previous weeks.
        should_delete_zipped_file: Determines if a zipped file should be deleted.
        delete_old_zipped_files: Removes zip files older than the retention period.

    Generated by Duo.
    """

    @staticmethod
    def create_zip_filename_from_datetime(dt: Union[datetime, ddate]) -> str:
        """Create zip file based on date_time"""
        first_date_of_week = dt - timedelta(days=dt.weekday())
        return first_date_of_week.strftime(ZIP_FILENAME_FORMAT) + '.zip'

    @staticmethod
    def create_zip_filename_from_logfile(logfile: str) -> str:
        dt = get_datetime_from_file(logfile, BASE_FILENAME_FORMAT)
        zip_filename = ZipFileHandler.create_zip_filename_from_datetime(dt)
        parent = Path(logfile).parent
        return str(parent / zip_filename)

    @staticmethod
    def zip_all_files(files: list[str], zip_filename: str):
        """Zip all the files into a zip"""
        if not files:
            return
        with ZipFile(zip_filename, 'w') as zf:
            for file in files:
                _, basename = os.path.split(file)
                zf.write(file, arcname=basename)
                os.remove(file)

    @staticmethod
    def should_zip_file(current_date: datetime, creation_date: datetime) -> bool:
        """Check if we should zip the file with creation_date
        All the file with created before this week should be zipped
        """
        current_date_monday = shift_date_to_monday(current_date)
        creation_date_monday = shift_date_to_monday(creation_date)
        return current_date_monday - creation_date_monday >= timedelta(weeks=1)

    @staticmethod
    def zip_all_previous_files_gen(path: Path, job_management=None):
        """Generator function for zipping all previous files which in the same week into a single zip file"""
        from ap.common.jobs.job_info_schema import ZipLogFilesJobInfo

        yield 0
        # only run this if we have log files to be zipped
        current_date = datetime.now()
        files_to_be_zipped: dict[str, list[str]] = {}

        # gather all log files should be zipped
        for logfile in glob.glob(os.path.join(path, '*.log')):
            creation_date = get_datetime_from_file(logfile, BASE_FILENAME_FORMAT)
            if not ZipFileHandler.should_zip_file(current_date, creation_date):
                break
            zip_filename = ZipFileHandler.create_zip_filename_from_logfile(logfile)
            if zip_filename not in files_to_be_zipped:
                files_to_be_zipped[zip_filename] = [logfile]
            else:
                files_to_be_zipped[zip_filename].append(logfile)

        # count total files to be zipped
        total_files_zipped = sum(len(logfiles) for logfiles in files_to_be_zipped.values())

        # update job info
        if job_management:
            job_management.info = ZipLogFilesJobInfo(total_files_zipped=total_files_zipped)
            if total_files_zipped == 0:
                job_management.info.info('No log files to zip')

        yield 50

        for zip_filename, logfiles in files_to_be_zipped.items():
            ZipFileHandler.zip_all_files(logfiles, zip_filename)

        yield 100

    @staticmethod
    def should_delete_zipped_file(
        current_date: datetime,
        creation_date: datetime,
        week_offset: int = DELETE_ZIPPED_FILE_OLDER_THAN,
    ) -> bool:
        current_date_monday = shift_date_to_monday(current_date)
        creation_date_monday = shift_date_to_monday(creation_date)
        return current_date_monday - creation_date_monday >= timedelta(weeks=week_offset)

    @staticmethod
    def delete_old_zipped_files(path: Path, **_kwargs: Mapping[str, Any]):
        """Delete zip file older than day_offset"""
        current_date = datetime.now()
        for file in glob.glob(os.path.join(path, '*.zip')):
            if not os.path.exists(file):
                continue
            creation_date = get_datetime_from_file(file, ZIP_FILENAME_FORMAT)
            if ZipFileHandler.should_delete_zipped_file(current_date, creation_date):
                os.remove(file)


def setup_console_logger(log_level: str = 'INFO') -> int:
    return logger.add(
        sys.stdout,
        level=log_level,
        format=LOG_FORMAT,
        # do not emit too long traceback
        backtrace=True,
        # do not emit as json
        serialize=False,
    )


def setup_logfile_logger(
    log_dir: str,
    log_level: str = 'INFO',
    is_main: bool = True,
    rotate_size: int = ROTATE_BY_SIZE,
    rotate_at=dt.time(23, 59, 59, 999),
    rotate_every=dt.timedelta(days=1),
    batch_size: int = LOG_MEMORY_BATCH_SIZE,
) -> int:
    rotator = LogRotator(size=rotate_size, at=rotate_at, every=rotate_every)

    pid = os.getpid()
    suffix_pid = f'{pid:06d}_main' if is_main else f'{pid:06d}'

    return logger.add(
        Path(log_dir) / f'{{time:YYYYMMDD_HHmmss}}_{suffix_pid}.log',
        level=log_level,
        format=LOG_FORMAT,
        # store 100 lines before writing to files
        # by default python store `https://docs.python.org/3/library/io.html#io.DEFAULT_BUFFER_SIZE`
        # in memory before emitting to disk
        buffering=batch_size,
        # each log file should be at most 50 MB
        rotation=rotator.should_rotate,
    )


class LogRotator:
    """Rotator by time and size for logging
    https://loguru.readthedocs.io/en/stable/resources/recipes.html#rotating-log-file-based-on-both-size-and-time
    """

    def __init__(self, *, size: float, at: dt.time, every: dt.timedelta) -> None:
        now = dt.datetime.now()

        self._size_limit = size
        self._time_limit = now.replace(hour=at.hour, minute=at.minute, second=at.second)
        self._every = every

        # The current time is already past the target time so it would rotate already.
        self.calculate_next_time_limit(now)

    def should_rotate(self, message: loguru.Message, file: TextIO) -> bool:
        file.seek(0, 2)

        filesize = file.tell()
        # new file, do not rotate
        if filesize == 0:
            return False

        # exceed: rotate by size
        if filesize + len(message) > self._size_limit:
            return True

        # exceed: rotate by time
        if message.record['time'].timestamp() >= self._time_limit.timestamp():
            self.calculate_next_time_limit(message.record['time'])
            return True

        return False

    def calculate_next_time_limit(self, at: dt.datetime):
        excess = at.timestamp() - self._time_limit.timestamp()
        if excess >= 0:
            seconds = math.ceil(excess / self._every.total_seconds()) * self._every.total_seconds()
            self._time_limit += dt.timedelta(seconds=seconds)


def bind_user_info(req=None, res=None):
    logger.info(f'REQUEST: {req.method} {req.full_path}')
    if res:
        logger.info(f'RESPONSE: {res.status_code}')
    return logger


def log_execution_time(prefix='', logging_exception=True):
    """Decorator to log function run time
    Arguments:
        fn {function} -- [description]
        prefix {string} -- prefix set to logged message
    Returns:
        fn {function} -- [description]
    """

    def decorator(fn):
        @wraps(fn)
        def wrapper(*args: Any, **kwargs: Mapping[str, Any]):
            start_dt = datetime.now()
            start = perf_counter()
            try:
                result = fn(*args, **kwargs)
            except Exception as e:
                logger.exception(e)
                raise e
            finally:
                print_log_with_processing_time(start, start_dt)
            return result

        def print_log_with_processing_time(start, start_dt):
            end = perf_counter()
            count_time = end - start
            log_func = logger.info if count_time >= 1 else logger.debug
            log_func(
                '{log_prefix} Function: {function}; START: {start_time}; ExecTime: {exec_time:.6f}s',
                log_prefix=prefix,
                function=fn.__name__,
                start_time=start_dt,
                exec_time=count_time,
            )

        return wrapper

    return decorator
