from __future__ import annotations

import uuid
from collections import defaultdict
from dataclasses import dataclass
from functools import cached_property
from typing import Any, Self, Union

import sqlalchemy as sa

from ap.api.common.services.utils import gen_proc_time_label
from ap.common.common_utils import BoundType, TimeRangeStr, gen_sql_label, gen_sql_like_value
from ap.common.constants import (
    EPOCH,
    TIME_COL,
    DuplicateSerialShow,
    FilterFunc,
    RawDataTypeDB,
)
from ap.common.log import log_execution_time
from ap.setting_module.models import CfgFilterDetail, CfgProcessColumn, CfgTrace
from ap.trace_data.schemas import ConditionProc, ConditionProcDetail
from ap.trace_data.transaction_model import TransactionData

ROW_NUMBER_COL_PREFIX = 'cum_count'

CTE_PROCESS_PREFIX = 'cte_p'

PROCESS_ALIAS_PREFIX = 'p'
NORMAL_FILTER_ALIAS_PREFIX = 'pn'
MASTER_FILTER_ALIAS_PREFIX = 'pm'
SHOW_CATEGORY_ALIAS_PREFIX = 'ps'

SEMI_TABLE_ALIAS_PREFIX = 's'
MASTER_MAPPING_PREFIX = 'm'

MAPPING_PART_NO = 'mapping_part'
MAPPING_LINE = 'mapping_line'
MAPPING_MACHINE = 'mapping_equip'
MAPPING_PROCESS = 'mapping_process'

SQL_GENERATOR_PREFIX = 'SQL_GENERATOR'

NOT_MATERIALIZED = 'NOT MATERIALIZED'

FILTER_PREFIX = 'filtered'

TIMEDIFF_PREFIX = 'timediff'
RANK_BY_TIMEDIFF = 'rank_by_timediff'
CTE_TRACING_TIMEDIFF = 'cte_tracing_timediff'
CTE_TRACING_RANK_BY_TIMEDIFF = 'cte_tracing_rank_by_timediff'
CTE_TRACING_MIN_TIMEDIFF = 'cte_tracing_min_timediff'


def gen_alias_col_name(trans_data: TransactionData, column_name: str) -> str | None:
    cfg_column = trans_data.get_cfg_column_by_name(column_name)
    if cfg_column is None:
        return None

    alias_name = gen_sql_label(cfg_column.id, cfg_column.column_name)
    return alias_name


def gen_row_number_col_name(proc_id: int) -> str:
    return f'{ROW_NUMBER_COL_PREFIX}_{proc_id}'


def join_table(
    join_conditions: sa.Join | None,
    left: Any,
    right: Any,
    onclause: Union[sa.Operators, bool],
    isouter: bool = True,
) -> sa.Join:
    if join_conditions is None:
        return sa.join(left=left, right=right, onclause=onclause, isouter=isouter)
    return join_conditions.join(right=right, onclause=onclause, isouter=isouter)


@dataclass(frozen=True)
class SqlProcLinkKey:
    """Immutable data class representing a process link key for SQL queries.

    This class stores information about a column used as a link key between processes,
    including substring extraction parameters and delta time settings.

    Attributes:
        id: Column ID.
        name: Column name.
        substr_from: Starting position for substring extraction (1-indexed).
        substr_to: Ending position for substring extraction (inclusive).
        delta_time: Time difference in minutes for time-based linking.
        cut_off: Tolerance window in minutes for time-based linking.
        is_delta_time_cut_off_linked: Whether this key uses delta time/cut-off linking.

    Properties:
        good: Returns True if the key has valid substring or delta time settings.
        bad: Returns True if the key lacks valid settings.
        cfg_col: Cached CfgProcessColumn configuration object.
        sql_label: SQL label for the column.
        unixepoch_sql_label: SQL label with UNIXEPOCH suffix for time columns.

    Generated by Duo.
    """

    id: int
    name: str
    substr_from: int | None
    substr_to: int | None
    delta_time: float | None
    cut_off: float | None
    is_delta_time_cut_off_linked: bool

    @property
    def good(self) -> bool:
        return (self.substr_from and self.substr_to) or self.is_delta_time_cut_off_linked

    @property
    def bad(self) -> bool:
        return not self.good

    @cached_property
    def cfg_col(self) -> CfgProcessColumn | None:
        return CfgProcessColumn.get_by_id(self.id)

    @property
    def sql_label(self) -> str:
        return self.cfg_col.gen_sql_label()

    @property
    def epoch_sql_label(self) -> str:
        return f'{self.sql_label}_{EPOCH}'


class SqlProcLink:
    """Represents a process link in SQL query generation for tracing data.

    This class encapsulates all information needed to generate SQL queries for
    linking processes together in trace analysis, including link keys, time ranges,
    and filter conditions.

    Attributes:
        process_id: ID of the process.
        table_name: Name of the transaction table.
        time_col: Name of the time column.
        select_col_ids: List of column IDs to select.
        select_col_names: List of column names to select.
        start_tm: Start time for the query.
        end_tm: End time for the query.
        link_keys: List of link keys for joining with previous process.
        next_link_keys: List of link keys for joining with next process.
        sql: Generated SQL query string.
        params: SQL query parameters.
        temp_table_name: Name of temporary table if used.
        time_ranges: List of time range tuples.
        trans_data: TransactionData model for this process.
        condition_procs: List of filter conditions for this process.
        is_start_proc: Whether this is the starting process in the trace.

    Properties:
        has_link_keys: Returns True if link keys exist.
        link_cfg_columns: List of CfgProcessColumn objects for link keys.
        all_link_key_ids: Set of all link key column IDs.
        all_link_keys_labels: Set of all link key SQL labels.
        condition_procs_column_id: Set of column IDs used in filter conditions.
        all_cfg_columns: List of all CfgProcessColumn objects needed for the query.

    Methods:
        gen_proc_time_label: Generate time column label for this process.
        filter_conditions: Generate filter conditions for the CTE.
        apply_filter: Apply filter conditions to a CTE.
        gen_cte: Generate Common Table Expression for this process.
        gen_cached_unixepoch_cte: Generate CTE with cached UNIXEPOCH columns.

    Generated by Duo.
    """

    process_id: int
    table_name: str
    time_col: str
    select_col_ids: list[int]
    select_col_names: list[str]
    start_tm: str
    end_tm: str
    link_keys: list[SqlProcLinkKey]
    next_link_keys: list[SqlProcLinkKey]
    sql: str
    params: str
    temp_table_name: str
    time_ranges: list[tuple[str]]
    trans_data: TransactionData
    condition_procs: list[ConditionProc]
    is_start_proc: bool = False

    @property
    def has_link_keys(self) -> bool:
        """Determine if we have link keys"""
        return bool(self.link_keys or self.next_link_keys)

    @property
    def link_cfg_columns(self) -> list[CfgProcessColumn]:
        return CfgProcessColumn.get_by_ids(self.all_link_key_ids)

    @cached_property
    def all_link_key_ids(self) -> set[int]:
        """Get all possible link keys for dropping duplicates
        - multiple processes: get link keys as is
        - one process: get serial columns as link keys
        """
        if not self.has_link_keys and not self.trans_data.serial_columns:
            return set()

        # multiple processes
        if self.has_link_keys:
            return {link.id for link in self.link_keys + self.next_link_keys}

        # one process
        return {col.id for col in self.trans_data.serial_columns}

    @cached_property
    def all_link_keys_labels(self) -> set[str]:
        """Get all link keys sql label"""
        return {cfg_col.gen_sql_label() for cfg_col in self.link_cfg_columns}

    @property
    def condition_procs_column_id(self) -> set[int]:
        """Get all filter condition columns"""
        cond_procs_column_id = set()
        for cond in self.condition_procs:
            cond_ids = cond.dic_col_id_filters.keys()
            cond_procs_column_id.update(cond_ids)
        return cond_procs_column_id

    @property
    def all_cfg_columns(self) -> list[CfgProcessColumn]:
        all_column_ids = self.all_link_key_ids | set(self.select_col_ids) | self.condition_procs_column_id
        return [c for c in CfgProcessColumn.get_by_ids(all_column_ids) if c.is_transaction_column]

    def gen_proc_time_label(self, is_start_proc: bool = False) -> str:
        return TIME_COL if is_start_proc else gen_proc_time_label(self.process_id)

    def filter_conditions(self, cte: sa.CTE) -> sa.Operators | None:
        """Filter master after we get cte from single process"""
        conditions = set()

        for cond_proc in self.condition_procs:
            assert cond_proc.proc_id == self.process_id
            for col_id, filters in cond_proc.dic_col_id_filters.items():
                cfg_column = self.trans_data.get_cfg_column_by_id(col_id)
                if not cfg_column or len(cfg_column.function_details):
                    continue

                col_name_alias = gen_alias_col_name(self.trans_data, cfg_column.bridge_column_name)
                col = cte.c.get(col_name_alias)
                assert col is not None, f'{col_name_alias} must exist'
                filter_col = col
                filter_col_type = cfg_column.data_type
                conditions.add(gen_sql_condition_per_col(filter_col, filter_col_type, filters))

        if not conditions:
            return None
        return sa.and_(*conditions)

    def apply_filter(self, cte: sa.CTE) -> sa.CTE:
        filter_conditions = self.filter_conditions(cte)
        if filter_conditions is None:
            return cte
        name_aliased = f'{FILTER_PREFIX}_{cte.description}'
        stmt = sa.select(cte).where(filter_conditions)
        return stmt.cte(name_aliased)

    @log_execution_time(SQL_GENERATOR_PREFIX)
    def gen_cte(
        self,
        idx: int,
        duplicated_serial_show: DuplicateSerialShow,
        is_start_proc: bool = False,
        for_count: bool = False,
    ):
        query_builder = TransactionDataQueryBuilder(self.trans_data)
        if is_start_proc:
            query_builder.add_column(column=self.trans_data.id_col_name)

        time_col = self.trans_data.getdate_column
        query_builder.add_column(column=time_col.bridge_column_name, label=self.gen_proc_time_label(is_start_proc))
        query_builder.between(start_tm=self.start_tm, end_tm=self.end_tm)
        query_builder_time_col = query_builder.column(self.gen_proc_time_label(is_start_proc))

        for cfg_col in self.all_cfg_columns:
            if cfg_col.existed_in_transaction_table():
                query_builder.add_column(column=cfg_col.bridge_column_name, label=cfg_col.gen_sql_label())

        link_cols = []
        for col_label in self.all_link_keys_labels:
            link_cols.append(query_builder.column(col_label))

        if not for_count and duplicated_serial_show != DuplicateSerialShow.SHOW_BOTH:
            distinct_cols = [col for col in link_cols if col.name != self.time_col]
            if distinct_cols:
                # sqlalchemy 2.1 support qualify, we can use them later
                # See: https://gitlab.com/dot-asterisk/biz-app/analysis-interface/analysisinterface/-/issues/132
                query_builder.qualify(
                    column=query_builder_time_col,
                    group_bys=distinct_cols,
                    func=sa.func.min if duplicated_serial_show == DuplicateSerialShow.SHOW_FIRST else sa.func.max,
                )

        cte = query_builder.build().cte(f'{CTE_PROCESS_PREFIX}{idx}')
        cte = self.apply_filter(cte)
        cte = self.gen_cached_epoch_cte(cte)

        return cte

    def gen_cached_epoch_cte(self, cte: sa.CTE) -> sa.CTE:
        epoch_cols = []
        for key in self.link_keys:
            if key.is_delta_time_cut_off_linked:
                column = cte.c.get(key.sql_label)
                if column is None:
                    raise ValueError(f'{key.name} must existed in CTE')
                epoch_col = convert_to_epoch(column)
                epoch_cols.append(epoch_col.label(key.epoch_sql_label))

        if not epoch_cols:
            return cte

        return sa.select(*epoch_cols, *cte.c).cte(f'{cte.description}_{EPOCH}').prefix_with('MATERIALIZED')


def cast_col_to_text(col: sa.ColumnClause, raw_data_type: str) -> Union[sa.ColumnClause, sa.ColumnOperators]:
    if RawDataTypeDB.is_text_data_type(raw_data_type):
        return col
    return sa.cast(col, sa.Text)


def force_take_substr(
    col: sa.ColumnClause,
    key: SqlProcLinkKey,
    raw_data_type: str,
) -> Union[sa.ColumnClause, sa.ColumnOperators]:
    try:
        substr_col = cast_col_to_text(col, raw_data_type)
        distance = key.substr_to - key.substr_from + 1
    except Exception:
        return col

    return sa.func.substr(substr_col, key.substr_from, distance)


def make_comparison_column_with_cast_and_substr(
    col1: sa.ColumnClause,
    key1: SqlProcLinkKey,
    type1: str,
    col2: sa.ColumnClause,
    key2: SqlProcLinkKey,
    type2: str,
) -> sa.ColumnOperators | bool | None:
    modified_col1 = col1 if key1.bad else force_take_substr(col1, key1, type1)
    modified_col2 = col2 if key2.bad else force_take_substr(col2, key2, type2)

    modified_type1 = type1 if key1.bad else RawDataTypeDB.TEXT.value
    modified_type2 = type2 if key2.bad else RawDataTypeDB.TEXT.value

    is_col1_text = RawDataTypeDB.is_text_data_type(modified_type1)
    is_col2_text = RawDataTypeDB.is_text_data_type(modified_type2)

    if (is_col1_text and is_col2_text) or (not is_col1_text and not is_col2_text):
        return modified_col1 == modified_col2

    modified_col1 = cast_col_to_text(modified_col1, modified_type1)
    modified_col2 = cast_col_to_text(modified_col2, modified_type2)
    return modified_col1 == modified_col2


def convert_to_epoch(col: sa.ColumnClause) -> sa.ColumnClause:
    # https://duckdb.org/docs/stable/sql/functions/timestamp#epochtimestamp
    return sa.func.epoch(sa.cast(col, sa.TIMESTAMP))


def make_comparisons_column_delta_time_and_cut_off(
    from_col: sa.ColumnClause,
    from_key: SqlProcLinkKey,
    to_col: sa.ColumnClause,
    to_key: SqlProcLinkKey,
):
    def _make_comparison(col: sa.ColumnClause, key: SqlProcLinkKey, other_col: sa.ColumnClause):
        cut_off = abs(key.cut_off if key.cut_off is not None else 0)
        return [
            other_col > col,
            other_col < col + key.delta_time * 60 + cut_off * 60,
            other_col > col + key.delta_time * 60 - cut_off * 60,
        ]

    if from_key.delta_time is not None:
        return _make_comparison(from_col, from_key, to_col)

    if to_key.delta_time is not None:
        return _make_comparison(to_col, to_key, from_col)

    return []


def make_comparisons_column(
    from_col: sa.ColumnClause,
    from_key: SqlProcLinkKey,
    from_data_type: str,
    to_col: sa.ColumnClause,
    to_key: SqlProcLinkKey,
    to_data_type: str,
):
    if from_key.is_delta_time_cut_off_linked or to_key.is_delta_time_cut_off_linked:
        # TODO: check data type
        comparisons = make_comparisons_column_delta_time_and_cut_off(
            from_col,
            from_key,
            to_col,
            to_key,
        )
        return comparisons
    else:
        comparison = make_comparison_column_with_cast_and_substr(
            from_col,
            from_key,
            from_data_type,
            to_col,
            to_key,
            to_data_type,
        )
        return [comparison]


def make_delta_time_diff(
    from_col: sa.ColumnClause,
    from_key: SqlProcLinkKey,
    to_col: sa.ColumnClause,
    to_key: SqlProcLinkKey,
):
    if from_key.delta_time is not None:
        return sa.func.abs(to_col - (from_col + from_key.delta_time * 60))

    if to_key.delta_time is not None:
        return sa.func.abs(from_col - (to_col + to_key.delta_time * 60))

    return None


@log_execution_time(SQL_GENERATOR_PREFIX)
def gen_tracing_cte(
    tracing_table_alias: str,
    cte_proc_list: list[sa.CTE],
    sql_objs: list[SqlProcLink],
    duplicated_serial_show: DuplicateSerialShow,
    dict_cond_procs: dict,
):
    start_proc_table = cte_proc_list[0] if cte_proc_list else None
    assert start_proc_table is not None
    stmt = sa.select(*cte_proc_list)

    join_conditions: sa.Join | None = None

    for i in range(1, len(sql_objs)):
        sql_obj = sql_objs[i]
        cte_proc = cte_proc_list[i]
        link_keys = sql_obj.link_keys

        prev_sql_obj = sql_objs[i - 1]
        prev_cte_proc = cte_proc_list[i - 1]
        prev_link_keys = prev_sql_obj.next_link_keys or prev_sql_obj.link_keys

        comparisons = []
        for from_key, to_key in zip(link_keys, prev_link_keys, strict=False):
            if from_key.is_delta_time_cut_off_linked:
                from_col = cte_proc.c.get(from_key.epoch_sql_label)
                to_col = prev_cte_proc.c.get(to_key.epoch_sql_label)
            else:
                from_col = cte_proc.c.get(from_key.sql_label)
                to_col = prev_cte_proc.c.get(to_key.sql_label)

            comparisons.extend(
                make_comparisons_column(
                    from_col,
                    from_key,
                    from_key.cfg_col.raw_data_type,
                    to_col,
                    to_key,
                    to_key.cfg_col.raw_data_type,
                ),
            )

        if duplicated_serial_show == duplicated_serial_show.SHOW_BOTH:
            from_col = cte_proc.c.get(gen_row_number_col_name(sql_obj.process_id))
            to_col = prev_cte_proc.c.get(gen_row_number_col_name(prev_sql_obj.process_id))
            if from_col is not None and to_col is not None:
                comparisons.append(from_col == to_col)

        join_conditions = join_table(
            join_conditions,
            left=prev_cte_proc,
            right=cte_proc,
            onclause=sa.and_(*comparisons),
            isouter=not is_has_condition(
                sql_obj.process_id,
                dict_cond_procs,
            ),  # TODO: this is complicated
        )

    if join_conditions is not None:
        stmt = stmt.select_from(join_conditions)
    return stmt.cte(tracing_table_alias)


def gen_conditions_per_column(filters):
    ands = []
    for cfg_filter in filters:
        comp_ins = []
        comp_likes = []
        comp_regexps = []
        cfg_filter_detail: CfgFilterDetail
        for cfg_filter_detail in cfg_filter.cfg_filter_details:
            val = cfg_filter_detail.filter_condition
            if cfg_filter_detail.filter_function == FilterFunc.REGEX.name:
                comp_regexps.append(val)
            elif not cfg_filter_detail.filter_function or cfg_filter_detail.filter_function == FilterFunc.MATCHES.name:
                comp_ins.append(val)
            else:
                comp_likes.extend(
                    gen_sql_like_value(
                        val,
                        FilterFunc[cfg_filter_detail.filter_function],
                        position=cfg_filter_detail.filter_from_pos,
                    ),
                )
        ands.append((comp_ins, comp_likes, comp_regexps))
    return ands


def gen_sql_condition_per_col(
    col: sa.ColumnClause,
    datatype: str,
    filters: list[ConditionProcDetail],
) -> sa.Operators:
    text_col = cast_col_to_text(col, datatype)

    and_conditions = gen_conditions_per_column(filters)
    ands = []
    for in_vals, like_vals, regex_vals in and_conditions:
        ors = []
        if in_vals:
            ors.append(col.in_(in_vals))
        if like_vals:
            ors.extend(text_col.like(like_val) for like_val in like_vals)
        if regex_vals:
            # Duckdb support regexp matches by default:
            # https://duckdb.org/docs/stable/sql/functions/regular_expressions#using-regexp_matches
            ors.extend(sa.func.regexp_matches(text_col, regex_val) for regex_val in regex_vals)
        if ors:
            ands.append(sa.or_(*ors))
    return sa.and_(*ands)


def gen_tracing_cte_with_delta_time_cut_off(cte_tracing: sa.CTE, sql_objs: list[SqlProcLink]) -> sa.CTE:
    timediff_cols = []
    for sql_obj, prev_sql_obj in zip(sql_objs[1:], sql_objs, strict=False):
        link_keys = sql_obj.link_keys
        prev_link_keys = prev_sql_obj.next_link_keys or prev_sql_obj.link_keys
        for from_key, to_key in zip(link_keys, prev_link_keys, strict=False):
            if from_key.is_delta_time_cut_off_linked or to_key.is_delta_time_cut_off_linked:
                from_col = cte_tracing.c.get(from_key.epoch_sql_label)
                to_col = cte_tracing.c.get(to_key.epoch_sql_label)
                timediff_cols.append(make_delta_time_diff(from_col, from_key, to_col, to_key))

    if not timediff_cols:
        return cte_tracing

    timediff_labels = [f'{TIMEDIFF_PREFIX}_{i}' for i in range(len(timediff_cols))]
    timediff_cols = [col.label(label) for col, label in zip(timediff_cols, timediff_labels, strict=False)]

    cte_tracing_timediff = sa.select(*cte_tracing.columns, *timediff_cols).cte(CTE_TRACING_TIMEDIFF)

    rank_by_timediff = (
        sa.func.rank()
        .over(
            partition_by=cte_tracing_timediff.c.get(TransactionData.id_col_name),
            order_by=[cte_tracing_timediff.c.get(col) for col in timediff_labels],
        )
        .label(RANK_BY_TIMEDIFF)
    )
    cte_tracing_rank = sa.select(*cte_tracing_timediff.columns, rank_by_timediff).cte(CTE_TRACING_RANK_BY_TIMEDIFF)

    cte_tracing_filtered_rank = (
        sa.select(*cte_tracing_rank.columns)
        .where(cte_tracing_rank.c.get(RANK_BY_TIMEDIFF) == 1)
        .cte(CTE_TRACING_MIN_TIMEDIFF)
    )

    return cte_tracing_filtered_rank


@log_execution_time(SQL_GENERATOR_PREFIX)
def gen_show_stmt(
    cte_tracing: sa.CTE,
    sql_objs: list[SqlProcLink],
) -> sa.Select:
    # we must add id and time to shown_cols
    shown_cols = [cte_tracing.c.get(TransactionData.id_col_name).label(TransactionData.id_col_name)]

    time_cols = []
    for idx, sql_obj in enumerate(sql_objs):
        is_start_proc = idx == 0
        # we get the time column
        time_col_alias_name = sql_obj.gen_proc_time_label(is_start_proc)
        time_col = cte_tracing.c.get(time_col_alias_name)
        # assert time_col is not None, "If time_col is None, sql_obj.get() function isn't written correctly"
        time_col_alias = time_col.label(time_col_alias_name)
        time_cols.append(time_col_alias)

        # TODO: do we need this?
        # we add our start proc as time_{id}
        if is_start_proc:
            time_col_alias_with_id = sql_obj.gen_proc_time_label(is_start_proc=False)
            time_col_alias = time_col.label(time_col_alias_with_id)
            time_cols.append(time_col_alias)

    shown_cols.extend(time_cols)
    for sql_obj in sql_objs:
        for cfg_col in sql_obj.all_cfg_columns:
            col = cte_tracing.c.get(cfg_col.gen_sql_label())

            shown_cols.append(col)

    order_bys = sorted(time_cols, key=lambda c: c.name)
    order_bys += ['rowid']  # MUST sort rowid column to make data order same with SQLite3
    return sa.select(*shown_cols).order_by(*order_bys)


def gen_id_stmt(cte_tracing: sa.CTE) -> sa.Select:
    col = cte_tracing.c.get(TransactionData.id_col_name)
    return sa.select(col)


def gen_sql_proc_link_count(trace: CfgTrace, limit: int | None = None) -> sa.Select:
    self_proc_link_keys: list[SqlProcLinkKey] = []
    target_proc_link_keys: list[SqlProcLinkKey] = []

    self_trans_data = TransactionData(trace.self_process_id)
    target_trans_data = TransactionData(trace.target_process_id)

    for trace_key in trace.trace_keys:
        is_delta_time_cut_off_linked = trace_key.delta_time is not None

        self_proc_link_keys.append(
            SqlProcLinkKey(
                id=trace_key.self_column_id,
                name=self_trans_data.get_column_name(trace_key.self_column_id),
                substr_from=trace_key.self_column_substr_from,
                substr_to=trace_key.self_column_substr_to,
                delta_time=trace_key.delta_time,
                cut_off=trace_key.cut_off,
                is_delta_time_cut_off_linked=is_delta_time_cut_off_linked,
            ),
        )
        target_proc_link_keys.append(
            SqlProcLinkKey(
                id=trace_key.target_column_id,
                name=target_trans_data.get_column_name(trace_key.target_column_id),
                substr_from=trace_key.target_column_substr_from,
                substr_to=trace_key.target_column_substr_to,
                # delta time and cut_off apply only self process link key, self_link_key + delta_time = target_link_key
                delta_time=None,
                cut_off=None,
                is_delta_time_cut_off_linked=is_delta_time_cut_off_linked,
            ),
        )
    self_query_builder = TransactionDataProcLinkQueryBuilder(
        self_trans_data,
        self_proc_link_keys,
        table_alias='self',
        limit=limit,
    )
    target_query_builder = TransactionDataProcLinkQueryBuilder(
        target_trans_data,
        target_proc_link_keys,
        table_alias='target',
        limit=limit,
    )
    return self_query_builder.build_count_query(target_query_builder)


def is_has_condition(proc_id, dict_cond_procs):
    if proc_id not in dict_cond_procs:
        return False

    return any(cond_proc.dic_col_id_filters for cond_proc in dict_cond_procs[proc_id])


QUALIFY_CONDITION_AGG_LABEL = '__QUALIFY_CONDITION_AGG'
QUALIFY_CONDITION_ROWID_LABEL = '__QUALIFY_CONDITION_ROWID'


@dataclass
class QualifyCondition:
    """
    This is support for show first, last, but sqlalchemy doesn't support qualify for duckdb (yet)
    https://duckdb.org/docs/stable/sql/query_syntax/qualify
    we can remove this after:
    https://gitlab.com/dot-asterisk/biz-app/analysis-interface/analysisinterface/-/issues/132
    """

    column: sa.Column
    group_bys: list[sa.Column]
    func: Any  # this is sa.func


class TransactionDataQueryBuilder:
    """Builder class for constructing SQL queries on transaction data.

    This class provides a fluent interface for building complex SQL queries
    on transaction data tables, including column selection, filtering, grouping,
    and ordering.

    Attributes:
        trans_model: TransactionData model instance.
        table: SQLAlchemy table model.
        selected_columns: List of columns to select in the query.
        join_conditions: Join conditions for the query.
        where_clauses: List of WHERE clause conditions.
        distinct_columns: Columns for DISTINCT/GROUP BY.
        orderby_columns: Columns for ORDER BY.
        having_columns: Columns for HAVING clause.
        joined_r_factory_machine: Flag indicating if factory machine table is joined.
        joined_r_prod_part: Flag indicating if product part table is joined.

    Methods:
        table_column: Get a column from the table by name.
        column: Get a selected column by label name.
        add_column: Add a column to the SELECT clause.
        distinct: Set columns for DISTINCT/GROUP BY.
        order_by: Set columns for ORDER BY.
        having: Set columns for HAVING clause.
        between: Add time range filter using start and end times.
        between_bound: Add time range filter with bound types.
        get_condition_from_filter_details: Generate conditions from filter details.
        add_conditions: Add filter conditions to WHERE clause.
        build: Build and return the final SQL SELECT statement.

    Generated by Duo.
    """

    def __init__(self, trans_model: TransactionData) -> None:
        self.trans_model = trans_model
        self.table = self.trans_model.table_model

        self.selected_columns: list[sa.Label] = []
        self.where_clauses = []

        self.orderby_columns = []

        self.qualify_condition: QualifyCondition | None = None

        self.joined_r_factory_machine = False
        self.joined_r_prod_part = False

    def table_column(self, name: str) -> sa.Column:
        column = self.table.c.get(name)
        if column is None:
            raise AssertionError(f'{column} does not existed in {self.table.name}')
        return column

    def column(self, name: str) -> sa.Label:
        for column in self.selected_columns:
            if column.name == name:
                return column
        raise RuntimeError(f"Column {name} doesn't exist.")

    def add_column(
        self,
        *,
        column: Union[sa.ColumnClause, str, sa.Label],
        label: str | None = None,
    ) -> None:
        if isinstance(column, str):
            # rowid of DuckDB is less 1 than SQLite3. Therefore, add 1 to the same
            # https://gitlab.com/dot-asterisk/biz-app/analysis-interface/analysisinterface/-/work_items/982
            if column == 'rowid':
                _column = self.table_column(column)
                column = (_column + 1).label(_column.name)
            else:
                column = self.table_column(column)
        if label is not None:
            column = column.label(label)
        self.selected_columns.append(column)

    def order_by(self, *, columns: list[sa.Column | sa.Label]) -> None:
        self.orderby_columns = columns

    def qualify(self, *, column: sa.Column, group_bys: list[sa.Column], func: Any):
        self.qualify_condition = QualifyCondition(column=column, group_bys=group_bys, func=func)

    def between(self, *, start_tm: str | None, end_tm: str | None) -> None:
        time_col = self.table_column(self.trans_model.getdate_column.bridge_column_name)

        conditions = []
        if start_tm is not None:
            conditions.append(time_col >= start_tm)
        if end_tm is not None:
            conditions.append(time_col < end_tm)

        if not conditions:
            return

        if len(conditions) == 1:
            self.where_clauses.append(conditions[0])
        else:
            self.where_clauses.append(sa.and_(*conditions))

    def between_bound(self, *, time_range: TimeRangeStr) -> None:
        """This is a new method that accept bound, we should have another MR that remove the use of `between`
        and only using this between_bound method
        """
        time_col = self.table_column(self.trans_model.getdate_column.bridge_column_name)

        conditions = []
        if time_range.min.kind is BoundType.INCLUDED:
            conditions.append(time_col >= time_range.min.value)
        elif time_range.min.kind is BoundType.EXCLUDED:
            conditions.append(time_col > time_range.min.value)

        if time_range.max.kind is BoundType.INCLUDED:
            conditions.append(time_col <= time_range.max.value)
        elif time_range.max.kind is BoundType.EXCLUDED:
            conditions.append(time_col < time_range.max.value)

        if len(conditions) == 1:
            self.where_clauses.append(conditions[0])
        elif len(conditions) > 1:
            self.where_clauses.append(sa.and_(*conditions))

    def get_condition_from_filter_details(self, filter_details: list[CfgFilterDetail]) -> list:
        """
        Get condition from a filter detail
        Args:
            filter_details: list[CfgFilterDetail], filter setting in column
            column_metadata: dict, include bridge column name and data-type
        """
        comp_regexps, comp_ins, comp_likes = [], [], []
        type_check = {
            FilterFunc.REGEX.name: comp_regexps,
            FilterFunc.MATCHES.name: comp_ins,
        }

        and_clauses = []
        for filter_detail in filter_details:
            # categorize condition type
            if filter_detail.filter_function in type_check:
                type_check[str(filter_detail.filter_function)].append(filter_detail.filter_condition)
            elif not filter_detail.filter_function:
                # what does `not filter_detail.filter_function` mean? need to refactor/define a meaning value
                # after that, push this into type_check instead of elif here
                comp_ins.append(filter_detail.filter_condition)
            else:
                comp_likes.extend(
                    gen_sql_like_value(
                        filter_detail.filter_condition,
                        FilterFunc[str(filter_detail.filter_function)],
                        position=filter_detail.filter_from_pos,
                    ),
                )

        # or_ filter for items in column setting
        or_clauses = []

        # All filters for a column are combined in filter_details,
        # so we use the first item to get the column metadata.
        filter_column = next(iter(filter_details), None)
        if not filter_column:
            return []

        column = self.table_column(filter_column.cfg_filter.column.bridge_column_name)
        data_type = filter_column.cfg_filter.column.data_type
        text_col = cast_col_to_text(column, data_type)

        # build condition logic
        if comp_ins:
            or_clauses.append(column.in_(comp_ins))
        if comp_likes:
            or_clauses.extend(text_col.like(like_val) for like_val in comp_likes)
        if comp_regexps:
            or_clauses.extend(text_col.regexp_match(regex_val) for regex_val in comp_regexps)
        and_clauses.append(sa.or_(*or_clauses))
        return and_clauses

    def add_conditions(self, filters: list[CfgFilterDetail]) -> None:
        """
        Add filter conditions for transaction data query
        Args:
            filters: list[CfgFilterDetail], filters detail will be applied in query
        """
        filter_columns = defaultdict(list)
        for _filter in filters:
            filter_columns[_filter.cfg_filter.column_id].append(_filter)

        conditions = set()
        for cols in filter_columns.values():
            ands = self.get_condition_from_filter_details(cols)
            conditions.add(sa.and_(*ands))
        self.where_clauses.append(sa.and_(*conditions))

    def build(self, limit: int | None = None) -> sa.Select:
        stmt = sa.select(*self.selected_columns)

        # this is our hack for `QUALIFY`.
        # See: https://gitlab.com/dot-asterisk/biz-app/analysis-interface/analysisinterface/-/issues/132
        if self.qualify_condition is not None:
            # what we do here?
            # - distinct using `qualify_condition.group_bys`
            # - select first (`func = sa.min`) or last (`func = sa.max`)
            # - use `rowid` as tie-breaker
            subquery = (
                sa.select(
                    *self.qualify_condition.group_bys,
                    self.qualify_condition.func(self.qualify_condition.column).label(QUALIFY_CONDITION_AGG_LABEL),
                    self.qualify_condition.func(sa.Column('rowid')).label(QUALIFY_CONDITION_ROWID_LABEL),
                )
                .group_by(*self.qualify_condition.group_bys)
                .where(*self.where_clauses)
                .subquery()
            )

            # select from the subquery above, use `rowid` as tie-breaker
            stmt = stmt.join(
                target=subquery,
                onclause=sa.and_(
                    self.qualify_condition.column == subquery.c[QUALIFY_CONDITION_AGG_LABEL],
                    sa.Column('rowid') == subquery.c[QUALIFY_CONDITION_ROWID_LABEL],
                ),
            )

        stmt = stmt.where(*self.where_clauses).order_by(*self.orderby_columns).limit(limit)
        del self
        return stmt


class TransactionDataProcLinkQueryBuilder:
    """Builder class for constructing process link count queries.

    This class builds SQL queries to count records that can be linked between
    two processes based on their link keys, supporting substring matching and
    delta time/cut-off criteria.

    Attributes:
        trans_model: TransactionData model instance.
        proc_link_keys: List of SqlProcLinkKey objects defining link criteria.
        table_alias: Alias name for the table in the query.
        limit: Maximum number of records to query.
        cte: Common Table Expression for the query.

    Methods:
        build_proc_link_cte: Build CTE for process link query.
        gen_cached_unixepoch_cte: Generate CTE with cached UNIXEPOCH columns.
        get_column_by_label: Get a column from CTE by its label.
        make_link_comparison: Create comparison conditions for linking with another process.
        build_count_query: Build a COUNT query for linked records between two processes.

    Generated by Duo.
    """

    def __init__(
        self,
        trans_model: TransactionData,
        proc_link_keys: list[SqlProcLinkKey],
        table_alias: str | None = None,
        limit: int | None = None,
    ) -> None:
        self.trans_model = trans_model
        self.proc_link_keys = proc_link_keys
        if table_alias is not None:
            self.table_alias = table_alias
        else:
            self.table_alias = uuid.uuid4().hex

        self.limit = limit
        self.cte: sa.CTE | None = None

    def build_proc_link_cte(self) -> Self:
        query_builder = TransactionDataQueryBuilder(self.trans_model)
        for key in self.proc_link_keys:
            query_builder.add_column(column=key.cfg_col.bridge_column_name, label=key.sql_label)
        stmt = query_builder.build(self.limit)
        self.cte = stmt.cte(self.table_alias)
        self.cte = self.gen_cached_epoch_cte()
        return self

    def gen_cached_epoch_cte(self) -> sa.CTE:
        epoch_cols = []
        for key in self.proc_link_keys:
            if key.is_delta_time_cut_off_linked:
                column = self.cte.c.get(key.sql_label)
                if column is None:
                    raise ValueError(f'{key.name} must existed in CTE')
                epoch_col = convert_to_epoch(column)
                epoch_cols.append(epoch_col.label(key.epoch_sql_label))

        if not epoch_cols:
            return self.cte

        return sa.select(*epoch_cols, *self.cte.c).cte(f'{self.table_alias}_{EPOCH}')

    def get_column_by_label(self, label: str) -> sa.ColumnClause | None:
        return self.cte.c.get(label)

    def make_link_comparison(self, other: Self) -> list[sa.ColumnOperators]:
        comparisons = []
        for key, other_key in zip(self.proc_link_keys, other.proc_link_keys, strict=False):
            if key.is_delta_time_cut_off_linked:
                column = self.get_column_by_label(key.epoch_sql_label)
                other_column = other.get_column_by_label(other_key.epoch_sql_label)
            else:
                column = self.get_column_by_label(key.sql_label)
                other_column = other.get_column_by_label(other_key.sql_label)

            comparisons.extend(
                make_comparisons_column(
                    column,
                    key,
                    key.cfg_col.raw_data_type,
                    other_column,
                    other_key,
                    other_key.cfg_col.raw_data_type,
                ),
            )

        return comparisons

    def build_count_query(self, other: Self) -> sa.Select:
        if self.cte is None:
            self.build_proc_link_cte()
        if other.cte is None:
            other.build_proc_link_cte()
        comparisons = self.make_link_comparison(other)
        exists_stmt = sa.exists(1).where(sa.and_(*comparisons))
        count_stmt = sa.select(sa.func.count()).select_from(self.cte)
        return count_stmt.where(exists_stmt)
