from typing import Union

from ap.common.pydn.dblib.db_proxy import DbProxy
from ap.setting_module.models import CfgDataSource, CfgDataSourceDB


class ReadOnlyDbProxy(DbProxy):
    """An interface for client to connect to many type of database"""

    def __init__(
        self,
        data_src: Union[CfgDataSource, CfgDataSourceDB, int],
        force_connect: bool = False,
        is_universal_db=False,
        proc_id=None,
    ) -> None:
        """cfg_data_source_db: CfgDataSourceDB object"""
        super().__init__(
            data_src,
            read_only=True,
            force_connect=force_connect,
            is_universal_db=is_universal_db,
            proc_id=proc_id,
        )

    def __exit__(self, exc_type, exc_val, exc_tb) -> bool:
        """
        Close the database connection when exiting the context manager.

        Args:
            exc_type: Exception type if raised inside the context; otherwise None.
            exc_val: Exception instance if raised inside the context; otherwise None.
            exc_tb: Traceback if an exception occurred; otherwise None.

        Returns:
            bool: Always False so that any exception inside the context is propagated.

        Generated by Junie
        """
        self.db_instance.disconnect()
        return False

    def _get_db_instance(self):
        return super()._get_db_instance()
