from __future__ import annotations

from datetime import datetime
from typing import Any, ClassVar, Union

from ap.common.common_utils import add_seconds, set_sqlite_params
from ap.common.constants import MSG_NOT_SUPPORT_DB, DBType
from ap.common.cryptography_utils import decrypt_pwd
from ap.common.custom_exception import DatabaseConnectionError
from ap.common.path_utils import gen_sqlite3_file_name
from ap.common.pydn.dblib import sqlite
from ap.common.pydn.dblib.mssqlserver import MSSQLServer
from ap.common.pydn.dblib.mysql import MySQL
from ap.common.pydn.dblib.oracle import Oracle
from ap.common.pydn.dblib.postgresql import PostgreSQL
from ap.common.pydn.dblib.snowflake import Snowflake
from ap.common.pydn.dblib.sqlite import SQLite3
from ap.setting_module.models import CfgDataSource, CfgDataSourceDB


class DbProxy:
    """An interface for client to connect to many type of database"""

    db_instance: Union[SQLite3, None, PostgreSQL, Oracle, MySQL, MSSQLServer, Snowflake]
    db_basic: CfgDataSource
    db_detail: CfgDataSourceDB
    dic_last_connect_failed_time: ClassVar[dict[int, datetime]] = {}

    def __init__(
        self,
        data_src,
        is_universal_db=False,
        force_connect=False,
        dic_db_files=None,
        proc_id=None,
        read_only: bool = False,
    ) -> None:
        """Initializes a DbProxy instance for database connection management.

        This constructor accepts multiple input types for data_src: a CfgDataSource
        object, a CfgDataSourceDB object, or a data source ID. It sets up the
        database configuration and connection parameters.

        Args:
            data_src: A CfgDataSource object, CfgDataSourceDB object, or data source ID.
            is_universal_db: Whether this is a universal database connection. Defaults to False.
            force_connect: Whether to force connection without checking failed connection history. Defaults to False.
            dic_db_files: Dictionary mapping process IDs to database file paths for attachment. Defaults to None.
            proc_id: The process ID associated with this proxy instance. Defaults to None.
            read_only: Whether the database connection should be read-only. Defaults to False.

        Generated by Duo
        """
        self.dic_db_files = dic_db_files
        self.proc_id = proc_id
        self.is_universal_db = is_universal_db
        self.force_connect = force_connect
        self.read_only = read_only
        if isinstance(data_src, CfgDataSource):
            self.db_basic = data_src
            self.db_detail = data_src.db_detail
        elif isinstance(data_src, CfgDataSourceDB):
            self.db_basic = data_src.cfg_data_source
            self.db_detail = data_src
        else:
            self.db_basic = CfgDataSource.query.get(data_src)
            self.db_detail = self.db_basic.db_detail

    def check_latest_failed_connection(self):
        if not self.db_basic.id:
            return
        last_failed_time = DbProxy.dic_last_connect_failed_time.get(self.db_basic.id)
        if last_failed_time is not None and last_failed_time > add_seconds(seconds=-180):
            raise DatabaseConnectionError(self.db_basic.name)

    def add_latest_failed_connection(self):
        if self.db_basic.id:
            DbProxy.dic_last_connect_failed_time[self.db_basic.id] = datetime.utcnow()

    def remove_latest_failed_connection(self):
        DbProxy.dic_last_connect_failed_time.pop(self.db_basic.id, None)

    def __enter__(self) -> Any:
        """Context manager entry point for establishing a database connection.

        Checks the connection history (unless force_connect is True), creates a
        database instance, establishes the connection, and attaches any additional
        databases if specified. Raises an exception if the connection fails.

        Returns:
            The database instance (SQLite3, PostgreSQL, Oracle, MySQL, MSSQLServer, or Snowflake).

        Raises:
            Exception: If the database connection fails.

        Generated by Duo
        """
        if not self.force_connect:
            self.check_latest_failed_connection()

        self.db_instance = self._get_db_instance()

        conn = self.db_instance.connect()
        if conn in (None, False):
            self.add_latest_failed_connection()
            raise DatabaseConnectionError(self.db_basic.name)

        # connect successfully, we need reset failed connection
        self.remove_latest_failed_connection()

        if self.is_universal_db:
            set_sqlite_params(conn)

        if self.dic_db_files:
            for proc_id, db_file in self.dic_db_files.items():
                if proc_id != self.proc_id:
                    self.db_instance.cursor.execute(f"ATTACH DATABASE '{db_file}' as {proc_id}")

        return self.db_instance

    def __exit__(self, _exc_type, _exc_val, _exc_tb) -> bool:
        """
        Handle context manager exit by committing or rolling back and disconnecting.

        Args:
            _exc_type: Exception type if an exception occurred within the context; otherwise None.
            _exc_val: Exception instance if an exception occurred within the context; otherwise None.
            _exc_tb: Traceback object if an exception occurred within the context; otherwise None.

        Returns:
            bool: Always False so that any exception is propagated to the caller.

        Notes:
            - For universal DB (SQLite), commit on success; rollback on error.
            - For other DBs, always rollback to avoid unintended writes in read contexts.

        Generated by Junie
        """
        try:
            if self.is_universal_db:
                if _exc_type:
                    self.db_instance.connection.rollback()
                else:
                    self.db_instance.connection.commit()
            else:
                self.db_instance.connection.rollback()
        except Exception as e:
            if self.db_instance.connection is not None:
                self.db_instance.connection.rollback()

            raise e
        finally:
            self.db_instance.disconnect()
        return False

    def _get_db_instance(self):
        db_type = self.db_basic.type.lower()
        if db_type == DBType.SQLITE.value.lower():
            return sqlite.SQLite3(self.db_detail.dbname, read_only=self.read_only)

        is_snowflake = db_type in [DBType.SNOWFLAKE.value.lower(), DBType.SNOWFLAKE_SOFTWARE_WORKSHOP.value.lower()]
        if db_type == DBType.POSTGRESQL.value.lower():
            target_db_class = PostgreSQL
        elif db_type == DBType.ORACLE.value.lower():
            target_db_class = Oracle
        elif db_type == DBType.MYSQL.value.lower():
            target_db_class = MySQL
        elif db_type == DBType.MSSQLSERVER.value.lower():
            target_db_class = MSSQLServer
        elif db_type == DBType.POSTGRES_SOFTWARE_WORKSHOP.value.lower():
            target_db_class = PostgreSQL
        elif is_snowflake:
            target_db_class = Snowflake
        else:
            raise Exception(MSG_NOT_SUPPORT_DB)

        password = self.db_detail.password
        if self.db_detail.hashed:
            password = decrypt_pwd(password)

        args = {'dbname': self.db_detail.dbname, 'read_only': self.read_only}
        if is_snowflake:
            if self.db_detail.hashed:
                snowflake_private_key_file_pwd = decrypt_pwd(self.db_detail.snowflake_private_key_file_pwd)
                snowflake_access_token = decrypt_pwd(self.db_detail.snowflake_access_token)
            else:
                snowflake_private_key_file_pwd = self.db_detail.snowflake_private_key_file_pwd
                snowflake_access_token = self.db_detail.snowflake_access_token

            # snowflake connector does not accept read only
            args.pop('read_only', None)
            args.update(
                {
                    'account': self.db_detail.host,
                    'user': self.db_detail.username,
                    'dbname': self.db_detail.dbname,
                    'warehouse': self.db_detail.snowflake_warehouse,
                    'role': self.db_detail.snowflake_role,
                    'authentication_type': self.db_detail.snowflake_authentication_type,
                    'access_token': snowflake_access_token,
                    'private_key_file': self.db_detail.snowflake_private_key_file,
                    'private_key_file_pwd': snowflake_private_key_file_pwd,
                    'port': self.db_detail.port,
                    'schema': self.db_detail.schema,
                }
            )
        elif self.db_basic.type == DBType.ORACLE.name:
            args.update(
                {
                    'host': self.db_detail.host,
                    'username': self.db_detail.username,
                    'password': password,
                    'port': self.db_detail.port,
                    'schema': self.db_detail.schema,
                },
            )
        elif self.db_basic.type != DBType.SQLITE.name:
            args.update(
                {
                    'host': self.db_detail.host,
                    'username': self.db_detail.username,
                    'password': password,
                    'port': self.db_detail.port,
                },
            )

        db_instance = target_db_class(**args)

        # use custom port or default port
        if self.db_detail.port:
            db_instance.port = int(self.db_detail.port)
        # FIXME: cast port to integer, this is a really bad operation ... we should save integer in db instead
        if db_instance.port is not None:
            db_instance.port = int(db_instance.port)

        if self.db_detail.schema:
            db_instance.schema = self.db_detail.schema

        return db_instance

    @classmethod
    def check_db_connection(cls, data_src, force: bool = False):
        with cls(data_src, force_connect=force) as db_instance:
            if not db_instance.is_connected:
                raise DatabaseConnectionError(data_src.name)


def gen_data_source_of_universal_db(proc_id=None):
    """
    Create data source cfg object that point to our application universal db
    :return:
    """
    db_src = CfgDataSource()
    db_detail = CfgDataSourceDB()

    db_src.type = DBType.SQLITE.name
    db_src.db_detail = db_detail

    db_detail.dbname = gen_sqlite3_file_name(proc_id)

    return db_src


def gen_data_source_software_workshop(
    host: str | None = None,
    port: int | None = None,
    dbname: str | None = None,
    schema: str | None = None,
    username: str | None = None,
    password: str | None = None,
    db_type: str | None = None,
):
    db_src = CfgDataSource()
    db_detail = CfgDataSourceDB(
        host=host,
        port=port,
        dbname=dbname,
        schema=schema,
        username=username,
        password=password,
    )

    db_src.type = db_type
    db_src.db_detail = db_detail
    return db_src
