#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Author: Masato Yasuda (2018/01/04)

import logging

import pymysql.cursors
from pymysql.cursors import SSCursor

from ap.common.common_utils import strip_all_quote

logger = logging.getLogger(__name__)


class MySQL:
    """MySQL database connection and operations handler.

    Provides methods for connecting to and interacting with MySQL databases,
    including table management, query execution, and schema operations.

    Attributes:
        host: Database server hostname or IP address.
        port: Database server port number (default 3306).
        dbname: Name of the database to connect to (equivalent to schema in MySQL).
        username: Database user for authentication.
        password: Password for database authentication.
        is_connected: Connection status flag.
        connection: Active database connection object.
        read_only: If True, restricts to read-only operations.

    Methods:
        connect: Establishes connection to the database.
        disconnect: Closes the database connection.
        run_sql: Executes SQL query and returns results.
        fetch_many: Executes query and yields results in batches.
        list_tables: Returns list of table names.
        list_tables_and_views: Returns list of tables and views.
        list_table_columns: Returns column information for a table.
        get_timezone: Retrieves database timezone offset.
        execute_sql: Executes SQL statement with commit.

    Generated by Duo.
    """

    def __init__(self, host, dbname, username, password, port=3306, read_only=False) -> None:
        self.host = host
        self.port = port
        self.dbname = dbname
        # postgresqlと違い、mysqlにはdbとschemaは同義
        # postgresqlはdbの下にschemaという概念がある。
        # http://d.hatena.ne.jp/sheeg/20070906/1189083744
        self.username = username
        self.password = password
        self.is_connected = False
        self.connection = None
        self.read_only = read_only

    def dump(self):
        logger.info(
            f"""\
===== DUMP RESULT =====
DB Type: MySQL
self.host: {self.host}
self.port: {self.port}
self.dbname: {self.dbname}
self.username: {self.username}
self.is_connected: {self.is_connected}
=======================
""",
        )

    def connect(self):
        try:
            self.connection = pymysql.connect(
                host=self.host,
                user=self.username,
                password=self.password,
                db=self.dbname,
                port=self.port,
                charset='utf8',
            )  # ,
            # cursorclass=pymysql.cursors.DictCursor)
            self.is_connected = True
            return self.connection
        except Exception as e:
            logger.exception(e)
            return False

    def disconnect(self):
        if not self._check_connection():
            return False
        self.connection.close()
        self.is_connected = False
        return True

    def create_table(self, tblname, valtypes):
        if not self._check_connection():
            return False

        tblname = tblname.strip('"')
        sql = f'create table {tblname:s}('
        for idx, val in enumerate(valtypes):
            if idx > 0:
                sql += ','

            sql += val['name'] + ' ' + val['type']
        sql += ')'
        logger.info(sql)
        cur = self.connection.cursor()
        cur.execute(sql)
        cur.close()
        self.connection.commit()
        logger.info(f'{tblname} created!')
        return True

    # 作成済みのテーブルを配列として返す
    def list_tables(self):
        if not self._check_connection():
            return []

        sql = 'show tables'
        cur = self.connection.cursor()
        cur.execute(sql)
        results = []
        for row in cur.fetchall():
            results.append(row[0])
        return results

    def list_tables_and_views(self):
        if not self._check_connection():
            return False
        # Only list tables of default schema (default schema name can be got by "SCHEMA_NAME()")
        sql = 'select table_name from information_schema.tables '
        sql += f"where table_schema = '{self.dbname:s}'"
        cur = self.connection.cursor()
        cur.execute(sql)
        results = []
        rows = cur.fetchall()
        for row in rows:
            results.append(row[0])
        cur.close()
        return results

    def drop_table(self, tblname):
        if not self._check_connection():
            return False

        sql = 'drop table if exists ' + tblname
        sql = sql.replace('"', '`')
        cur = self.connection.cursor()
        cur.execute(sql)
        cur.close()
        self.connection.commit()
        logger.info(f'{tblname} dropped!')
        return True

    # テーブルのカラムのタイプを辞書の配列として返す
    # columns:
    #  name => カラム名,
    #  type => カラムタイプ
    def list_table_columns(self, tblname):
        if not self._check_connection():
            return False
        sql = 'show columns from ' + tblname
        sql = sql.replace('"', '`')
        cur = self.connection.cursor()
        cur.execute(sql)
        rows = cur.fetchall()
        results = []
        for row in rows:
            results.append({'name': row[0], 'type': row[1]})
        return results

    def get_data_type_by_colname(self, tbl, col_name):
        col_name = strip_all_quote(col_name)
        cols = self.list_table_columns(tbl)
        data_type = [col['type'] for col in cols if col['name'] == col_name]
        return data_type[0] if data_type else None

    # list_table_columnsのうちcolumn nameだけ必要な場合
    # def list_table_colnames(self, tblname):
    #     if not self._check_connection():
    #         return False
    #     columns = self.list_table_columns(tblname)
    #     colnames = []
    #     for column in columns:
    #         colnames.append(column['name'])
    #     return colnames

    def insert_table_records(self, tblname, names, values, add_comma_to_value=True):
        if not self._check_connection():
            return False

        sql = f'insert into {tblname:s}'

        # Generate column names field
        sql += '('
        for idx, name in enumerate(names):
            if idx > 0:
                sql += ','
            sql += name
        sql += ') '

        # Generate values field
        sql += 'values '
        for idx1, value in enumerate(values):
            if idx1 > 0:
                sql += ','
            sql += '('
            for idx2, name in enumerate(names):
                if idx2 > 0:
                    sql += ','

                if value[name] in ('', None):
                    sql += 'Null'
                elif add_comma_to_value:
                    sql += "'" + str(value[name]) + "'"
                else:
                    sql += str(value[name])

            sql += ')'

        sql = sql.replace('"', '`')
        cur = self.connection.cursor()
        cur.execute(sql)
        cur.close()
        self.connection.commit()
        logger.info(f'Dummy data was inserted to {tblname}!')
        return True

    # SQLをそのまま実行。
    # cols, rows = db1.run_sql("select * from tbl01")
    # という形で呼び出す
    def run_sql(self, sql, row_is_dict=True):
        if not self._check_connection():
            return False
        cur = self.connection.cursor()
        sql = sql.replace('"', '`')
        cur.execute(sql)
        # cursor.descriptionはcolumnの配列
        # そこから配列名(column[0])を取り出して配列columnsに代入
        cols = [column[0] for column in cur.description]
        # columnsは取得したカラム名、rowはcolumnsをKeyとして持つ辞書型の配列
        # rowは取得したカラムに対応する値が順番にrow[0], row[1], ...として入っている
        # それをdictでまとめてrowsに取得
        rows = [dict(zip(cols, row, strict=False)) for row in cur.fetchall()] if row_is_dict else cur.fetchall()

        cur.close()
        return cols, rows

    def fetch_many(self, sql, size=10_000, params=None):
        if not self._check_connection():
            return False

        # use SSCursor for optimize with large data
        # https://pymysql.readthedocs.io/en/latest/modules/cursors.html#pymysql.cursors.SSCursor
        cur = self.connection.cursor(SSCursor)

        sql = sql.replace('"', '`')
        cur.execute(sql, params)
        cols = [column[0] for column in cur.description]
        yield cols
        while True:
            rows = cur.fetchmany(size)
            if not rows:
                break

            yield rows

        cur.close()
        return True

    def get_timezone(self):
        try:
            # rows = self.run_sql('''SELECT @@global.time_zone as server_tz, @@session.time_zone as session_tz''')
            _, rows = self.run_sql('SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP) TZOFFSET')
            tz_offset = str(rows[0]['TZOFFSET'])
            return tz_offset

        except Exception as e:
            logger.exception(e)

        return None

    def execute_sql(self, sql):
        """For executing any query requires commit action
        :param sql: SQL to be executed
        :return: Execution result
        """
        if not self._check_connection():
            return False

        cur = self.connection.cursor()
        sql = sql.replace('"', '`')
        logger.info(sql)
        res = cur.execute(sql)
        cur.close()
        self.connection.commit()

        return res

    # private functions

    def _check_connection(self):
        if self.is_connected:
            return True
        # 接続していないなら
        logger.warning('Connection is not Initialized. Please run connect() to connect to DB')
        return False

    def is_timezone_hold_column(self, _tbl, _col):
        # data_type = self.get_data_type_by_colname(tbl, col)
        # return True if data_type in [] else False
        return False
