#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Author: Masato Yasuda (2018/01/04)


from typing import Union

import psycopg2
import psycopg2.extras
import sqlalchemy as sa
from loguru import logger
from sqlalchemy.dialects import postgresql

from ap.common.common_utils import convert_sa_sql_to_sa_str, handle_read_only, strip_all_quote
from ap.common.log import log_execution_time

# See this for more, https://www.psycopg.org/docs/usage.html#server-side-cursors
# This avoid out of memory when running query without limit
# PSYCOPG2_SERVER_SIZE_CURSOR_ITERSIZE = 2000


class PostgreSQL:
    """PostgreSQL database connection and operations handler.

    Provides methods for connecting to and interacting with PostgreSQL databases,
    including table management, query execution, and schema operations.

    Attributes:
        host: Database server hostname or IP address.
        port: Database server port number (default 5432).
        dbname: Name of the database to connect to.
        schema: Schema name within the database (auto-detected if not specified).
        username: Database user for authentication.
        password: Password for database authentication.
        is_connected: Connection status flag.
        connection: Active database connection object.
        read_only: If True, restricts to read-only operations.

    Methods:
        connect: Establishes connection to the database.
        disconnect: Closes the database connection.
        run_sql: Executes SQL query and returns results.
        fetch_many: Executes query and yields results in batches.
        list_tables: Returns list of table names.
        list_tables_and_views: Returns list of tables and views.
        list_table_columns: Returns column information for a table.
        get_timezone: Retrieves database timezone information.
        execute_sql: Executes SQL statement with commit.
        gen_sql_and_params: Generates SQL string and parameters from SQLAlchemy statement.

    Generated by Duo.
    """

    def __init__(self, host, dbname, username, password, port=5432, read_only=False) -> None:
        self.host = host
        self.port = port
        self.dbname = dbname
        # postgresqlはdbの下にschemaという概念がある。
        # http://d.hatena.ne.jp/sheeg/20070906/1189083744
        self.schema = None
        self.username = username
        self.password = password
        self.is_connected = False
        self.connection = None
        self.read_only = read_only

    def dump(self):
        logger.info(
            f"""\
===== DUMP RESULT =====
DB Type: PostgreSQL
self.host: {self.host}
self.port: {self.port}
self.dbname: {self.dbname}
self.username: {self.username}
self.is_connected: {self.is_connected}
======================='
""",
        )

    def connect(self):
        dsn = f'host={self.host:s} '
        dsn += f'port={int(self.port):d} '
        dsn += f'dbname={self.dbname:s} '
        dsn += f'user={self.username:s} '
        dsn += f'password={self.password:s}'
        try:
            self.connection = psycopg2.connect(dsn)
            cur = self.connection.cursor()
            self.is_connected = True

            if self.schema:
                cur.execute(
                    f"SELECT schema_name FROM information_schema.schemata WHERE schema_name = '{self.schema}';",
                )
                if cur.rowcount:
                    cur.execute(f'SET search_path TO {self.schema:s}')
                else:
                    logger.warning('Schema is not exists!!!')
                    self.disconnect()
            else:
                # Get current schema
                cur.execute('SELECT current_schema();')
                default_schema = cur.fetchone()
                # Save default schema as constant, use to list current schema's tables
                self.schema = default_schema[0]
            cur.close()
            return self.connection
        except Exception as e:
            logger.exception(e)
            return False

    def disconnect(self):
        if not self._check_connection():
            return False
        # https://stackoverflow.com/questions/1281875/
        # making-sure-that-psycopg2-database-connection-alive
        self.connection.close()
        self.is_connected = False

    def create_table(self, tblname, colnames):
        if not self._check_connection():
            return False
        sql = f'create table {tblname:s}('
        for idx, val in enumerate(colnames):
            if idx > 0:
                sql += ','
            sql += val['name'] + ' ' + val['type']
        sql += ')'
        logger.info(sql)
        cur = self.connection.cursor()
        cur.execute(sql)
        cur.close()
        self.connection.commit()
        logger.info(f'{tblname} created!')

    # テーブル名を配列として返す
    def list_tables(self):
        if not self._check_connection():
            return []
        sql = 'select table_name from information_schema.tables '
        sql += f"where table_type = 'BASE TABLE' and table_schema = '{self.schema:s}'"
        cur = self.connection.cursor()
        cur.execute(sql)
        # cursor.descriptionはcolumnの配列
        # そこから配列名(column[0])を取り出して配列columnsに代入
        cols = [column[0] for column in cur.description]
        # columnsは取得したカラム名、rowはcolumnsをKeyとして持つ辞書型の配列
        # rowは取得したカラムに対応する値が順番にrow[0], row[1], ...として入っている
        # それをdictでまとめてrowsに取得
        rows = []
        for row in cur.fetchall():
            rows.append(dict(zip(cols, row, strict=False)))
        cur.close()
        # キーに"table_name"を持つ要素を配列として返す
        return [row['table_name'] for row in rows]

    def list_tables_and_views(self):
        if not self._check_connection():
            return False
        sql = 'select table_name from information_schema.tables '
        sql += f"where table_schema = '{self.schema:s}'"
        cur = self.connection.cursor()
        cur.execute(sql)
        # cursor.descriptionはcolumnの配列
        # そこから配列名(column[0])を取り出して配列columnsに代入
        cols = [column[0] for column in cur.description]
        # columnsは取得したカラム名、rowはcolumnsをKeyとして持つ辞書型の配列
        # rowは取得したカラムに対応する値が順番にrow[0], row[1], ...として入っている
        # それをdictでまとめてrowsに取得
        rows = []
        for row in cur.fetchall():
            rows.append(dict(zip(cols, row, strict=False)))
        cur.close()
        # キーに"table_name"を持つ要素を配列として返す
        return [row['table_name'] for row in rows]

    def drop_table(self, tblname):
        if not self._check_connection():
            return False
        sql = 'drop table if exists ' + tblname
        cur = self.connection.cursor()
        cur.execute(sql)
        cur.close()
        self.connection.commit()
        logger.info(f'{tblname} dropped!')

    # テーブルのカラムのタイプを辞書の配列として返す
    # columns:
    #  name => カラム名,
    #  type => カラムタイプ
    def list_table_columns(self, tblname):
        if not self._check_connection():
            return False

        sql = 'select * from information_schema.columns '
        sql += f"where table_schema = '{self.schema}' and table_name = '{tblname}'"
        cur = self.connection.cursor()
        cur.execute(sql)
        # cursor.descriptionはcolumnの配列
        # そこから配列名(column[0])を取り出して配列columnsに代入
        cols = [column[0] for column in cur.description]
        # columnsは取得したカラム名、rowはcolumnsをKeyとして持つ辞書型の配列
        # rowは取得したカラムに対応する値が順番にrow[0], row[1], ...として入っている
        # それをdictでまとめてrowsに取得
        rows = []
        for row in cur.fetchall():
            rows.append(dict(zip(cols, row, strict=False)))
        cur.close()
        results = []

        for row in rows:
            results.append({'name': row['column_name'], 'type': row['data_type']})
        return results

    def get_data_type_by_colname(self, tbl, col_name):
        col_name = strip_all_quote(col_name)
        cols = self.list_table_columns(tbl)
        data_type = [col['type'] for col in cols if col['name'] == col_name]
        return data_type[0] if data_type else None

    # list_table_columnsのうちcolumn nameだけ必要な場合
    # def list_table_colnames(self, tblname):
    #     if not self._check_connection():
    #         return False
    #     columns = self.list_table_columns(tblname)
    #     colnames = []
    #     for column in columns:
    #         colnames.append(column['name'])
    #     return colnames

    # 元はinsert_table関数
    def insert_table_records(self, tblname, names, values, add_comma_to_value=True):
        if not self._check_connection():
            return False

        sql = f'insert into {tblname:s}'

        # Generate column names fields
        sql += '('
        for idx, name in enumerate(names):
            if idx > 0:
                sql += ','
            sql += name
        sql += ') '

        # Generate values field
        if not values:
            return False

        sql += 'values '
        for idx1, value in enumerate(values):
            if idx1 > 0:
                sql += ','
            sql += '('
            for idx2, name in enumerate(names):
                if idx2 > 0:
                    sql += ','

                if value[name] in ('', None):
                    sql += 'Null'
                elif add_comma_to_value:
                    sql += "'" + str(value[name]) + "'"
                else:
                    sql += str(value[name])

            sql += ')'

        cur = self.connection.cursor()
        cur.execute(sql)
        cur.close()
        self.connection.commit()

        logger.info(f'Dummy data was inserted to {tblname}!')

    # SQLをそのまま実行
    # colsとdict形式のrowsを返す
    # cols, rows = db1.run_sql("select * from tbl01")
    # という形で呼び出す
    @log_execution_time('POSTGRES')
    @convert_sa_sql_to_sa_str
    @handle_read_only()
    def run_sql(self, sql: str, row_is_dict=True, params=None):
        if not self._check_connection():
            return False
        cur = self.connection.cursor()
        # https://stackoverflow.com/questions/10252247/
        # how-do-i-get-a-list-of-column-names-from-a-psycopg2-cursor
        # カラム名がRenameされた場合も対応出来る形に処理を変更
        logger.info(sql)
        cur.execute(sql, params)
        # cursor.descriptionはcolumnの配列
        # そこから配列名(column[0])を取り出して配列columnsに代入
        cols = [column[0] for column in cur.description]
        # columnsは取得したカラム名、rowはcolumnsをKeyとして持つ辞書型の配列
        # rowは取得したカラムに対応する値が順番にrow[0], row[1], ...として入っている
        # それをdictでまとめてrowsに取得
        rows = [dict(zip(cols, row, strict=False)) for row in cur.fetchall()] if row_is_dict else cur.fetchall()

        cur.close()
        return cols, rows

    @convert_sa_sql_to_sa_str
    @handle_read_only()
    def fetch_many(self, sql, size=10_000, params=None):
        if not self._check_connection():
            return False

        cur = self.connection.cursor()

        cur.execute(sql, params)

        cols = [column[0] for column in cur.description]
        yield cols
        while True:
            rows = cur.fetchmany(size)
            if not rows:
                break

            yield rows

        cur.close()

    def execute_sql(self, sql):
        """For executing any query requires commit action
        :param sql: SQL to be executed
        :return: Execution result
        """
        if not self._check_connection():
            return False

        cur = self.connection.cursor()
        res = cur.execute(sql)
        cur.close()
        self.connection.commit()

        return res

    # 現時点ではSQLをそのまま実行するだけ
    def get_timezone(self):
        try:
            _, rows = self.run_sql('show timezone')
            tz_offset = str(rows[0]['TimeZone'])
            return tz_offset
        except Exception as e:
            logger.exception(e)
            return None

    # private functions

    def _check_connection(self):
        if self.is_connected:
            return True
        # 接続していないなら
        logger.warning('Connection is not Initialized. Please run connect() to connect to DB')
        return False

    def is_timezone_hold_column(self, tbl, col):
        data_type = self.get_data_type_by_colname(tbl, col)

        return 'WITH TIME ZONE' in data_type.upper()

    @staticmethod
    def gen_sql_and_params(stmt: Union[sa.Select, sa.TextClause]) -> tuple[str, dict[str, str]]:
        compiled_stmt = stmt.compile(dialect=postgresql.dialect(), compile_kwargs={'render_postcompile': True})
        return compiled_stmt.string, compiled_stmt.params
