import logging
from abc import ABCMeta, abstractmethod

from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)


class SessionMeta(ABCMeta):
    """Abstract base metaclass for session metadata management.

    Defines the interface for managing metadata throughout the SQLAlchemy
    session lifecycle.

    Methods:
        begin: Initializes metadata when a session transaction begins.
        update: Updates metadata during session flush or before commit.
        close: Cleans up metadata when a transaction ends.
        commit: Processes metadata changes on transaction commit.

    Generated by Duo.
    """

    @classmethod
    @abstractmethod
    def begin(cls, session: Session):
        """Init metadata on current session variable.

        :param Session session: SQLAlchemy session
        :return: Void
        """

    @classmethod
    @abstractmethod
    def update(cls, session: Session):
        """Update metadata on current session variable.

        :param Session session: SQLAlchemy session
        :return: Void
        """

    @classmethod
    @abstractmethod
    def close(cls, session: Session):
        """Close metadata on current session variable

        :param Session session: SQLAlchemy session
        :return: Void
        """

    @classmethod
    @abstractmethod
    def commit(cls, session: Session):
        """Commit metadata on current session variable

        :param Session session: SQLAlchemy session
        :return: Void
        """
