from __future__ import annotations

import contextlib
import logging
import re
from abc import abstractmethod
from collections.abc import Mapping
from itertools import pairwise
from typing import Any, ClassVar, override

import numpy as np
import pandas as pd
import pydantic
from dateutil import tz
from pydantic import BaseModel, ConfigDict
from pydantic.functional_validators import field_validator

from ap.common.constants import (
    DOUBLE_COLON_CONNECTOR,
    EMPTY_STRING,
    MULTIPLE_VALUES_CONNECTOR,
    DataTypeEncode,
    RawDataTypeDB,
)
from ap.common.memoize import CustomCache
from ap.equations.error import INVALID_VALUE_MSG, MUST_HAVE_THE_SAME_TYPE_MSG, ErrorField, FunctionFieldError
from ap.setting_module.models import MFunction

logger = logging.getLogger(__name__)

BOOLEAN_DICT_VALUES = {
    'true': True,
    'True': True,
    '1': True,
    'false': False,
    'False': False,
    '0': False,
}

FUNCTION_DATE_FORMAT = '%Y-%m-%d'
FUNCTION_TIME_FORMAT = '%H:%M:%S.%f'


class FunctionInfo(BaseModel):
    """Metadata model for mathematical and transformation functions.

    Stores configuration and metadata for functions used in data transformations.

    Attributes:
        id: Unique identifier for the function.
        function_type: Type/category of the function.
        function_name_en: English name of the function.
        function_name_jp: Japanese name of the function.
        description_en: English description of the function.
        description_jp: Japanese description of the function.
        x_types: List of allowed data types for X variable.
        y_types: List of allowed data types for Y variable.
        vars: List of variable names used by the function.
        coefs: List of all coefficient names.
        required_coefs: List of required coefficient names.
        optional_coefs: List of optional coefficient names.
        show_serial: Flag indicating if serial number should be shown.
        a, b, c: Numeric coefficient parameters.
        n, k: Integer coefficient parameters.
        s, t: String coefficient parameters.

    Generated by Duo.
    """

    id: int
    function_type: str
    function_name_en: str | None = None
    function_name_jp: str | None = None
    description_en: str | None = None
    description_jp: str | None = None
    x_types: list[RawDataTypeDB]
    y_types: list[RawDataTypeDB]
    vars: list[str]
    coefs: list[str]
    required_coefs: list[str]
    optional_coefs: list[str]
    show_serial: bool
    a: str | None = None
    b: str | None = None
    c: str | None = None
    n: str | None = None
    k: str | None = None
    s: str | None = None
    t: str | None = None
    model_config = ConfigDict(use_enum_values=True)


def cast_value_based_on_series(series: pd.Series, value: Any) -> tuple[Any, bool]:
    """
    @param series:
    @param value:
    @return: cast value (if possible) and boolean result indicated that it is cast to series or not
    """
    if pd.api.types.is_bool_dtype(series) and value in BOOLEAN_DICT_VALUES:
        return BOOLEAN_DICT_VALUES[value], True

    if pd.api.types.is_float_dtype(series):
        with contextlib.suppress(ValueError):
            return float(value), True

    if pd.api.types.is_integer_dtype(series):
        with contextlib.suppress(ValueError):
            return int(value), True

    if pd.api.types.is_string_dtype(series):
        with contextlib.suppress(ValueError):
            return str(value), True

    # fallback to the smallest type possible
    for typ in [int, float, str]:
        with contextlib.suppress(ValueError):
            return typ(value), False

    # keep the original type
    return value, False


def try_cast_series_pd_types(series: pd.Series, pd_types: list[pd.ExtensionType]) -> pd.Series | None:
    for dtype in pd_types:
        if series.dtype == dtype:
            return series

        result_series = series

        current_type_is_not_boolean = not pd.api.types.is_bool_dtype(result_series)
        type_should_be_boolean = pd.api.types.is_bool_dtype(dtype)
        if current_type_is_not_boolean and type_should_be_boolean:
            result_series = result_series.astype(object).replace(BOOLEAN_DICT_VALUES)

        # pandas 2.0 does not allow to astype datetime data from tz-naive to tz-aware
        if pd.api.types.is_datetime64_any_dtype(dtype):
            with contextlib.suppress(TypeError, ValueError, OverflowError):
                dtype_timezone = getattr(dtype, 'tz', None)
                return pd.to_datetime(result_series).dt.tz_localize(tz=dtype_timezone)

        if pd.api.types.is_numeric_dtype(dtype):
            with contextlib.suppress(TypeError, ValueError, OverflowError):
                return pd.to_numeric(result_series, errors='coerce').convert_dtypes().astype(dtype)

        with contextlib.suppress(TypeError, ValueError, OverflowError):
            return result_series.astype(dtype)
        with contextlib.suppress(TypeError, ValueError, OverflowError):
            return result_series.astype(pd.StringDtype()).astype(dtype)
        with contextlib.suppress(TypeError, ValueError, OverflowError):
            return result_series.convert_dtypes().astype(dtype)
        with contextlib.suppress(TypeError, ValueError, OverflowError):
            return result_series.astype(object).astype(dtype)
    return None


def try_cast_series(series: pd.Series, raw_data_types: list[RawDataTypeDB | None]) -> pd.Series:
    # TODO: write extension type later
    if pd.api.types.is_object_dtype(series) and RawDataTypeDB.TIME in raw_data_types:
        return pd.to_datetime(series.astype(pd.StringDtype()))

    # cast all possible data types
    pd_types = [
        RawDataTypeDB.get_pandas_dtype(raw_dtype.value) for raw_dtype in raw_data_types if raw_dtype is not None
    ]
    casted_series = try_cast_series_pd_types(series, pd_types)
    if casted_series is None:
        # maybe series is full of empty text, we will replace EMPTY_STRING by None then cast it again
        casted_series = try_cast_series_pd_types(series.replace(EMPTY_STRING, pd.NA), pd_types)

    if casted_series is None and RawDataTypeDB.BOOLEAN in raw_data_types:
        # in case of raw dtype is BOOLEAN but was casted into Int32
        casted_series = try_cast_series_pd_types(series.replace(BOOLEAN_DICT_VALUES), pd_types)

    if casted_series is None:
        raise FunctionFieldError('Cast error').add_error(
            ErrorField(field=None, msg=f'Cannot cast series of type `{series.dtype}` to `{raw_data_types}`'),
        )

    return casted_series


def get_data_encoding_type_from_series(series: pd.Series) -> DataTypeEncode:
    if pd.api.types.is_integer_dtype(series):
        return DataTypeEncode.INTEGER
    if pd.api.types.is_float_dtype(series):
        return DataTypeEncode.REAL
    if pd.api.types.is_string_dtype(series):
        return DataTypeEncode.TEXT
    return DataTypeEncode.NULL


class BaseFunction(BaseModel):
    """Abstract base class for all mathematical and transformation functions.

    Provides common functionality for evaluating functions on pandas Series,
    including type casting, validation, and coefficient management.

    Attributes:
        EXCLUDE_VARS: Class variable listing fields to exclude from coefficient lists.
        type_cast: Optional type casting specification for output.

    Methods:
        from_kwargs: Creates a function instance from keyword arguments.
        all_coefficients: Returns all coefficient names for the function.
        required_coefficients: Returns required coefficient names.
        optional_coefficients: Returns optional coefficient names.
        get_vars: Gets variable names from the function ORM.
        get_function_orm: Retrieves the MFunction database record.
        function_type: Returns the function type string.
        set_type_cast: Sets the output type cast.
        eval_to_series: Abstract method to evaluate the function on Series.
        get_output_type_cast: Gets the output type cast specification.
        get_output_type: Determines the output data type.
        evaluate: Evaluates the function on a DataFrame.

    Generated by Duo.
    """

    EXCLUDE_VARS: ClassVar[list[str]] = ['type_cast']
    type_cast: str | None = None

    @classmethod
    def from_kwargs(cls, **kwargs: Mapping[str, Any]) -> BaseFunction:
        existed_required_kwargs = {k: v for k, v in kwargs.items() if k in cls.required_coefficients()}
        missing_required_kwargs = {k: None for k in cls.required_coefficients() if k not in existed_required_kwargs}
        optional_kwargs = {k: v for k, v in kwargs.items() if k in cls.optional_coefficients()}
        try:
            instance = cls(**existed_required_kwargs, **missing_required_kwargs, **optional_kwargs)
        except pydantic.ValidationError as exc:
            raise FunctionFieldError.from_pydantic_validation_error(exc, cls.function_type()) from exc

        return instance

    @field_validator('*', mode='before')
    @classmethod
    def validate_empty_string(cls, value: str) -> str | None:
        if isinstance(value, str) and value.strip() == EMPTY_STRING:
            return None
        return value

    @classmethod
    def all_coefficients(cls) -> set[str]:
        all_properties = cls.model_json_schema().get('properties', {}).keys()
        return {coef for coef in all_properties if coef not in cls.EXCLUDE_VARS}

    @classmethod
    def required_coefficients(cls) -> set[str]:
        return set(cls.model_json_schema().get('required', []))

    @classmethod
    def optional_coefficients(cls) -> set[str]:
        return cls.all_coefficients() - cls.required_coefficients()

    @classmethod
    def get_vars(cls) -> list[str]:
        return cls.get_function_orm().get_variables()

    @classmethod
    @CustomCache.memoize()
    def get_function_orm(cls) -> MFunction | None:
        for function_id, klass in EQUATION_DEFINITION.items():
            if klass == cls:
                return MFunction.query.get(function_id)
        return None

    @classmethod
    def function_type(cls) -> str | None:
        function_orm = cls.get_function_orm()
        if function_orm is not None:
            return function_orm.function_type
        return None

    def set_type_cast(self, type_cast: str) -> None:
        self.type_cast = type_cast

    @abstractmethod
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray: ...

    def get_output_type_cast(self) -> str | None:
        type_cast = self.type_cast if self.type_cast is not None else getattr(self, 't', None)

        # TODO: must preprocess `type_cast` to match with RawDataTypeDB
        if type_cast is None:
            return None

        output_type_cast = type_cast.strip()  # type: str
        if output_type_cast == DataTypeEncode.REAL.value:
            return RawDataTypeDB.REAL.value

        if output_type_cast == DataTypeEncode.INTEGER.value:
            return RawDataTypeDB.INTEGER.value

        if output_type_cast == DataTypeEncode.TEXT.value:
            return RawDataTypeDB.TEXT.value

        if output_type_cast == DataTypeEncode.CATEGORY.value:
            return RawDataTypeDB.CATEGORY.value

        # do not support other types
        return None

    def get_output_type(self, x_data_type: str | None = None, y_data_type: str | None = None) -> RawDataTypeDB:
        output_type_cast = self.get_output_type_cast()
        output_data_type = self.get_function_orm().get_output_data_type(x_data_type, y_data_type, output_type_cast)
        if output_data_type is None:
            raise FunctionFieldError('Get output error').add_error(
                ErrorField(
                    function_type=self.function_type(),
                    field=None,
                    msg=f'Cannot get output type for function: {self.__class__.__name__} '
                    f'with variables: {self.__dict__}',
                ),
            )
        return output_data_type

    def evaluate(
        self,
        df: pd.DataFrame,
        out_col: str,
        x_col: str | None = None,
        y_col: str | None = None,
        x_dtype: str | None = None,
        y_dtype: str | None = None,
    ):
        if df.empty:
            result_series = pd.Series([])
        else:
            df = df.reset_index(drop=True)
            m_function = self.get_function_orm()

            series_x = None
            if m_function.has_x():
                if x_col is None:
                    raise FunctionFieldError('Missing var').add_error(
                        ErrorField(function_type=self.function_type(), field='X', msg='Missing X'),
                    )

                possible_types = (
                    [m_function.get_x_data_type(x_data_type=x_dtype)]
                    if x_dtype is not None
                    else m_function.get_possible_x_types()
                )
                series_x = try_cast_series(df[x_col], possible_types)

            series_y = None
            if m_function.has_y():
                if y_col is None:
                    raise FunctionFieldError('Missing var').add_error(
                        ErrorField(function_type=self.function_type(), field='Y', msg='Missing Y'),
                    )

                possible_types = (
                    [m_function.get_y_data_type(y_data_type=y_dtype)]
                    if y_dtype is not None
                    else m_function.get_possible_y_types()
                )
                series_y = try_cast_series(df[y_col], possible_types)

            result_series = self.eval_to_series(series_x=series_x, series_y=series_y)

        raw_output_type = self.get_output_type(x_data_type=x_dtype, y_data_type=y_dtype)
        output_dtype = RawDataTypeDB.get_pandas_dtype(raw_output_type.value)
        result_series = result_series.convert_dtypes()

        maybe_none_result_series = try_cast_series_pd_types(result_series, [output_dtype])
        if maybe_none_result_series is None:
            logger.error(
                f'Function {self.__class__.__name__}:'
                f'cannot cast output from `{result_series.dtype}` to `{output_dtype}',
            )
        if maybe_none_result_series is not None:
            result_series = maybe_none_result_series

        # must change null string to NA
        if raw_output_type == RawDataTypeDB.TEXT:
            result_series = result_series.replace(to_replace=EMPTY_STRING, value=pd.NA)

        df[out_col] = result_series

        return df


class LinearFunction(BaseFunction):
    """Linear transformation function: f(x) = a*x + c.

    Applies a linear transformation to input data.

    Attributes:
        a: Slope coefficient.
        c: Intercept constant.

    Methods:
        eval_to_series: Evaluates the linear function on a Series.

    Generated by Duo.
    """

    a: float
    c: float

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return self.a * series_x + self.c


class LinearCombination(BaseFunction):
    """Linear combination function: f(x,y) = a*x + b*y + c.

    Combines two variables with linear coefficients.

    Attributes:
        a: Coefficient for X variable.
        b: Coefficient for Y variable.
        c: Intercept constant.

    Methods:
        eval_to_series: Evaluates the linear combination on two Series.

    Generated by Duo.
    """

    a: float
    b: float
    c: float

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return self.a * series_x + self.b * series_y + self.c


class Production(BaseFunction):
    """Production function: f(x,y) = a*(x*y) + c.

    Multiplies two variables and applies linear transformation.

    Attributes:
        a: Scaling coefficient.
        c: Intercept constant.

    Methods:
        eval_to_series: Evaluates the production function on two Series.

    Generated by Duo.
    """

    a: float
    c: float

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return self.a * (series_x * series_y) + self.c


class Ratio(BaseFunction):
    """Ratio function: f(x,y) = (a*x)/(b*y) + c.

    Calculates the ratio of two scaled variables with special handling for zero division.

    Attributes:
        a: Numerator coefficient.
        b: Denominator coefficient.
        c: Intercept constant.

    Methods:
        eval_to_series: Evaluates the ratio function, setting NA for 0/0 cases.

    Generated by Duo.
    """

    a: float
    b: float
    c: float

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        """
        https://github.com/pandas-dev/pandas/issues/30188
        Calling numpy calculation in Float64 dataframe, can result in np.nan exist in Float64,
        those can cause incorrect behavior, therefore, we need to handle these cases separately
        """
        a_mul = self.a * series_x
        b_mul = self.b * series_y
        result = a_mul / b_mul + self.c

        # explicitly set zeros indexes NA
        both_zeroes = (a_mul == 0) & (b_mul == 0)
        result[both_zeroes] = pd.NA

        return result


class ExpTransform(BaseFunction):
    """Exponential transformation function: f(x,y) = a*x*(10^(y-b)) + c.

    Applies exponential transformation based on two variables.

    Attributes:
        a: Scaling coefficient.
        b: Exponent offset.
        c: Intercept constant.

    Methods:
        eval_to_series: Evaluates the exponential transformation.

    Generated by Duo.
    """

    a: float
    b: float
    c: float

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return self.a * series_x * (10 ** (series_y - self.b)) + self.c


class PowTransform(BaseFunction):
    """Power transformation function: f(x) = a*(x^b) + c.

    Applies power transformation to input data.

    Attributes:
        a: Scaling coefficient.
        b: Power exponent.
        c: Intercept constant.

    Methods:
        eval_to_series: Evaluates the power transformation.

    Generated by Duo.
    """

    a: float
    b: float
    c: float

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return self.a * (series_x**self.b) + self.c


class LogTransform(BaseFunction):
    """Logarithmic transformation function: f(x) = a*log10(x-b) + c.

    Applies logarithmic transformation with special handling for negative values.

    Attributes:
        a: Scaling coefficient.
        b: Offset before logarithm.
        c: Intercept constant.

    Methods:
        eval_to_series: Evaluates the log transformation, setting NA for negative inputs.

    Generated by Duo.
    """

    a: float
    b: float
    c: float

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        """
        https://github.com/pandas-dev/pandas/issues/30188
        Calling numpy calculation in Float64 dataframe, can result in np.nan exist in Float64,
        those can cause incorrect behavior, therefore, we need to handle these cases separately
        """
        minus_b = series_x - self.b
        result = self.a * np.log10(minus_b) + self.c

        # log10(x) if x < 0 is NaN
        is_negative = minus_b < 0
        result[is_negative] = pd.NA

        return result


class HexToDec(BaseFunction):
    """Hexadecimal to decimal conversion function.

    Converts hexadecimal string values to decimal integers.

    Methods:
        _convert: Static method to convert a single hex value to decimal.
        eval_to_series: Applies hex-to-decimal conversion to a Series.

    Generated by Duo.
    """

    @staticmethod
    def _convert(value: str | None) -> int | None:
        try:
            return int(value, base=16)
        except (ValueError, TypeError):
            return pd.NA

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return series_x.apply(self._convert)


class HexToBin(BaseFunction):
    """Hexadecimal to binary conversion function.

    Converts hexadecimal string values to binary string representation.

    Methods:
        _convert: Static method to convert a single hex value to binary string.
        eval_to_series: Applies hex-to-binary conversion to a Series.

    Generated by Duo.
    """

    @staticmethod
    def _convert(value: str | None) -> str | None:
        try:
            return bin(int(value, base=16))[2:]
        except (ValueError, TypeError):
            return pd.NA

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return series_x.apply(self._convert)


class HexToLogical(BaseFunction):
    """Hexadecimal to logical bit extraction function.

    Extracts a specific bit from a hexadecimal value and returns it as a boolean.

    Attributes:
        n: The bit position to extract (1-indexed).

    Methods:
        eval_to_series: Converts hex to decimal, then extracts the nth bit as boolean.

    Generated by Duo.
    """

    n: int

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        result = HexToDec().eval_to_series(series_x=series_x, series_y=series_y)
        nth_bit = 2 ** (int(self.n) - 1)
        is_na = result.isna()
        result.loc[~is_na] = (result[~is_na] & nth_bit) != 0
        return result


class RadiusPosition(BaseFunction):
    """Calculates radial distance from a reference point.

    Computes the Euclidean distance from point (a, b) scaled by factor c.
    Formula: sqrt((x-a)^2 + (y-b)^2) / c

    Attributes:
        a: X-coordinate of the reference point.
        b: Y-coordinate of the reference point.
        c: Scaling factor for the distance.

    Methods:
        eval_to_series: Calculates radial position from two coordinate Series.

    Generated by Duo.
    """

    a: float
    b: float
    c: float

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        x_minus_a = series_x - self.a
        y_minus_b = series_y - self.b
        return np.sqrt(x_minus_a * x_minus_a + y_minus_b * y_minus_b) / self.c


class AngularPosition(BaseFunction):
    """Calculates angular position relative to a reference point.

    Computes the angle in degrees from point (a, b) with offset c.
    Formula: arctan2(y-b, x-a) converted to degrees, then subtract c.

    Attributes:
        a: X-coordinate of the reference point.
        b: Y-coordinate of the reference point.
        c: Angular offset in degrees.

    Methods:
        eval_to_series: Calculates angular position from two coordinate Series.

    Generated by Duo.
    """

    a: float
    b: float
    c: float

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        result = np.arctan2(series_y - self.b, series_x - self.a)
        result = np.rad2deg(result) - self.c
        return result


class StringExtraction(BaseFunction):
    """Extracts a substring from text data.

    Extracts characters from position n to position k, with type conversion.

    Attributes:
        n: Starting position (1-indexed, negative values count from end).
        k: Ending position (-1 for end of string, negative values count from end).
        t: Output data type (TEXT or CATEGORY).

    Methods:
        custom_validate: Validates that t is TEXT or CATEGORY.
        eval_to_series: Extracts substring and converts to specified type.

    Generated by Duo.
    """

    n: int
    k: int
    t: str

    def custom_validate(self):
        required_ts = [
            DataTypeEncode.TEXT.value,
            DataTypeEncode.CATEGORY.value,
        ]
        if self.t.strip() not in required_ts:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(function_type=self.function_type(), field='t', msg=f'Value of t must in {required_ts}'),
            )

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()
        self.set_type_cast(self.t)

        start = self.n
        if start > 0:
            start -= 1

        stop = None if self.k == -1 else self.k
        if stop is not None and stop < 0:
            stop += 1

        result = series_x.astype(pd.StringDtype()).str.slice(start=start, stop=stop)

        type_converter = TypeConvert.from_kwargs(t=self.type_cast)
        return type_converter.eval_to_series(series_x=result)


class CategoryGeneration(BaseFunction):
    """Generates categorical values by formatting two variables.

    Creates formatted strings from X and Y variables using a format template.

    Attributes:
        s: Format string with two placeholders for X and Y (e.g., "{}-{}").
        t: Output data type (TEXT or CATEGORY).

    Methods:
        count_curly_brace_pairs_in_s: Counts format field pairs in the template.
        custom_validate: Validates format string has exactly 2 fields and t is valid.
        apply_format: Applies the format string to X and Y values.
        eval_to_series: Generates formatted categories from two Series.

    Generated by Duo.
    """

    s: str
    t: str

    def count_curly_brace_pairs_in_s(self) -> int:
        pattern = r'\{[^\{\}]*\}'
        matches = re.findall(pattern, self.s)
        return len(matches)

    def custom_validate(self):
        error = FunctionFieldError(INVALID_VALUE_MSG)

        # validate number of argument format fields in s
        if self.count_curly_brace_pairs_in_s() != 2:
            error.add_error(
                ErrorField(
                    function_type=self.function_type(),
                    field='s',
                    msg='Invalid format, s must have 2 fields for X and Y',
                ),
            )

        # validate type t
        required_ts = [
            DataTypeEncode.TEXT.value,
            DataTypeEncode.CATEGORY.value,
        ]
        if self.t.strip() not in required_ts:
            raise error.add_error(
                ErrorField(function_type=self.function_type(), field='t', msg=f'Value of t must in {required_ts}'),
            )

        if error.has_error():
            raise error

    def apply_format(self, x: Any, y: Any) -> str | None:
        """
        This function is slow because we use lambda instead of vectorization
        Try to parse x, y as empty string if it is None.
        However, in case the format is specified for number (e.g: {:02d}), we can only return None if x or y is None
        """
        with contextlib.suppress(TypeError, ValueError):
            x = EMPTY_STRING if pd.isna(x) else x
            y = EMPTY_STRING if pd.isna(y) else y
            return self.s.format(x, y)

        return None

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()
        self.set_type_cast(self.t)

        result = pd.Series([self.apply_format(x, y) for x, y in zip(series_x, series_y, strict=False)])
        type_converter = TypeConvert.from_kwargs(t=self.type_cast)
        return type_converter.eval_to_series(series_x=result)


class Datetime(BaseFunction):
    """Converts string data to datetime using a specified format.

    Parses datetime strings according to the provided format string.

    Attributes:
        s: Datetime format string (e.g., "%Y-%m-%d %H:%M:%S").

    Methods:
        eval_to_series: Converts string Series to datetime using the format.

    Generated by Duo.
    """

    s: str

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return pd.to_datetime(series_x, format=self.s, errors='coerce')


class DatetimeFromDateAndTime(BaseFunction):
    """Combines separate date and time values into a single datetime.

    Merges date (X) and time (Y) columns into a localized datetime value.

    Attributes:
        s: Optional date format string (required if X is string type).
        t: Optional time format string (required if Y is string type).

    Methods:
        custom_validate: Validates that format strings are provided for string inputs.
        eval_to_series: Combines date and time Series into datetime with local timezone.

    Generated by Duo.
    """

    s: str | None = None
    t: str | None = None

    def custom_validate(self, is_x_string: bool, is_y_string: bool):
        function_field_error = FunctionFieldError(INVALID_VALUE_MSG)
        if is_x_string and not self.s:
            function_field_error.add_error(
                ErrorField(function_type=self.function_type(), field='s', msg='Missing s format for string column'),
            )
        if is_y_string and not self.t:
            function_field_error.add_error(
                ErrorField(function_type=self.function_type(), field='t', msg='Missing t format for string column'),
            )
        if function_field_error.has_error():
            raise function_field_error

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        is_x_string = not pd.api.types.is_datetime64_any_dtype(series_x)
        is_y_string = not pd.api.types.is_datetime64_any_dtype(series_y)

        self.custom_validate(is_x_string, is_y_string)

        date_format = self.s if is_x_string and self.s else FUNCTION_DATE_FORMAT
        time_format = self.t if is_y_string and self.t else FUNCTION_TIME_FORMAT

        result_format = f'{date_format}{time_format}'

        # extract date format
        if not is_x_string:
            series_x = series_x.dt.strftime(date_format)

        # extract time format
        if not is_y_string:
            series_y = series_y.dt.strftime(time_format)

        return pd.to_datetime(series_x + series_y, format=result_format, exact=True, errors='coerce').dt.tz_localize(
            tz.tzlocal(),
        )


class DateExtraction(BaseFunction):
    """Extracts date components using a format string.

    Formats datetime values according to a strftime format string.

    Attributes:
        s: Date format string for extraction (e.g., "%Y", "%m", "%Y%m%d").

    Methods:
        eval_to_series: Extracts and formats date components, auto-casting to integer if possible.

    Generated by Duo.
    """

    s: str

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        result = series_x.dt.strftime(self.s).astype(pd.StringDtype())
        # try to cast result to integer
        with contextlib.suppress(ValueError, TypeError):
            result = result.astype(pd.Int64Dtype())
        self.set_type_cast(get_data_encoding_type_from_series(result).value)
        return result


class TimeframeExtraction(BaseFunction):
    """Categorizes datetime values into time intervals.

    Bins datetime values into time ranges starting at hour a with interval b.

    Attributes:
        a: Starting hour (0-24, can include decimals for minutes).
        b: Interval duration in hours (0.5-24).

    Methods:
        _interval_to_label: Converts minute intervals to "HH:MM-HH:MM" labels.
        custom_validate: Validates that a and b are within valid ranges.
        eval_to_series: Bins datetime values into labeled time intervals.

    Generated by Duo.
    """

    a: float
    b: float

    @staticmethod
    def _interval_to_label(left: int, right: int) -> str:
        mid_night = 24 * 60

        # exceed 1 day
        if left > mid_night:
            left -= mid_night
            right -= mid_night

        def minute_to_string(minute: float) -> str:
            h = int(minute) // 60
            m = int(minute) % 60
            return f'{h:02d}:{m:02d}'

        return f'{minute_to_string(left)}-{minute_to_string(right)}'

    def custom_validate(self):
        function_field_error = FunctionFieldError(INVALID_VALUE_MSG)
        if self.a < 0 or self.a >= 24:
            function_field_error.add_error(
                ErrorField(function_type=self.function_type(), field='a', msg='Value of a must be between 0 and 24'),
            )
        if self.b < 0.5 or self.b >= 24:
            function_field_error.add_error(
                ErrorField(function_type=self.function_type(), field='b', msg='Value of b must be between 0.5 and 24'),
            )
        if function_field_error.has_error():
            raise function_field_error

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()

        # calculate bins by minutes
        shift_a_day = 24 * 60
        start = self.a * 60  # convert to minutes
        end = start + shift_a_day  # the next day (by minutes)
        freq = self.b * 60  # convert to minute
        bins = np.arange(start, end, freq)
        if end != bins[-1]:
            bins = np.append(bins, end)

        # calculate minutes in each record
        time_data = series_x.dt.hour * 60 + series_x.dt.minute

        # handle edge case where the hour indicated is out of range
        # for example: start = 9.5 but [hour] we looking for is 1.5 => need to shift it to correct time range
        invalid_index = time_data < start
        time_data.loc[invalid_index] = time_data[invalid_index] + shift_a_day

        # cut and rename to correct category
        labels = [self._interval_to_label(left, right) for left, right in pairwise(bins)]
        result = pd.cut(time_data, bins=bins, labels=labels)

        return result


class WeekdayExtraction(BaseFunction):
    """Extracts weekday names from datetime values.

    Converts datetime to weekday names in various formats and languages.

    Attributes:
        n: Format selector (0=short English, 1=full English, 2=short Japanese, 3=full Japanese).

    Methods:
        custom_validate: Validates that n is between 0 and 3.
        eval_to_series: Extracts weekday names in the specified format.

    Generated by Duo.
    """

    n: int

    def custom_validate(self):
        if self.n < 0 or self.n > 3:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(function_type=self.function_type(), field='n', msg='Value of a must be between 0 and 3'),
            )

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()

        locale_translator = {
            0: {0: 'Mon', 1: 'Tue', 2: 'Wed', 3: 'Thu', 4: 'Fri', 5: 'Sat', 6: 'Sun'},
            1: {0: 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Friday', 5: 'Saturday', 6: 'Sunday'},
            2: {0: '月', 1: '火', 2: '水', 3: '木', 4: '金', 5: '土', 6: '日'},
            3: {0: '月曜日', 1: '火曜日', 2: '水曜日', 3: '木曜日', 4: '金曜日', 5: '土曜日', 6: '日曜日'},
        }

        result = series_x.dt.weekday.replace(locale_translator[self.n])

        return result


class WeekNumExtraction(BaseFunction):
    """Extracts ISO week number from datetime values.

    Returns the week number according to ISO 8601 calendar.

    Methods:
        eval_to_series: Extracts ISO week number from datetime Series.

    Generated by Duo.
    """

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return series_x.dt.isocalendar().week


class DayExtraction(BaseFunction):
    """Extracts day of month from datetime values.

    Returns the day component (1-31) from datetime values.

    Methods:
        eval_to_series: Extracts day of month from datetime Series.

    Generated by Duo.
    """

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return series_x.dt.day


class MonthExtraction(BaseFunction):
    """Extracts month from datetime values.

    Returns the month component (1-12) from datetime values.

    Methods:
        eval_to_series: Extracts month from datetime Series.

    Generated by Duo.
    """

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return series_x.dt.month


class YearExtraction(BaseFunction):
    """Extracts year from datetime values.

    Returns either full year or 2-digit year based on parameter n.

    Attributes:
        n: Format selector (0=full year, 1=2-digit year).

    Methods:
        eval_to_series: Extracts year from datetime Series.

    Generated by Duo.
    """

    n: int

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        year = series_x.dt.year
        if self.n == 0:
            return year
        return year % 100


class LogicalEqual(BaseFunction):
    """Performs equality or inequality comparison with multiple values.

    Compares Series values against one or more target values using == or != operator.

    Attributes:
        s: Comma-separated list of values to compare against.
        t: Comparison operator ('==' or '!=').

    Methods:
        custom_validate: Validates that t is '==' or '!='.
        _logical_equal: Performs comparison for a single value.
        eval_to_series: Performs comparison against all values in s.

    Generated by Duo.
    """

    s: str
    t: str

    def custom_validate(self):
        required_ts = ['==', '!=']
        if self.t.strip() not in required_ts:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(
                    function_type=self.function_type(),
                    field='t',
                    msg=f'Value of t must in {required_ts}',
                ),
            )

    def _logical_equal(self, series: pd.Series, value: str) -> pd.Series:
        s, _ = cast_value_based_on_series(series, value)
        result = series == s if self.t.strip() == '==' else series != s
        return result

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()
        result = pd.Series(False, index=series_x.index)
        for value in self.s.split(MULTIPLE_VALUES_CONNECTOR):
            result = result | self._logical_equal(series_x, value)

        return result


class LogicalNotEqual(BaseFunction):
    """Performs relational comparison operations.

    Compares Series values using relational operators (>, <, >=, <=).

    Attributes:
        s: Value to compare against.
        t: Comparison operator ('>', '<', '>=', or '<=').

    Methods:
        custom_validate: Validates that t is a valid relational operator.
        eval_to_series: Performs the specified relational comparison.

    Generated by Duo.
    """

    s: str
    t: str

    def custom_validate(self):
        required_ts = ['>', '<', '>=', '<=']
        if self.t.strip() not in required_ts:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(function_type=self.function_type(), field='t', msg=f'Value of t must in {required_ts}'),
            )

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()

        s, _ = cast_value_based_on_series(series_x, self.s)

        t = self.t.strip()

        result = None
        if t == '>':
            result = series_x > s
        elif t == '<':
            result = series_x < s
        elif t == '>=':
            return series_x >= s
        elif t == '<=':
            return series_x <= s

        return result


class LogicalOr(BaseFunction):
    """Performs logical OR operation on two boolean Series.

    Combines two boolean Series using OR logic, preserving NA values.

    Methods:
        eval_to_series: Performs element-wise OR operation on two Series.

    Generated by Duo.
    """

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        is_na = series_x.isna() | series_y.isna()
        result = series_x.astype(pd.BooleanDtype()) | series_y.astype(pd.BooleanDtype())
        result.loc[is_na] = pd.NA
        return result


class LogicalAnd(BaseFunction):
    """Performs logical AND operation on two boolean Series.

    Combines two boolean Series using AND logic, preserving NA values.

    Methods:
        eval_to_series: Performs element-wise AND operation on two Series.

    Generated by Duo.
    """

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        is_na = series_x.isna() | series_y.isna()
        result = series_x.astype(pd.BooleanDtype()) & series_y.astype(pd.BooleanDtype())
        result.loc[is_na] = pd.NA
        return result


class RegexExtraction(BaseFunction):
    """Extracts text matching a regular expression pattern.

    Extracts substrings matching regex groups, with optional type conversion.

    Attributes:
        s: Regular expression pattern (groups are automatically added if missing).
        t: Optional output data type for conversion.

    Methods:
        custom_validate: Validates regex pattern and ensures it has groups.
        eval_to_series: Extracts matching text and converts to specified type.

    Generated by Duo.
    """

    s: str
    t: str | None = None

    def custom_validate(self):
        try:
            regex = re.compile(self.s, flags=0)
        except re.error as exc:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(function_type=self.function_type(), field='s', msg='Invalid regex'),
            ) from exc

        # if no group is present, we assign this as a new group
        # because pandas.str.extract requires pattern should have groups
        if regex.groups == 0:
            self.s = f'({self.s})'

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()

        extracted_x = series_x.astype(pd.StringDtype()).str.extract(self.s)

        columns = extracted_x.columns
        # always convert to string when we have multiple groups:
        if len(columns) > 1:
            self.set_type_cast(DataTypeEncode.TEXT.value)
        elif self.t:
            self.set_type_cast(self.t)
        else:
            self.set_type_cast(get_data_encoding_type_from_series(series_x).value)

        result = extracted_x[columns[0]]
        for col in columns[1:]:
            result = result + MULTIPLE_VALUES_CONNECTOR + extracted_x[col]

        type_converter = TypeConvert.from_kwargs(t=self.type_cast)
        return type_converter.eval_to_series(series_x=result)


class RegexRemoval(BaseFunction):
    """Removes text matching regular expression patterns.

    Removes substrings matching one or more regex patterns from text data.

    Attributes:
        s: Comma-separated list of regex patterns to remove.
        t: Optional output data type (defaults to original type if not specified).

    Methods:
        eval_to_series: Removes matching patterns and converts to specified type.

    Generated by Duo.
    """

    s: str
    t: str | None = None

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        result = series_x.astype(pd.StringDtype())
        for pat in self.s.split(MULTIPLE_VALUES_CONNECTOR):
            result = result.str.replace(pat, EMPTY_STRING, regex=True)

        # keep original type if `self.t` is not defined
        self.set_type_cast(self.t if self.t else get_data_encoding_type_from_series(series_x).value)

        type_converter = TypeConvert.from_kwargs(t=self.type_cast)
        return type_converter.eval_to_series(series_x=result)


class RegexReplacement(BaseFunction):
    """Replaces text matching a regular expression pattern.

    Replaces substrings matching regex pattern s with replacement string t.

    Attributes:
        s: Regular expression pattern to match.
        t: Replacement string.

    Methods:
        eval_to_series: Performs regex replacement on text Series.

    Generated by Duo.
    """

    s: str
    t: str

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        return series_x.astype(pd.StringDtype()).str.replace(self.s, self.t, regex=True)


class Merge(BaseFunction):
    """Merges two Series by filling missing values.

    Combines two Series of the same type, using Y to fill NA values in X.

    Attributes:
        t: Output data type for the merged result.

    Methods:
        eval_to_series: Merges two Series and converts to specified type.

    Generated by Duo.
    """

    t: str

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        if series_x.dtype != series_y.dtype:
            raise FunctionFieldError(MUST_HAVE_THE_SAME_TYPE_MSG).add_error(
                ErrorField(function_type=self.function_type(), field='X', msg=MUST_HAVE_THE_SAME_TYPE_MSG),
                ErrorField(function_type=self.function_type(), field='Y', msg=MUST_HAVE_THE_SAME_TYPE_MSG),
            )

        if pd.api.types.is_string_dtype(series_x):
            series_x = series_x.replace({EMPTY_STRING: pd.NA})
            series_y = series_y.replace({EMPTY_STRING: pd.NA})

        result = series_x.combine_first(series_y)
        self.set_type_cast(self.t)
        type_converter = TypeConvert.from_kwargs(t=self.type_cast)
        return type_converter.eval_to_series(series_x=result)


class Lookup(BaseFunction):
    """Performs value lookup and replacement with type conversion.

    Maps values from s to corresponding values in t, with optional type specification.

    Attributes:
        s: Comma-separated list of values to match.
        t: Comma-separated list of replacement values (optionally with ::type suffix).

    Methods:
        split_multiple_values_connector: Parses t to extract values and output type.
        custom_validate: Validates that s and t have the same number of values.
        eval_to_series: Performs lookup replacement and type conversion.

    Generated by Duo.
    """

    s: str
    t: str

    def split_multiple_values_connector(self) -> tuple[list[str], str]:
        multi_parts_connector = self.t.split(MULTIPLE_VALUES_CONNECTOR)

        if DOUBLE_COLON_CONNECTOR in multi_parts_connector[-1]:
            # split the string at the first occurrence
            last_part, type_part = multi_parts_connector[-1].split(DOUBLE_COLON_CONNECTOR, 1)
            multi_parts_connector[-1] = last_part
            type_part = type_part if type_part else DataTypeEncode.TEXT.value
        else:
            type_part = DataTypeEncode.TEXT.value

        return multi_parts_connector, type_part

    def custom_validate(self):
        values = self.s.split(MULTIPLE_VALUES_CONNECTOR)
        multi_parts_connector = self.t.split(MULTIPLE_VALUES_CONNECTOR)

        if DOUBLE_COLON_CONNECTOR in multi_parts_connector[-1]:
            t_value, _ = multi_parts_connector[-1].split(DOUBLE_COLON_CONNECTOR, 1)
        else:
            t_value = self.t

        error_msg = (
            f'{self.s} and {t_value} must have the same number of values connected by {MULTIPLE_VALUES_CONNECTOR}'
        )
        replace_values, return_type = self.split_multiple_values_connector()

        if len(values) != len(replace_values):
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(function_type=self.function_type(), field='s', msg=error_msg),
                ErrorField(function_type=self.function_type(), field='t', msg=error_msg),
            )

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()

        values = self.s.split(MULTIPLE_VALUES_CONNECTOR)
        replace_values, output_type_cast = self.split_multiple_values_connector()
        dict_replace = dict(zip(values, replace_values, strict=False))
        self.set_type_cast(output_type_cast)
        result = series_x.astype(pd.StringDtype())

        # handle special boolean case
        if pd.api.types.is_bool_dtype(series_x):
            true_keys = [k for k, v in BOOLEAN_DICT_VALUES.items() if v]
            false_keys = [k for k, v in BOOLEAN_DICT_VALUES.items() if not v]

            truth_values = [dict_replace.get(k) for k in true_keys]
            false_values = [dict_replace.get(k) for k in false_keys]

            if truth_values:
                result[series_x] = truth_values[0]
            if false_values:
                result[~series_x] = false_values[0]
        else:
            result = result.replace(dict_replace)

        type_converter = TypeConvert.from_kwargs(t=self.type_cast)
        return type_converter.eval_to_series(series_x=result)


class TypeConvert(BaseFunction):
    """Converts Series data to a specified type.

    Performs type conversion with special handling for boolean, numeric, and string types.

    Attributes:
        t: Target data type (REAL, INTEGER, TEXT, or CATEGORY).

    Methods:
        custom_validate: Validates that t is a supported data type.
        eval_to_series: Converts Series to the specified type.

    Generated by Duo.
    """

    t: str

    def custom_validate(self):
        if self.t is None:
            return None

        required_ts = [
            DataTypeEncode.REAL.value,
            DataTypeEncode.INTEGER.value,
            DataTypeEncode.TEXT.value,
            DataTypeEncode.CATEGORY.value,
        ]
        if self.t.strip() not in required_ts:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(
                    function_type=self.function_type(),
                    field='t',
                    msg=f'Value of type conversion should be in {required_ts}',
                ),
            )

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()

        self.set_type_cast(self.t)

        type_cast = self.get_output_type_cast()
        pd_type = RawDataTypeDB.get_pandas_dtype(type_cast)

        if pd.api.types.is_bool_dtype(series_x):
            if pd.api.types.is_float_dtype(pd_type):
                series_x = series_x.astype('float64')  # Float64 can not astype pd.Series(True, pd.NA, False)
            elif pd_type == pd.StringDtype():
                series_x = series_x.astype(pd_type).str.lower()
            else:
                series_x = series_x.astype(pd_type)

            return series_x

        if pd.api.types.is_numeric_dtype(pd_type):
            casted_x = pd.to_numeric(series_x, errors='coerce')

            if pd.api.types.is_float_dtype(pd_type):
                return casted_x

            # replace float data as NA
            float_index = (np.floor(casted_x) - casted_x) != 0
            casted_x.loc[float_index] = pd.NA

            return casted_x.astype(pd_type)

        # dtype is string
        return series_x.astype(pd_type)


class Shift(BaseFunction):
    """Shifts Series values by a specified number of positions.

    Shifts data forward or backward, filling with a constant value.

    Attributes:
        s: Fill value for shifted positions.
        t: Number of positions to shift (positive=forward, negative=backward).

    Methods:
        custom_validate: Validates that t is an integer.
        eval_to_series: Shifts Series and fills with specified value.

    Generated by Duo.
    """

    s: str
    t: str

    def custom_validate(self):
        try:
            int(self.t)
        except ValueError as e:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(
                    function_type=self.function_type(),
                    field='t',
                    msg=f'Only accept integer value for t, received `{self.t}` instead',
                ),
            ) from e

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()

        s, convertible = cast_value_based_on_series(series_x, self.s)

        t = int(self.t)

        # no need to cast type
        if convertible:
            result = series_x.shift(t, fill_value=s)
        else:
            if isinstance(s, int):
                casted_series = series_x.astype(pd.Int64Dtype())
            elif isinstance(s, float):
                casted_series = series_x.astype(pd.Float64Dtype())
            elif isinstance(s, str):
                casted_series = series_x.astype(pd.StringDtype())
            else:
                raise NotImplementedError(f'Cannot cast `s` of type {type(s)}')

            result = casted_series.shift(t, fill_value=s)

        self.set_type_cast(get_data_encoding_type_from_series(result).value)

        return result


class FillNa(BaseFunction):
    """Fills missing values using various strategies.

    Fills NA values using constant, forward fill, backward fill, or combinations.

    Attributes:
        s: Optional constant value for filling (required if 'c' is in t).
        t: Fill strategy ('c'=constant, 'b'=backfill, 'f'=forward fill, or combinations).

    Methods:
        custom_validate: Validates fill strategy and required parameters.
        eval_to_series: Fills NA values according to the specified strategy.

    Generated by Duo.
    """

    s: str | None = None
    t: str

    def custom_validate(self):
        required_ts = ['c', 'b', 'f', 'bc', 'fc', 'bf', 'fb']
        if self.t.strip() not in required_ts:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(function_type=self.function_type(), field='t', msg=f'Value of t must in {required_ts}'),
            )

        if 'c' in self.t.strip() and self.s is None:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(
                    function_type=self.function_type(),
                    field='s',
                    msg='Must provide s when fillna using constant',
                ),
            )

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()

        for fill_method in self.t.strip():
            if fill_method == 'b':
                series_x = series_x.fillna(method='ffill')
            elif fill_method == 'f':
                series_x = series_x.fillna(method='bfill')
            elif fill_method == 'c':
                s, convertible = cast_value_based_on_series(series_x, self.s)
                if not convertible:
                    raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                        ErrorField(
                            function_type=self.function_type(),
                            field='s',
                            msg=f'Cannot cast `s` of type {type(s)}',
                        ),
                    )

                series_x = series_x.fillna(s)

        self.set_type_cast(get_data_encoding_type_from_series(series_x).value)

        return series_x


class NumberRemoval(BaseFunction):
    """Removes specific numeric values by setting them to NA.

    Replaces up to three specified numeric values with NA.

    Attributes:
        a: First value to remove.
        b: Optional second value to remove.
        c: Optional third value to remove.

    Methods:
        eval_to_series: Removes specified numeric values from Series.

    Generated by Duo.
    """

    a: float
    b: float | None = None
    c: float | None = None

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        result = series_x.copy()
        if self.a is not None:
            result.loc[result == float(self.a)] = pd.NA
        if self.b is not None:
            result.loc[result == float(self.b)] = pd.NA
        if self.c is not None:
            result.loc[result == float(self.c)] = pd.NA

        return result


class RangeRemoval(BaseFunction):
    """Removes values within a specified range by setting them to NA.

    Replaces values between a and b (inclusive) with NA.

    Attributes:
        a: Lower bound of the range to remove.
        b: Upper bound of the range to remove.

    Methods:
        eval_to_series: Removes values within the specified range.

    Generated by Duo.
    """

    a: float | None = None
    b: float | None = None

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        result = series_x.copy()
        result.loc[(result >= float(self.a)) & (result <= float(self.b))] = pd.NA
        return result


class OutOfRangeRemoval(BaseFunction):
    """Removes values outside a specified range by setting them to NA.

    Replaces values less than a or greater than b with NA.

    Attributes:
        a: Lower bound (values below this are removed).
        b: Upper bound (values above this are removed).

    Methods:
        eval_to_series: Removes values outside the specified range.

    Generated by Duo.
    """

    a: float | None = None
    b: float | None = None

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        result = series_x.copy()
        result.loc[(result < float(self.a)) | (result > float(self.b))] = pd.NA
        return result


class StringRemoval(BaseFunction):
    """Removes specific string values by setting them to NA.

    Replaces exact string matches with NA and converts to specified type.

    Attributes:
        s: String value to remove.
        t: Output data type (TEXT or CATEGORY).

    Methods:
        custom_validate: Validates that t is TEXT or CATEGORY.
        eval_to_series: Removes specified string and converts to specified type.

    Generated by Duo.
    """

    s: str
    t: str

    def custom_validate(self):
        required_ts = [
            DataTypeEncode.TEXT.value,
            DataTypeEncode.CATEGORY.value,
        ]
        if self.t.strip() not in required_ts:
            raise FunctionFieldError(INVALID_VALUE_MSG).add_error(
                ErrorField(function_type=self.function_type(), field='t', msg=f'Value of t must in {required_ts}'),
            )

    @override
    def eval_to_series(
        self,
        *,
        series_x: pd.Series | None = None,
        series_y: pd.Series | None = None,
    ) -> pd.Series | np.NDArray:
        self.custom_validate()
        self.set_type_cast(self.t)

        result = series_x.copy()
        if self.s is not None:
            result.loc[result == self.s] = pd.NA

        type_convert = TypeConvert.from_kwargs(t=self.type_cast)
        return type_convert.eval_to_series(series_x=result)


EQUATION_DEFINITION = {
    10: LinearFunction,
    11: LinearCombination,
    12: Production,
    13: Ratio,
    14: ExpTransform,
    15: PowTransform,
    16: LogTransform,
    20: HexToDec,
    21: HexToBin,
    22: HexToLogical,
    28: RadiusPosition,
    29: AngularPosition,
    30: StringExtraction,
    32: CategoryGeneration,
    40: Datetime,
    41: DatetimeFromDateAndTime,
    42: DateExtraction,
    43: TimeframeExtraction,
    44: WeekdayExtraction,
    45: WeekNumExtraction,
    46: DayExtraction,
    47: MonthExtraction,
    48: YearExtraction,
    50: LogicalEqual,
    51: LogicalNotEqual,
    55: LogicalOr,
    56: LogicalAnd,
    60: RegexExtraction,
    61: RegexRemoval,
    62: RegexReplacement,
    70: Merge,
    71: Lookup,
    72: TypeConvert,
    80: Shift,
    90: FillNa,
    120: NumberRemoval,
    121: RangeRemoval,
    122: OutOfRangeRemoval,
    130: StringExtraction,
    131: StringRemoval,
    160: RegexExtraction,
    161: RegexRemoval,
    162: RegexReplacement,
    170: Merge,
    171: Lookup,
    172: TypeConvert,
    190: FillNa,
}
