from __future__ import annotations

import dataclasses
from typing import TYPE_CHECKING, Any, Union

from flask import Response, jsonify

if TYPE_CHECKING:
    from werkzeug.exceptions import HTTPException


@dataclasses.dataclass
class ErrorMessage:
    """Data class representing a single error message.

    Encapsulates error information with a reason code and descriptive message.

    Attributes:
        reason: Short identifier or code for the error type.
        message: Detailed human-readable error message.

    Generated by Duo.
    """

    reason: str
    message: str


@dataclasses.dataclass
class Errors:
    """Collection of error messages for API error handling.

    Manages a list of ErrorMessage objects with utility methods for
    adding, checking, and rendering errors.

    Attributes:
        errors: List of ErrorMessage objects representing all errors.

    Methods:
        add_error_message: Adds one or more error messages to the collection.
        has_error: Checks if any errors exist in the collection.
        clear: Removes all errors from the collection.
        render: Converts the errors to a dictionary format.

    Generated by Duo.
    """

    errors: list[ErrorMessage] = dataclasses.field(default_factory=list)

    def add_error_message(
        self,
        *,
        error_msg: Union[ErrorMessage | None, list[ErrorMessage]] = None,
    ) -> None:
        if error_msg is None:
            return
        if isinstance(error_msg, ErrorMessage):
            self.errors.append(error_msg)
        elif isinstance(error_msg, list):
            for err in error_msg:
                if not isinstance(error_msg, ErrorMessage):
                    raise RuntimeError(
                        'Invalid usage: `error_msg` must be a list of `ErrorMessage`',
                    )
                self.errors.append(err)

    def __len__(self) -> int:
        """
        Return the number of error messages in the collection.

        Returns:
            int: Count of ErrorMessage items.

        Generated by Junie
        """
        return len(self.errors)

    def __str__(self) -> str:
        """
        Return a newline-joined string of error messages.

        Returns:
            str: Concatenated string representation of all ErrorMessage items.

        Generated by Junie
        """
        return '\n'.join(map(str, self.errors))

    def clear(self):
        self.errors = []

    def has_error(self) -> bool:
        return len(self) > 0

    def render(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


class APIError(Exception):
    """Custom exception class for API errors with structured error messages.

    Provides a standardized way to handle and return API errors with
    HTTP status codes and detailed error information.

    Attributes:
        errors: Collection of error messages.
        status_code: HTTP status code for the error response.

    Methods:
        with_status: Sets the HTTP status code for the error.
        add_error: Adds additional error messages to the exception.
        has_errors: Checks if any errors are present.
        response: Generates a Flask JSON response for the error.
        check_error: Raises the exception if errors exist.
        from_http_error: Creates an APIError from an HTTPException.

    Generated by Duo.
    """

    def __init__(
        self,
        status_code: int = 500,
        error_msg: Union[ErrorMessage | None, list[ErrorMessage]] = None,
    ) -> None:
        self.errors = Errors()
        self.errors.add_error_message(error_msg=error_msg)
        self.status_code = status_code

    def __str__(self) -> str:
        """
        Return the string representation of the underlying error collection.

        Returns:
            str: String form of the Errors container.

        Generated by Junie
        """
        return str(self.errors)

    def with_status(self, status_code: int) -> APIError:
        self.status_code = status_code
        return self

    def add_error(
        self,
        error_msg: Union[ErrorMessage | None, list[ErrorMessage]] = None,
    ) -> APIError:
        self.errors.add_error_message(error_msg=error_msg)
        return self

    def has_errors(self) -> bool:
        return self.errors.has_error()

    @property
    def description(self) -> dict[str, Any]:
        return self.errors.render()

    def response(self) -> Response:
        response = jsonify(self.description)
        response.status_code = self.status_code
        return response

    def check_error(self) -> None:
        if self.has_errors():
            raise self

    @classmethod
    def from_http_error(cls, e: HTTPException) -> APIError:
        return cls(
            status_code=e.code,
            error_msg=ErrorMessage(reason=e.description, message=e.description),
        )
