"""export filter

Revision ID: baff361f9e06
Revises: b4eace1bb217
Create Date: 2025-10-31 12:02:09.966851

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'baff361f9e06'
down_revision = 'b4eace1bb217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cfg_export_filter',
        sa.Column('export_id', sa.Integer(), nullable=False),
        sa.Column('filter_detail_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['export_id'],
            ['cfg_export.id'],
            name=op.f('fk_cfg_export_filter_export_id_cfg_export'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['filter_detail_id'],
            ['cfg_filter_detail.id'],
            name=op.f('fk_cfg_export_filter_filter_detail_id_cfg_filter_detail'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('export_id', 'filter_detail_id', name=op.f('pk_cfg_export_filter')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cfg_export_filter')
    # ### end Alembic commands ###
