"""migrate export config

Revision ID: 5db269a8c04a
Revises: 49401a46123b
Create Date: 2025-09-16 11:01:13.235354

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5db269a8c04a'
down_revision = '49401a46123b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cfg_export',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('export_from', sa.String(), nullable=False),
        sa.Column('export_to', sa.String(), nullable=True),
        sa.Column('process_id', sa.Integer(), nullable=False),
        sa.Column('export_frequency', sa.Integer(), nullable=True),
        sa.Column('folder_path', sa.String(), nullable=False),
        sa.Column('file_type', sa.String(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('updated_at', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['process_id'], ['cfg_process.id'], name=op.f('fk_cfg_export_process_id_cfg_process'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_cfg_export')),
        sqlite_autoincrement=True,
    )
    op.create_table(
        'cfg_export_detail',
        sa.Column('export_id', sa.Integer(), nullable=False),
        sa.Column('process_column_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['export_id'], ['cfg_export.id'], name=op.f('fk_cfg_export_detail_export_id_cfg_export')
        ),
        sa.ForeignKeyConstraint(
            ['process_column_id'],
            ['cfg_process_column.id'],
            name=op.f('fk_cfg_export_detail_process_column_id_cfg_process_column'),
        ),
        sa.PrimaryKeyConstraint('export_id', 'process_column_id', name=op.f('pk_cfg_export_detail')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cfg_export_detail')
    op.drop_table('cfg_export')
    # ### end Alembic commands ###
