"""add pull_from

Revision ID: 70c90e89a142
Revises: 09d1cd13a9ac
Create Date: 2025-09-04 14:09:59.867480

"""

import sqlalchemy as sa
from alembic import op

from migrations.versions import remove_orphaned_data

# revision identifiers, used by Alembic.
revision = '70c90e89a142'
down_revision = '09d1cd13a9ac'
branch_labels = None
depends_on = None


def upgrade():
    remove_orphaned_data()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_data_source_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pull_from', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_data_source_db', schema=None) as batch_op:
        batch_op.drop_column('pull_from')

    # ### end Alembic commands ###
