"""add web detail

Revision ID: 925e53b79d74
Revises: ebaa22873218
Create Date: 2025-09-15 13:45:48.443671

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '925e53b79d74'
down_revision = 'ebaa22873218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cfg_data_source_web',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('url', sa.VARCHAR(), nullable=False),
        sa.Column('created_at', sa.VARCHAR(), nullable=False),
        sa.Column('updated_at', sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id'], ['cfg_data_source.id'], name=op.f('fk_cfg_data_source_web_id_cfg_data_source'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_cfg_data_source_web')),
        sqlite_autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cfg_data_source_web')
    # ### end Alembic commands ###
