"""add cfg label

Revision ID: 49b1b6cb43d3
Revises: baff361f9e06
Create Date: 2025-11-21 10:35:21.477846

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm

from migrations import system_labels_import

# revision identifiers, used by Alembic.
revision = '49b1b6cb43d3'
down_revision = 'c4272af5047c'
branch_labels = None
depends_on = None


def populate_process_labels():
    """Populate cfg_process_label with default labels based on datasource type"""
    conn = op.get_bind()

    # Insert into cfg_process_label by joining cfg_process with cfg_data_source
    # and matching datasource type with label name
    conn.execute(
        sa.text("""
                INSERT INTO cfg_process_label (process_id, label_id)
                SELECT
                    cp.id AS process_id,
                    cl.id AS label_id
                FROM cfg_process cp
                INNER JOIN cfg_data_source cds ON cp.data_source_id = cds.id
                INNER JOIN cfg_label cl ON cds.type = cl.name
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM cfg_process_label cpl
                    WHERE cpl.process_id = cp.id AND cpl.label_id = cl.id
                )
            """)
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cfg_label',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_cfg_label')),
        sa.UniqueConstraint('name', name=op.f('uq_cfg_label_name')),
        sqlite_autoincrement=True,
    )
    op.create_table(
        'cfg_process_label',
        sa.Column('process_id', sa.Integer(), nullable=False),
        sa.Column('label_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['label_id'], ['cfg_label.id'], name=op.f('fk_cfg_process_label_label_id_cfg_label'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['process_id'],
            ['cfg_process.id'],
            name=op.f('fk_cfg_process_label_process_id_cfg_process'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('process_id', 'label_id', name=op.f('pk_cfg_process_label')),
    )

    # ### end Alembic commands ###
    system_labels_import(orm.Session(bind=op.get_bind()))
    op.execute("UPDATE sqlite_sequence SET seq=1000 WHERE name='cfg_label'")

    populate_process_labels()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cfg_process_label')
    op.drop_table('cfg_label')
    op.execute("DELETE FROM sqlite_sequence WHERE name='cfg_label'")
    # ### end Alembic commands ###
