"""migrate_import_filter

Revision ID: 49401a46123b
Revises: 925e53b79d74
Create Date: 2025-09-16 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '49401a46123b'
down_revision = '925e53b79d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cfg_import_filter_detail')
    op.drop_table('cfg_import_filter')
    with op.batch_alter_table('cfg_process_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_process_column', schema=None) as batch_op:
        batch_op.drop_column('filter')

    op.create_table(
        'cfg_import_filter',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('column_id', sa.INTEGER(), nullable=False),
        sa.Column('filter_function', sa.VARCHAR(), nullable=False),
        sa.Column('filter_from_position', sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ['column_id'],
            ['cfg_process_column.id'],
            name='fk_cfg_import_filter_column_id_cfg_process_column',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name='pk_cfg_import_filter'),
    )
    op.create_table(
        'cfg_import_filter_detail',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('value', sa.VARCHAR(), nullable=False),
        sa.Column('filter_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ['filter_id'],
            ['cfg_import_filter.id'],
            name='fk_cfg_import_filter_detail_filter_id_cfg_import_filter',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name='pk_cfg_import_filter_detail'),
    )
    # ### end Alembic commands ###
