"""migrate_polling_frequency

Revision ID: 09d1cd13a9ac
Revises: b947a1beb4f1
Create Date: 2025-08-28 09:53:22.630158

"""

import sqlalchemy as sa
from alembic import op

from ap.common.constants import DEFAULT_POLLING_FREQ, DEFAULT_SNOWFLAKE_POLLING_FREQ, DBType
from migrations.versions import remove_orphaned_data

# revision identifiers, used by Alembic.
revision = '09d1cd13a9ac'
down_revision = 'b947a1beb4f1'
branch_labels = None
depends_on = None


def upgrade():
    remove_orphaned_data()
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_data_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('polling_frequency', sa.Integer(), nullable=True))
    get_ds_sql = 'SELECT * FROM cfg_data_source'
    get_polling_freq_sql = "SELECT value FROM cfg_constant WHERE type = 'POLLING_FREQUENCY'"
    data_sources = conn.execute(sa.text(get_ds_sql)).fetchall()
    result = conn.execute(sa.text(get_polling_freq_sql)).fetchone()
    interval_sec = (
        int(result._mapping.get('value'))
        if result and result._mapping.get('value') is not None
        else DEFAULT_POLLING_FREQ
    )
    # change from 0 to None if the option is import only one time
    interval_sec = None if interval_sec == 0 else interval_sec

    data_sources = [data_source._asdict() for data_source in data_sources]
    for data_source in data_sources:
        data_source['polling_frequency'] = interval_sec
        if data_source.get('type') in [DBType.SNOWFLAKE.name, DBType.SNOWFLAKE_SOFTWARE_WORKSHOP.name]:
            data_source['polling_frequency'] = DEFAULT_SNOWFLAKE_POLLING_FREQ
        cols_str = ','.join([f'"{k}"' if k == 'order' else k for k in data_source.keys()])
        param_str = ','.join([f':{key}' for key in data_source.keys()])
        sql = sa.text(f'INSERT OR REPLACE INTO cfg_data_source ({cols_str}) VALUES ({param_str})')
        sql = sql.bindparams(*[sa.bindparam(key) for key in data_source.keys()])
        conn.execute(sql, data_source)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_data_source', schema=None) as batch_op:
        batch_op.drop_column('polling_frequency')

    # ### end Alembic commands ###
