"""export_data_with_multi_processes

Revision ID: 9fde3812d3a7
Revises: 1c812fef361d
Create Date: 2026-04-13 15:02:07.392919

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9fde3812d3a7'
down_revision = '1c812fef361d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cfg_export_periodic',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('interval_unit', sa.String(), nullable=False),
        sa.Column('interval_value', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_cfg_export_periodic')),
        sqlite_autoincrement=True,
    )
    op.create_table(
        't_export_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('export_id', sa.Integer(), nullable=False),
        sa.Column('export_from', sa.String(), nullable=True),
        sa.Column('export_to', sa.String(), nullable=True),
        sa.Column('export_rows', sa.Integer(), nullable=True),
        sa.Column('export_file_path', sa.String(), nullable=True),
        sa.Column('start_time', sa.String(), nullable=False),
        sa.Column('end_time', sa.String(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['export_id'], ['cfg_export.id'], name=op.f('fk_t_export_history_export_id_cfg_export'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_t_export_history')),
        sqlite_autoincrement=True,
    )

    op.execute('DELETE FROM cfg_export')
    op.execute('DELETE FROM cfg_export_detail')

    with op.batch_alter_table('cfg_export', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), server_default='ONCE', nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sub_folder', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_format', sa.String(), server_default='TSV', nullable=True))
        batch_op.add_column(sa.Column('filename_identifier', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('filename_format', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('split_file_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remove_exception', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('remove_outlier', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('remove_abnormal_count', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('duplicated_check_type', sa.String(), server_default='all', nullable=True))
        batch_op.add_column(sa.Column('duplicated_check', sa.String(), server_default='auto', nullable=True))
        batch_op.add_column(sa.Column('periodic_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('main_process_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('client_timezone', sa.String(), nullable=False, server_default='Asia/Tokyo'))
        batch_op.alter_column('export_from', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            'export_column_name_type', existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("'0'")
        )
        batch_op.drop_constraint('fk_cfg_export_process_id_cfg_process', type_='foreignkey')
        batch_op.create_unique_constraint('uq_cfg_export_periodic_id', ['periodic_id'])
        batch_op.create_foreign_key(
            batch_op.f('fk_cfg_export_periodic_id_cfg_export_periodic'), 'cfg_export_periodic', ['periodic_id'], ['id']
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_cfg_export_main_process_id_cfg_process'), 'cfg_process', ['main_process_id'], ['id']
        )
        batch_op.drop_column('process_id')
        batch_op.drop_column('file_type')
        batch_op.drop_column('export_frequency')

    with op.batch_alter_table('cfg_export_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_id', sa.Integer(), nullable=False))
        batch_op.alter_column('order', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_constraint('fk_cfg_export_detail_export_id_cfg_export', type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('fk_cfg_export_detail_export_id_cfg_export'),
            'cfg_export',
            ['export_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_cfg_export_detail_process_id_cfg_process'), 'cfg_process', ['process_id'], ['id']
        )

    with op.batch_alter_table('cfg_export_filter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f('fk_cfg_export_filter_process_id_cfg_process'),
            'cfg_process',
            ['process_id'],
            ['id'],
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_export_filter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cfg_export_filter_process_id_cfg_process'), type_='foreignkey')
        batch_op.drop_column('process_id')

    with op.batch_alter_table('cfg_export_detail', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cfg_export_detail_process_id_cfg_process'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cfg_export_detail_export_id_cfg_export'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cfg_export_detail_export_id_cfg_export', 'cfg_export', ['export_id'], ['id'])
        batch_op.alter_column('order', existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_column('process_id')

    with op.batch_alter_table('cfg_export', schema=None) as batch_op:
        batch_op.add_column(sa.Column('export_frequency', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('process_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_cfg_export_main_process_id_cfg_process'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cfg_export_periodic_id_cfg_export_periodic'), type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_cfg_export_process_id_cfg_process', 'cfg_process', ['process_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.alter_column(
            'export_column_name_type',
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("'0'"),
        )
        batch_op.alter_column('export_from', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column('main_process_id')
        batch_op.drop_column('periodic_id')
        batch_op.drop_column('duplicated_check')
        batch_op.drop_column('duplicated_check_type')
        batch_op.drop_column('remove_abnormal_count')
        batch_op.drop_column('remove_outlier')
        batch_op.drop_column('remove_exception')
        batch_op.drop_column('split_file_by')
        batch_op.drop_column('filename_format')
        batch_op.drop_column('filename_identifier')
        batch_op.drop_column('file_format')
        batch_op.drop_column('sub_folder')
        batch_op.drop_column('description')
        batch_op.drop_column('created_by')
        batch_op.drop_column('type')
        batch_op.drop_column('client_timezone')

    op.drop_table('t_export_history')
    op.drop_table('cfg_export_periodic')
    # ### end Alembic commands ###
