"""add is_physical_func_col

Revision ID: 1c812fef361d
Revises: 47bdbca65e5f
Create Date: 2026-04-28 15:39:05.688688

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1c812fef361d'
down_revision = '47bdbca65e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_process_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_physical_func_col', sa.Boolean(), nullable=True))

    # set default False for existing records
    op.execute('UPDATE cfg_process_column SET is_physical_func_col = FALSE WHERE is_physical_func_col IS NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_process_column', schema=None) as batch_op:
        batch_op.drop_column('is_physical_func_col')

    # ### end Alembic commands ###
