"""add encoding for csv

Revision ID: 47bdbca65e5f
Revises: 137d4295f66f
Create Date: 2026-04-27 17:59:40.238531

"""

import sqlalchemy as sa
from alembic import op

from ap.api.setting_module.services.show_latest_record import preview_csv_data
from ap.common.constants import DATA_TYPE_ESTIMATION_LIMIT, Encoding

# revision identifiers, used by Alembic.
revision = '47bdbca65e5f'
down_revision = '137d4295f66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_data_source_csv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encoding', sa.String(), nullable=True, server_default='utf-8'))
        batch_op.add_column(sa.Column('auto_encoding', sa.Boolean(), nullable=True, server_default='true'))

    conn = op.get_bind()
    get_ds_csv_sql = 'SELECT * FROM cfg_data_source_csv'
    data_sources = conn.execute(sa.text(get_ds_csv_sql)).fetchall()
    data_sources: list[dict] = [data_source._asdict() for data_source in data_sources]
    for data_source in data_sources:
        # default encoding
        encoding = Encoding.UTF8.code
        try:
            dic_preview = preview_csv_data(
                folder_url=data_source.directory,
                etl_func=data_source.etl_func,
                csv_delimiter=data_source.delimiter,
                limit=10,
                return_df=True,
                max_records=DATA_TYPE_ESTIMATION_LIMIT,
                file_name=None,
                is_file_checker=data_source.is_file_checker,
                n_rows=data_source.n_rows,
            )
            encoding = dic_preview.get('encoding')
        except Exception:
            pass

        data_source['encoding'] = encoding
        cols_str = ','.join(list(data_source.keys()))
        param_str = ','.join([f':{key}' for key in data_source.keys()])
        conn.execute(
            sa.text(f'INSERT OR REPLACE INTO cfg_data_source_csv ({cols_str}) VALUES ({param_str})').bindparams(
                *[sa.bindparam(key, value, literal_execute=True) for key, value in data_source.items()]
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_data_source_csv', schema=None) as batch_op:
        batch_op.drop_column('auto_encoding')
        batch_op.drop_column('encoding')

    # ### end Alembic commands ###
