"""add order column to cfg_export_detail

Revision ID: 354bd613ea30
Revises: a2e10a4ef7f4
Create Date: 2026-03-23 14:16:29.883576

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '354bd613ea30'
down_revision = 'a2e10a4ef7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_export_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default='1', nullable=True))

    # Update old data
    conn = op.get_bind()
    cfg_export_detail = sa.table(
        'cfg_export_detail',
        sa.column('export_id', sa.Integer),
        sa.column('process_column_id', sa.Integer),
        sa.column('order', sa.Integer),
    )

    # Get all export_id distinct
    export_ids = [row[0] for row in conn.execute(sa.select(cfg_export_detail.c.export_id).distinct())]

    # For each export_id, set the order in ascending order.
    for eid in export_ids:
        rows = conn.execute(
            sa.select(cfg_export_detail.c.process_column_id)
            .where(cfg_export_detail.c.export_id == eid)
            .order_by(cfg_export_detail.c.process_column_id)
        ).fetchall()

        for idx, row in enumerate(rows, start=1):
            conn.execute(
                cfg_export_detail.update()
                .where(cfg_export_detail.c.export_id == eid)
                .where(cfg_export_detail.c.process_column_id == row[0])
                .values(order=idx)
            )

    # 3. remove server_default
    with op.batch_alter_table('cfg_export_detail', schema=None) as batch_op:
        batch_op.alter_column('order', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfg_export_detail', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
