"""migrate job error to info

Revision ID: 137d4295f66f
Revises: 354bd613ea30
Create Date: 2026-03-26 09:18:25.788254

"""

import sqlalchemy as sa
from alembic import op

from ap.common.constants import JobStatus

# revision identifiers, used by Alembic.
revision = '137d4295f66f'
down_revision = '354bd613ea30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    failed_statuses = JobStatus.failed_statuses()

    info_value = (
        '{'
        '"type":\' || '
        '   CASE '
        "      WHEN job_type = 'CSV_IMPORT' THEN '\"CsvImportJobInfo\"' "
        "      WHEN job_type = 'DATA_EXPORT' THEN '\"DataExportJobInfo\"' "
        "      WHEN job_type = 'IMPORT_DATA' THEN '\"ImportDataJobInfo\"' "
        "      WHEN job_type = 'PULL_DATA' THEN '\"PullDataJobInfo\"' "
        "      WHEN job_type = 'FACTORY_IMPORT' THEN '\"FactoryImportJobInfo\"' "
        "      WHEN job_type = 'FACTORY_PAST_IMPORT' THEN '\"FactoryPastImportJobInfo\"' "
        "      WHEN job_type = 'UPDATE_TRANSACTION_TABLE' THEN '\"UpdateTransactionTableJobInfo\"' "
        "      WHEN job_type = 'WEB_API_IMPORT' THEN '\"WebAPIImportJobInfo\"' "
        "      WHEN job_type = 'BACKUP_DATABASE' THEN '\"BackupDatabaseJobInfo\"' "
        "      WHEN job_type = 'DEL_ALL_TRANSACTION_DATA' THEN '\"DelAllTransactionDataJobInfo\"' "
        "      WHEN job_type = 'DEL_TRANSACTION_DATA_BY_LIMIT' THEN '\"DelTransactionDataByLimit\"' "
        "      WHEN job_type = 'PROC_LINK_COUNT' THEN '\"GenProcLinkCountJobInfo\"' "
        "      WHEN job_type = 'USER_RESTORE_DATABASE' THEN '\"UserRestoreDatabaseJobInfo\"' "
        "      WHEN job_type = 'USER_BACKUP_DATABASE' THEN '\"UserBackupDatabaseJobInfo\"' "
        "      WHEN job_type = 'ZIP_LOG' THEN '\"ZipLogFilesJobInfo\"' "
        "      WHEN job_type = 'BULK_PROCESS_REGISTER' THEN '\"BulkProcessRegisterJobInfo\"' "
        "      WHEN job_type = 'COMPUTE_PROCESS_CACHE' THEN '\"ComputeProcessCacheJobInfo\"' "
        "      WHEN job_type = 'PERIODICALLY_COMPUTE_PROCESS_CACHE' THEN '\"ComputeProcessCacheJobInfo\"' "
        "      WHEN job_type = 'COMPUTE_ALL_PROCESS_IDS_CACHE' THEN '\"ComputeAllProcessIdsCacheJobInfo\"' "
        "      WHEN job_type = 'PERIODICALLY_COMPUTE_ALL_PROCESSES_CACHE' THEN '\"ComputeAllProcessIdsCacheJobInfo\"' "
        "      WHEN job_type = 'COMPUTE_ALL_TRACES_CACHE' THEN '\"ComputeAllTracesCacheJobInfo\"' "
        "      WHEN job_type = 'PERIODICALLY_COMPUTE_ALL_TRACES_CACHE' THEN '\"ComputeAllTracesCacheJobInfo\"' "
        "      WHEN job_type = 'VACUUM_DB' THEN '\"VacuumDbJobInfo\"' "
        "      WHEN job_type = 'BACKUP_JOB_HISTORY' THEN '\"BackupJobHistoryJobInfo\"' "
        "      WHEN job_type = 'CLEANUP_JOB_HISTORY' THEN '\"CleanupJobHistoryJobInfo\"' "
        "      ELSE 'None' "
        "   END || ',"
        '"messages":[{'
        '"level":"error",'
        "\"content\":\"' || replace(replace(error_msg, '(208, b\"', ''), '\\n\")', '') || '\","
        '"created_at":"\' || updated_at || \'"'
        '}]'
        '}'
    )
    conn.execute(
        sa.text(
            f'UPDATE t_job_management '
            f"SET info = '{info_value}' "
            f'WHERE '
            f'error_msg IS NOT NULL AND '
            f'status in ({",".join([f"'{status}'" for status in failed_statuses])})'
        ),
    )

    # Remove old jobs have job type 'RESTRUCTURE_INDEXES'
    # because it does not exist in system after upgrading to DuckDB
    conn.execute(
        sa.text("DELETE FROM t_job_management WHERE job_type = 'RESTRUCTURE_INDEXES' "),
    )

    with op.batch_alter_table('t_job_management', schema=None) as batch_op:
        batch_op.drop_column('error_msg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_job_management', schema=None) as batch_op:
        batch_op.add_column('error_msg')
    # ### end Alembic commands ###
