"""job_management_add_info

Revision ID: c4272af5047c
Revises: f5dbe7fdfab2
Create Date: 2026-01-12 16:13:39.441864

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c4272af5047c'
down_revision = 'f5dbe7fdfab2'
branch_labels = None
depends_on = None


def upgrade():
    from ap.setting_module.models import SqlAlchemyJobInfoType

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_job_management', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', SqlAlchemyJobInfoType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_job_management', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
