"""job_management

Revision ID: 815abcc4f720
Revises: f9194c169486
Create Date: 2019-12-10 13:44:59.681629

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '815abcc4f720'
down_revision = '1eb4aa1d0b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        't_job_management',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('job_type', sa.Enum('CSV_IMPORT', 'GEN_GLOBAL', name='jobtype'), nullable=True),
        sa.Column('db_code', sa.Text(), nullable=True),
        sa.Column('db_name', sa.Text(), nullable=True),
        sa.Column('process_id', sa.Integer(), nullable=True),
        sa.Column('process_name', sa.Text(), nullable=True),
        sa.Column('start_tm', sa.Text(), nullable=True),
        sa.Column('end_tm', sa.Text(), nullable=True),
        sa.Column(
            'status',
            sa.Enum('DONE', 'FAILED', 'PROCESSING', 'PENDING', 'KILLED', name='jobstatus'),
            nullable=True,
        ),
        sa.Column('done_percent', sa.Float(), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        't_csv_import',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('job_id', sa.Integer(), nullable=True),
        sa.Column('process_id', sa.Integer(), nullable=True),
        sa.Column('file_name', sa.Text(), nullable=True),
        sa.Column('start_tm', sa.Text(), nullable=True),
        sa.Column('end_tm', sa.Text(), nullable=True),
        sa.Column('imported_row', sa.Integer(), nullable=True),
        sa.Column(
            'status',
            sa.Enum('DONE', 'FAILED', 'PROCESSING', 'PENDING', 'KILLED', name='jobstatus'),
            nullable=True,
        ),
        sa.Column('error_msg', sa.Text(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['job_id'],
            ['t_job_management.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        't_gen_global_id',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('job_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['job_id'],
            ['t_job_management.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_gen_global_id')
    op.drop_table('t_csv_import')
    op.drop_table('t_job_management')
    # ### end Alembic commands ###
