"""Add datetime_format column into cfg_processs table

Revision ID: 8600fce518a6
Revises: 3e055e1a5054
Create Date: 2024-06-04 09:23:09.648391

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8600fce518a6'
down_revision = '3e055e1a5054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_process', sa.Column('datetime_format', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_process', 'datetime_format')
    # ### end Alembic commands ###
