"""add indexs

Revision ID: c8acd55c0872
Revises: 1eb4aa1d0b6a
Create Date: 2019-12-10 15:06:23.817726

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c8acd55c0872'
down_revision = '1eb4aa1d0b6a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()['upgrade_%s' % engine_name]()


def downgrade(engine_name):
    globals()['downgrade_%s' % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_m_process_period_id'), 'm_process', ['period_id'], unique=False)
    op.create_index(op.f('ix_m_sensor_process_id'), 'm_sensor', ['process_id'], unique=False)
    op.create_index(op.f('ix_t_cycle_global_id'), 't_cycle', ['global_id'], unique=False)
    op.create_index(op.f('ix_t_cycle_process_id'), 't_cycle', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_cycle_process_id'), table_name='t_cycle')
    op.drop_index(op.f('ix_t_cycle_global_id'), table_name='t_cycle')
    op.drop_index(op.f('ix_m_sensor_process_id'), table_name='m_sensor')
    op.drop_index(op.f('ix_m_process_period_id'), table_name='m_process')
    # ### end Alembic commands ###


def upgrade_app_metadata():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.create_index(op.f('ix_t_csv_import_job_id'), 't_csv_import', ['job_id'], unique=False)
    op.create_index(op.f('ix_t_gen_global_id_job_id'), 't_gen_global_id', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_app_metadata():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_gen_global_id_job_id'), table_name='t_gen_global_id')
    op.drop_index(op.f('ix_t_csv_import_job_id'), table_name='t_csv_import')
    op.create_table(
        'apscheduler_jobs',
        sa.Column('id', sa.VARCHAR(length=191), nullable=False),
        sa.Column('next_run_time', sa.FLOAT(), nullable=True),
        sa.Column('job_state', sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
