from pydantic import BaseModel, computed_field, field_validator

from ap.common.constants import BaseEnum, JobStatus, JobType


class JobStatusFilter(BaseEnum):
    """Job status filter type enumeration.

    Defines the types of status filter used.

    Attributes:
        PROCESSING: For processing status.
        DONE: For done status.
        ERROR: For all error related status.
        OTHERS: All others status.

    Generated by Duo
    """

    PROCESSING = 0
    DONE = 1
    ERROR = 2
    OTHERS = 3


class JobTypeFilter(BaseEnum):
    """Job filter type enumeration.

    Defines the types of job filter used.

    Attributes:
        IMPORT: For all import job.
        PAST_IMPORT: For all past import job.
        DATA_LINK: For all data link related job.
        OTHERS: All others job.

    Generated by Duo
    """

    IMPORT = 0
    PAST_IMPORT = 1
    DATA_LINK = 2
    OTHERS = 3


class SearchParamsDTO(BaseModel):
    """Data Transfer Object for job search and filtering parameters.

    This DTO handles pagination, filtering, and sorting of background jobs.
    It provides automatic conversion of filter values to their corresponding
    job statuses and types using validators.

    Attributes:
        offset (int): The number of records to skip for pagination. Defaults to 0.
        search (str | None): Search query string to filter jobs by name or content. Defaults to None.
        sort (str | None): Field name to sort results by. Defaults to None.
        order (str | None): Sort order direction ('asc' or 'desc'). Defaults to None.
        show_past_import_job (bool | None): Whether to include past import jobs in results. Defaults to None.
        error_page (bool): Flag indicating if filtering for error/failed jobs only. Defaults to False.
        sort_by (str | None): Alternative sort field specification. Defaults to None.
        limit (int): Maximum number of records to return per page. Defaults to 50.
        statuses (list[str] | None): List of job statuses to filter by. Accepts status names or filter groups
            (PROCESSING, DONE, ERROR, OTHERS). Automatically converted to actual job statuses. Defaults to [].
        job_types (list[str] | None): List of job types to filter by. Accepts type names or filter groups
            (IMPORT, PAST_IMPORT, DATA_LINK, OTHERS). Automatically converted to actual job types. Defaults to [].
        ignore_job_types (list[str]): List of job types to exclude from results. Defaults to [].

    Properties:
        page (int): Computed property that calculates the current page number based on offset and limit.
    """

    offset: int = 0
    search: str | None = None
    sort: str | None = None
    order: str | None = None
    show_past_import_job: bool | None = None
    error_page: bool = False
    sort_by: str | None = None
    limit: int = 50
    statuses: list[str] | None = []
    job_types: list[str] | None = []
    ignore_job_types: list[str] = []

    @computed_field
    @property
    def page(self) -> int:
        return (self.offset // self.limit) + 1

    @field_validator('statuses', mode='before')
    @classmethod
    def convert_statuses(cls, v):
        if isinstance(v, str):
            v = v.split(',')

        statuses = []
        for status in v:
            match status:
                case JobStatusFilter.OTHERS.name:
                    statuses.extend(JobStatus.others_statuses())
                case JobStatusFilter.ERROR.name:
                    statuses.extend(JobStatus.failed_statuses())
                case _:
                    statuses.append(status)

        return statuses

    @field_validator('job_types', mode='before')
    @classmethod
    def convert_job_types(cls, v):
        if isinstance(v, str):
            v = v.split(',')

        types = []
        for job_type in v:
            match job_type:
                case JobTypeFilter.IMPORT.name:
                    types.extend(JobType.jobs_import())
                case JobTypeFilter.PAST_IMPORT.name:
                    types.extend(JobType.jobs_past_import())
                case JobTypeFilter.DATA_LINK.name:
                    types.extend(JobType.jobs_data_link())
                case JobTypeFilter.OTHERS.name:
                    types.extend(JobType.job_others())
                case _:
                    types.append(job_type)

        return types


class ExportConfigPeriodicDTO(BaseModel):
    """
    Data Transfer Object for periodic export configuration.

    Defines the scheduling parameters for periodic export operations,
    including interval settings and trigger times.

    Attributes:
        client_timezone: Timezone identifier for the client (e.g., 'UTC', 'America/New_York')
        interval_unit: Time unit for export frequency ('day' or 'hour')
        interval_value: Numeric value for the interval (e.g., 2 for every 2 days/hours)
        start_time: datetime

    Raises:
        ValueError: If validation fails for any field or model-level constraints

    Example:
        >>> config = ExportConfigPeriodicDTO(
        ...     client_timezone='UTC', interval_unit='day', interval_value=1, start_time='2026-05-14 07:00'
        ... )
    """

    client_timezone: str
    interval_unit: str
    interval_value: int
    start_time: str


class PaginationParamsDTO(BaseModel):
    """Data Transfer Object for pagination parameters."""

    page: int
    limit: int
