from __future__ import annotations

import logging
from collections.abc import Mapping
from datetime import datetime, timedelta
from typing import TYPE_CHECKING, Any, Final, Optional, TypedDict, override

import marshmallow
import pydantic
from marshmallow import fields, post_load, pre_dump, pre_load
from marshmallow_sqlalchemy.fields import Nested
from pydantic.alias_generators import to_camel

from ap import ma
from ap.common.constants import (
    SQL_DAYS_AGO,
    DataColumnType,
    DataType,
    DBType,
    ProcessStatus,
)
from ap.common.cryptography_utils import encrypt
from ap.common.services.jp_to_romaji_utils import to_romaji
from ap.conversion_formula import JudgeFormula, conversion_formula
from ap.setting_module.models import (
    CfgCsvColumn,
    CfgDataSource,
    CfgDataSourceCSV,
    CfgDataSourceDB,
    CfgDataSourceWeb,
    CfgExport,
    CfgExportDetail,
    CfgExportFilter,
    CfgFilter,
    CfgFilterDetail,
    CfgLabel,
    CfgOption,
    CfgProcess,
    CfgProcessColumn,
    CfgProcessFunctionColumn,
    CfgTrace,
    CfgTraceKey,
    CfgUserSetting,
    CfgVisualization,
    JobManagement,
)

EXCLUDE_COLS = ('updated_at', 'created_at')

logger = logging.getLogger(__name__)


class AnyAsBool(fields.Field):
    """Field that serializes string to boolean.

    This custom Marshmallow field converts any value to a boolean representation.

    Methods:
        _deserialize: Converts the input value to a boolean.

    Generated by Duo
    """

    # since _deserialize is an internal method of Field
    # do not overwrite this method in child class
    # use instead:
    #     def deserialize(value):
    #           return bool(value)
    @override
    def _deserialize(
        self,
        value: Any,
        attr: Optional[str],
        data: Optional[Mapping[str, Any]],
        **kwargs: Mapping[str, Any],
    ):
        return bool(value)


class ContextSchemaDict(TypedDict):
    """Type definition for schema context dictionary.

    TypedDict used to provide type hints for context parameters in schema classes.
    Controls behavior of schema serialization, particularly for graph display.

    Attributes:
        show_graph: Boolean flag to control graph display behavior. When True,
            modifies data type conversion and column type handling for visualization.

    Usage:
        Used in BaseSchema and ShowGraphSchema to provide type hints for context parameter.
        Example: ShowGraphSchema(context=ContextSchemaDict(show_graph=True))

    Generated by Duo
    """

    show_graph: bool


class BaseSchema(ma.SQLAlchemyAutoSchema):
    """Base schema with shared definition"""

    # typehint for dictionary
    if TYPE_CHECKING:
        context: ContextSchemaDict

    class Meta:
        """Base meta with shared definition"""

        # allow to include relationships from children models
        include_relationships = True

        # allow to show foreign keys
        include_fk = True

        # load into sqlalchemy models
        load_instance = True

        # allow objects non-existed in database
        transient = True

        # allow missing fields to be parsed as None
        partial = True

        # exclude every unknown fields
        unknown = marshmallow.EXCLUDE
        exclude = EXCLUDE_COLS


class CsvColumnSchema(BaseSchema):
    """Schema for CSV column configuration.

    Marshmallow schema for serializing and deserializing CfgCsvColumn model instances.

    Attributes:
        id: Integer field for the CSV column ID, can be None.
        data_source_id: Integer field for the associated data source ID, can be None.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgCsvColumn

    id = fields.Integer(allow_none=True)
    data_source_id = fields.Integer(allow_none=True)


class DataSourceDbSchema(BaseSchema):
    """Schema for database data source configuration.

    Marshmallow schema for serializing and deserializing CfgDataSourceDB model instances.
    Handles password encryption, date validation, and database connection details.

    Attributes:
        id: Integer field for the data source ID, can be None.

    Methods:
        make_instance: Post-load hook to validate dates and encrypt sensitive fields.
        _is_valid_date: Static method to validate date strings against a format.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgDataSourceDB

    id = fields.Integer(allow_none=True)

    @post_load
    def make_instance(self, data, **_kwargs: Mapping[Any, Any]):
        """Change some data after validation
        See more: <https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/502#issuecomment-1484628041>
        """
        model = super().make_instance(data)

        pull_from_req = model.pull_from
        if pull_from_req is not None:
            if self._is_valid_date(pull_from_req, '%Y-%m-%d'):
                dt = datetime.strptime(pull_from_req, '%Y-%m-%d')
                model.pull_from = datetime(dt.year, dt.month, dt.day).strftime('%Y-%m-%dT00:00:00.000000Z')
            elif not self._is_valid_date(pull_from_req, '%Y-%m-%dT00:00:00.000000Z'):
                logger.error(f'pull_from value {pull_from_req} is incorrect format')
                dt = datetime.now().date() - timedelta(days=SQL_DAYS_AGO)  # Default pull_from value is 30 days ago
                model.pull_from = datetime(dt.year, dt.month, dt.day).strftime('%Y-%m-%dT00:00:00.000000Z')

        if not model.password:
            model.password = None
        if not model.snowflake_access_token:
            model.snowflake_access_token = None
        if not model.snowflake_private_key_file_pwd:
            model.snowflake_private_key_file_pwd = None

        model.hashed = True
        # avoid blank string
        model.port = model.port or None
        model.schema = model.schema or None

        if model.id is not None:
            db: CfgDataSourceDB = CfgDataSourceDB.get_by_id(model.id)
            # db exists, use existing password in database if user doesn't specify
            # or use the new password provided by user
            if model.password is None and db.password:
                model.password = db.password
            else:
                model.password = encrypt(model.password)

            if model.snowflake_access_token is None and db.snowflake_access_token:
                model.snowflake_access_token = db.snowflake_access_token
            else:
                model.snowflake_access_token = encrypt(model.snowflake_access_token)

            if model.snowflake_private_key_file_pwd is None and db.snowflake_private_key_file_pwd:
                model.snowflake_private_key_file_pwd = db.snowflake_private_key_file_pwd
            else:
                model.snowflake_private_key_file_pwd = encrypt(model.snowflake_private_key_file_pwd)
        else:
            # new db, use provided password
            model.password = encrypt(model.password)
            model.snowflake_access_token = encrypt(model.snowflake_access_token)
            model.snowflake_private_key_file_pwd = encrypt(model.snowflake_private_key_file_pwd)

        return model

    @staticmethod
    def _is_valid_date(date_string: str, date_format: str) -> bool:
        try:
            datetime.strptime(date_string, date_format)  # str parse to time
            return True
        except ValueError:
            return False


class DataSourceDbPublicSchema(DataSourceDbSchema):
    """Public schema for database data source configuration.

    Extends DataSourceDbSchema but excludes sensitive fields like passwords
    and authentication tokens for public API responses.

    Generated by Duo
    """

    class Meta(DataSourceDbSchema.Meta):
        exclude = (
            *DataSourceDbSchema.Meta.exclude,
            CfgDataSourceDB.password.name,
            CfgDataSourceDB.snowflake_access_token.name,
            CfgDataSourceDB.snowflake_private_key_file_pwd.name,
        )


class DataSourceWebSchema(BaseSchema):
    """Schema for web API data source configuration.

    Marshmallow schema for serializing and deserializing CfgDataSourceWeb model instances.
    Handles password encryption for web API authentication.

    Attributes:
        id: Integer field for the data source ID, can be None.
        username: String field for authentication username, can be None.
        password: String field for authentication password, can be None.
        authentication_type: String field for authentication type, required.

    Methods:
        make_instance: Post-load hook to encrypt password fields.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgDataSourceWeb

    id = fields.Integer(allow_none=True)
    username = fields.String(allow_none=True)
    password = fields.String(allow_none=True)
    authentication_type = fields.String(allow_none=False)

    @post_load
    def make_instance(self, data, **_kwargs: Mapping[Any, Any]):
        """Change some data after validation
        See more: <https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/502#issuecomment-1484628041>
        """
        model = super().make_instance(data)

        # TODO: this is duplicated with DataSourceDbSchema, consider refactoring
        if not model.password:
            model.password = None

        if model.id is not None:
            web: CfgDataSourceWeb = CfgDataSourceWeb.get_by_id(model.id)
            # web exists, use existing password in database if user doesn't specify
            # or use the new password provided by user
            if model.password is None and web.password:
                model.password = web.password
            else:
                model.password = encrypt(model.password)
        else:
            # new web, use provided password
            model.password = encrypt(model.password)

        return model


class DataSourceWebPublicSchema(DataSourceWebSchema):
    """Public schema for web API data source configuration.

    Extends DataSourceWebSchema but excludes the password field for public API responses.

    Generated by Duo
    """

    class Meta(DataSourceWebSchema.Meta):
        exclude = (*DataSourceWebSchema.Meta.exclude, CfgDataSourceWeb.password.name)


class SWProcessSchema(BaseSchema):
    """
    schema for software workshop model
    It seems like a Process Schema, but with some columns excluded,
    while certain required columns are defined for validation from the form.
    """

    class Meta(BaseSchema.Meta):
        model = CfgProcess
        exclude = (
            'visualizations',
            'traces',
            'filters',
            'data_source',
            'unused_columns',
            *EXCLUDE_COLS,  # re-open the params if used
        )

    columns = fields.Nested('ProcessColumnSchema', many=True)
    id = fields.Integer(allow_none=True)
    # if create process from sw modal, child_equip_ids is required
    process_factid = fields.String(allow_none=False, required=True)
    master_type = fields.String(allow_none=False, required=True)
    status = fields.Integer(allow_none=True, default=ProcessStatus.REGISTERED.value, required=False)


class DataSourceCsvSchema(BaseSchema):
    """Schema for CSV data source configuration.

    Marshmallow schema for serializing and deserializing CfgDataSourceCSV model instances.

    Attributes:
        id: Integer field for the data source ID, can be None.
        csv_columns: Nested field for CSV column configurations.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgDataSourceCSV

    id = fields.Integer(allow_none=True)

    csv_columns = fields.Nested('CsvColumnSchema', many=True)


class DataSourceSchema(BaseSchema):
    """Schema for generic data source configuration.

    Marshmallow schema for serializing and deserializing CfgDataSource model instances.
    Supports CSV, database, and web API data sources.

    Attributes:
        id: Integer field for the data source ID, can be None.
        csv_detail: Nested field for CSV-specific configuration, can be None.
        db_detail: Nested field for database-specific configuration, can be None.
        web_detail: Nested field for web API-specific configuration, can be None.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgDataSource
        exclude = (*BaseSchema.Meta.exclude, 'order')

    id = fields.Integer(allow_none=True)

    csv_detail = fields.Nested('DataSourceCsvSchema', allow_none=True)
    db_detail = fields.Nested('DataSourceDbSchema', allow_none=True)
    web_detail = fields.Nested('DataSourceWebSchema', allow_none=True)


class DataSourcePublicSchema(DataSourceSchema):
    """Public schema for generic data source configuration.

    Extends DataSourceSchema but uses public schemas for nested fields to exclude
    sensitive information like passwords.

    Generated by Duo
    """

    db_detail = fields.Nested('DataSourceDbPublicSchema', allow_none=True)
    web_detail = fields.Nested('DataSourceWebSchema', allow_none=True)


class FilterDetailSchema(BaseSchema):
    """Schema for filter detail configuration.

    Marshmallow schema for serializing and deserializing CfgFilterDetail model instances.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgFilterDetail


class ProcessFunctionColumnSchema(BaseSchema):
    """Schema for process function column configuration.

    Marshmallow schema for serializing and deserializing CfgProcessFunctionColumn model instances.

    Attributes:
        id: Integer field for the function column ID, can be None.
        is_me_function: Boolean field indicating if this is a ME function (dump only).

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgProcessFunctionColumn

    id = fields.Integer(allow_none=True)
    # hybrid properties go here
    is_me_function = fields.Boolean(dump_only=True)


class ProcessColumnSchema(BaseSchema):
    """Schema for process column configuration.

    Marshmallow schema for serializing and deserializing CfgProcessColumn model instances.
    Handles column data types, transformations, and various column properties.

    Attributes:
        id: Integer field for the column ID, can be None.
        parent_column: Nested field for parent column reference.
        function_details: Nested field for function configurations.
        origin_raw_data_type: String field for original raw data type.
        process_id: Integer field for the associated process ID.
        Various boolean fields for column properties (is_serial_no, is_get_date, etc.).
        Multiple hybrid properties for computed column attributes.

    Methods:
        make_instance: Post-load hook to transform column names and data types.
        inherit_parent_properties: Pre-load hook to inherit properties from parent column.
        convert_data_type: Pre-dump hook to convert data types for display.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgProcessColumn

    id = fields.Integer(allow_none=True)

    parent_column = fields.Nested('ProcessColumnSchema', allow_none=True)
    # This field to sever store function config of this column
    function_details = fields.Nested('ProcessFunctionColumnSchema', many=True, required=False)

    # This field to sever store previous data type and show it on modal fail convert data
    origin_raw_data_type = fields.String(allow_none=True)

    # if new process
    process_id = fields.Integer(allow_none=True)

    # custom serialize to serialize empty string and others to boolean values
    is_serial_no = AnyAsBool()
    is_get_date = AnyAsBool()
    is_auto_increment = AnyAsBool()
    is_dummy_datetime = AnyAsBool()
    is_file_name = AnyAsBool()

    # hybrid properties go here
    is_main_serial = fields.Boolean(dump_only=True)
    is_function_column = fields.Boolean(dump_only=True)
    is_normal_column = fields.Boolean(dump_only=True)
    is_main_serial_function_column = fields.Boolean(dump_only=True)
    is_transaction_column = fields.Boolean(dump_only=True)
    shown_name = fields.String(dump_only=True)
    is_linking_column = fields.Boolean(dump_only=True)
    bridge_column_name = fields.String(dump_only=True)
    is_category = fields.Boolean(dump_only=True)
    is_int_category = fields.Boolean(dump_only=True)
    is_judge = fields.Boolean(dump_only=True)
    is_me_function_column = fields.Boolean(dump_only=True)
    is_chain_of_me_functions = fields.Boolean(dump_only=True)
    # judge data display for front-end
    judge_positive_value = fields.String(dump_only=True)
    judge_positive_display = fields.String(dump_only=True)
    judge_negative_display = fields.String(dump_only=True)

    @post_load
    def make_instance(self, data, **_kwargs: Mapping[Any, Any]):
        """Change some data after validation
        See more: <https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/502#issuecomment-1484628041>
        """
        model = super().make_instance(data)

        # transform english name
        if not model.name_en:
            model.name_en = to_romaji(model.column_name)

        # transform data type
        if model.data_type in (DataType.EU_REAL_SEP.name, DataType.REAL_SEP.name):
            model.data_type = DataType.REAL.name
        elif model.data_type in (DataType.EU_INTEGER_SEP.name, DataType.INTEGER_SEP.name):
            model.data_type = DataType.INTEGER.name

        return model

    @pre_load
    def inherit_parent_properties(self, data, **_kwargs: Mapping[Any, Any]):
        parent_id = data.get('parent_id')
        if parent_id is not None:
            parent_column = CfgProcessColumn.get_by_id(parent_id)
            for column_property in [
                CfgProcessColumn.data_type.name,
                CfgProcessColumn.column_type.name,
                CfgProcessColumn.raw_data_type.name,
                CfgProcessColumn.is_serial_no.name,
                CfgProcessColumn.is_get_date.name,
                CfgProcessColumn.is_auto_increment.name,
                CfgProcessColumn.is_file_name.name,
                CfgProcessColumn.unit.name,
                CfgProcessColumn.formula.name,
            ]:
                data[column_property] = getattr(parent_column, column_property)
        return data

    @pre_dump
    def convert_data_type(self, data: CfgProcessColumn, **_kwargs: Mapping[Any, Any]):
        data = data.clone()
        show_graph = self.context.get('show_graph', False)
        # convert datatype for show graph
        formula = conversion_formula(formula=data.formula, col_type=data.column_type, data_type=data.data_type)
        match formula:
            case JudgeFormula(positive=positive, positive_display=positive_display, negative_display=negative_display):
                data.judge_positive_value = positive
                data.judge_positive_display = positive_display
                data.judge_negative_display = negative_display

        if show_graph:
            # modify data type based on function columns
            if data.function_details and data.function_details[-1].return_type:
                function_return_type = data.function_details[-1].return_type
                data.data_type = function_return_type

            if data.is_boolean:
                data.column_type = DataColumnType.BOOLEAN.value

            # need to change again, make sure date, time, boolean be converted to text
            if data.data_type in [
                DataType.DATE.name,
                DataType.TIME.name,
                DataType.BOOLEAN.name,
            ]:
                data.data_type = DataType.TEXT.name

            # change data type column from `boolean` or `category` to Int(Cat) (PO requirements)
            if data.data_type == DataType.CATEGORY.name:
                data.data_type = DataType.INTEGER.name
                data.column_type = DataColumnType.INT_CATE.value

        return data


class FilterSchema(BaseSchema):
    """Schema for filter configuration.

    Marshmallow schema for serializing and deserializing CfgFilter model instances.

    Attributes:
        filter_details: Nested field for filter detail configurations.
        column: Nested field for the associated process column.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgFilter

    filter_details = fields.Nested('FilterDetailSchema', many=True)
    column = fields.Nested('ProcessColumnSchema', allow_none=True)


class VisualizationSchema(BaseSchema):
    """Schema for visualization configuration.

    Marshmallow schema for serializing and deserializing CfgVisualization model instances.

    Attributes:
        id: Integer field for the visualization ID, can be None.
        control_column: Nested field for the control column.
        filter_column: Nested field for the filter column, can be None.
        filter_detail: Nested field for filter details, can be None.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgVisualization

    id = fields.Integer(allow_none=True)

    control_column = fields.Nested('ProcessColumnSchema')
    filter_column = fields.Nested('ProcessColumnSchema', allow_none=True)
    filter_detail = fields.Nested('FilterDetailSchema', allow_none=True)


class TraceKeySchema(BaseSchema):
    """Schema for trace key configuration.

    Marshmallow schema for serializing and deserializing CfgTraceKey model instances.

    Attributes:
        self_column: Nested field for the source column.
        target_column: Nested field for the target column.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgTraceKey

    self_column = fields.Nested('ProcessColumnSchema')
    target_column = fields.Nested('ProcessColumnSchema')


class TraceSchema(BaseSchema):
    """Schema for trace configuration.

    Marshmallow schema for serializing and deserializing CfgTrace model instances.

    Attributes:
        trace_keys: Nested field for trace key configurations.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgTrace

    trace_keys = fields.Nested('TraceKeySchema', many=True)


class ProcessSchema(BaseSchema):
    """Main schema for process configuration.

    Marshmallow schema for serializing and deserializing CfgProcess model instances.
    Used in API controllers for process registration and updates, polling frequency services,
    and register_from_file services. Serves as parent class for ProcessPublicSchema,
    ProcessTraceSchema, and ShowGraphSchema.

    Attributes:
        id: Integer field for process ID, can be None. Allows creating new processes.
        columns: Nested ProcessColumnSchema for process column configurations.
        traces: Nested TraceSchema for trace configurations defining process relationships.
        filters: Nested FilterSchema for filter configurations.
        data_source: Nested DataSourceSchema for data source configuration. Uses lambda
            to limit exposed fields to id, name, type, csv_detail, and db_detail.
        order: Integer field for process order, can be None. Calculated after loading.
        shown_name: String field for displayed name (dump only, hybrid property from CfgProcess).
        is_check_datetime_format: Boolean field for datetime format checking
            (dump only, hybrid property from CfgProcess).

    Meta:
        model: CfgProcess
        exclude: Excludes visualizations and timestamp fields (updated_at, created_at).

    Usage:
        - API controllers: Process registration and updates
        - Polling frequency services: Process data serialization
        - Register from file services: Process configuration loading
        - Parent class for specialized process schemas

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgProcess
        exclude = ('visualizations', *EXCLUDE_COLS)  # re-open the params if used

    # allow to create new process
    id = fields.Integer(allow_none=True)

    columns = fields.Nested('ProcessColumnSchema', many=True)
    traces = fields.Nested('TraceSchema', many=True)
    filters = fields.Nested('FilterSchema', many=True)
    labels = fields.Nested('LabelSchema', many=True)

    # TODO(khanhdq): can we omit the lambda here? it is ugly
    data_source = fields.Nested(lambda: DataSourceSchema(only=('id', 'name', 'type', 'csv_detail', 'db_detail')))

    # `order` field will be calculated after loading, need to mark it here
    order = fields.Integer(required=False, allow_none=True)

    # hybrid properties go here
    shown_name = fields.String(dump_only=True)
    is_check_datetime_format = fields.Boolean(dump_only=True)


class ProcessPublicSchema(ProcessSchema):
    """Public schema for process configuration.

    Extends ProcessSchema but uses public data source schema to exclude sensitive information.

    Generated by Duo
    """

    data_source = fields.Nested('DataSourcePublicSchema')


class ProcessFullSchema(BaseSchema):
    """Full schema for process configuration with all relationships.

    Marshmallow schema for serializing and deserializing CfgProcess model instances
    including all nested relationships (columns, traces, filters, visualizations).

    Attributes:
        id: Integer field for the process ID, can be None.
        columns: Nested field for process columns.
        traces: Nested field for trace configurations.
        filters: Nested field for filter configurations.
        data_source: Nested field for data source configuration.
        visualizations: Nested field for visualization configurations.
        shown_name: String field for the displayed name (dump only).

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgProcess

    id = fields.Integer(required=False, allow_none=True)
    columns = Nested(ProcessColumnSchema, many=True)
    traces = Nested(TraceSchema, many=True)
    filters = Nested(FilterSchema, many=True)
    data_source = Nested(DataSourceSchema)
    visualizations = Nested(VisualizationSchema, many=True)
    # hybrid properties go here
    shown_name = fields.String(dump_only=True)


class ProcessVisualizationSchema(BaseSchema):
    """Schema for process visualization configuration.

    Marshmallow schema for serializing CfgProcess with visualization and filter details,
    excluding data source and trace information.

    Attributes:
        columns: Nested field for process columns.
        visualizations: Nested field for visualization configurations.
        filters: Nested field for filter configurations.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgProcess
        exclude = ('data_source', 'traces', *BaseSchema.Meta.exclude)

    columns = fields.Nested('ProcessColumnSchema', many=True)
    visualizations = fields.Nested('VisualizationSchema', many=True)
    filters = fields.Nested('FilterSchema', many=True)


class ProcessTraceSchema(ProcessSchema):
    """Schema for process trace configuration.

    Extends ProcessSchema but excludes visualization and filter information,
    focusing on trace relationships.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgProcess
        exclude = ('visualizations', 'filters', *EXCLUDE_COLS)  # re-open the params if used


class ProcessOnlySchema(BaseSchema):
    """Schema for minimal process information.

    Marshmallow schema for serializing CfgProcess with only basic process information,
    excluding all nested relationships.

    Attributes:
        shown_name: String field for the displayed name.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgProcess
        exclude = ('visualizations', 'columns', 'traces', 'filters', *EXCLUDE_COLS)  # re-open the params if used

    shown_name = fields.String(required=False, allow_none=False)
    labels = fields.Nested('LabelSchema', many=True)


class CfgUserSettingSchema(BaseSchema):
    """Schema for user setting configuration.

    Marshmallow schema for serializing and deserializing CfgUserSetting model instances.

    Attributes:
        id: Integer field for the setting ID, can be None.
        function: String field for the function name, can be None.
        hashed_owner: String field for the hashed owner identifier, required.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgUserSetting
        exclude: Final[list[str]] = ['created_at']

    id = fields.Integer(required=False, allow_none=True)
    function = fields.String(required=False, allow_none=True)
    hashed_owner = fields.String(required=True, allow_none=False)


class ShowGraphSchema(ProcessSchema):
    """Schema for show graph configuration.

    Extends ProcessSchema with full visualization details for graph display,
    excluding comment and order fields.

    Attributes:
        id: Integer field for the process ID, can be None.
        columns: Nested field for process columns.
        filters: Nested field for filter configurations.
        data_source: Nested field for data source configuration.
        visualizations: Nested field for visualization configurations.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgProcess
        exclude = ('comment', 'order', *EXCLUDE_COLS)

    id = fields.Integer(required=False, allow_none=True)
    columns = Nested(ProcessColumnSchema, many=True)
    filters = Nested(FilterSchema, many=True)
    data_source = Nested(DataSourceSchema)
    visualizations = Nested(VisualizationSchema, many=True)


class CfgOptionSchema(BaseSchema):
    """Schema for configuration option.

    Marshmallow schema for serializing and deserializing CfgOption model instances.

    Methods:
        make_obj: Post-load hook to create CfgOption instance.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgOption
        # TODO: why we don't use default exclude here?
        exclude: Final[list[str]] = []

    @post_load
    def make_obj(self, data, **_kwargs: Mapping[Any, Any]):
        return CfgOption(**data)


class ProcessColumnExternalAPISchema(BaseSchema):
    """Schema for process column external API representation.

    Marshmallow schema for serializing process column data for external API consumption.

    Attributes:
        id: Integer field for the column ID, required.
        shown_name: String field for the displayed name, required.
        data_type: String field for the data type, required.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        load_instance = False
        exclude: Final[list[str]] = []

    id = fields.Integer(required=True)
    shown_name = fields.String(required=True, data_key='name')
    data_type = fields.String(required=True)


class JobManagementSchema(BaseSchema):
    """Schema for job management configuration.

    Marshmallow schema for serializing and deserializing JobManagement model instances.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = JobManagement


class BasePydanticModel(pydantic.BaseModel):
    """using pydantic.BaseModel to have a better autocompletion"""

    model_config = pydantic.ConfigDict(from_attributes=True)


class AutolinkInSchema(BasePydanticModel):
    """Pydantic schema for autolink input data.

    Attributes:
        process_ids: List of process IDs for autolink operation.

    Generated by Duo
    """

    model_config = pydantic.ConfigDict(alias_generator=to_camel)
    process_ids: list[int]


class VisTraceKeyOutSchema(BasePydanticModel):
    """Pydantic schema for visualization trace key output.

    Attributes:
        self_column_id: ID of the source column.
        target_column_id: ID of the target column.
        self_column_substr_from: Substring start position for source column.
        self_column_substr_to: Substring end position for source column.
        target_column_substr_from: Substring start position for target column.
        target_column_substr_to: Substring end position for target column.
        delta_time: Time delta for trace matching.
        cut_off: Cut-off value for trace matching.

    Generated by Duo
    """

    self_column_id: int
    target_column_id: int
    self_column_substr_from: Optional[int]
    self_column_substr_to: Optional[int]
    target_column_substr_from: Optional[int]
    target_column_substr_to: Optional[int]
    delta_time: Optional[float]
    cut_off: Optional[float]


class VisTraceOutSchema(BasePydanticModel):
    """Pydantic schema for visualization trace output.

    Attributes:
        self_process_id: ID of the source process.
        target_process_id: ID of the target process.
        trace_keys: List of trace key configurations.

    Generated by Duo
    """

    self_process_id: int
    target_process_id: int
    trace_keys: list[VisTraceKeyOutSchema]


class VisLabelOutSchema(BasePydanticModel):
    """Pydantic schema for visualization label output."""

    id: int
    name: str


class VisProcessTraceOutSchema(BasePydanticModel):
    """Pydantic schema for visualization process trace output.

    Comprehensive schema for process trace visualization including process details,
    data source information, and trace configurations.

    Attributes:
        id: Process ID.
        name: Process name.
        name_en: English name.
        name_jp: Japanese name.
        name_local: Local name.
        shown_name: Displayed name.
        data_source_id: Data source ID.
        table_name: Database table name.
        master_type: Master type identifier.
        process_factid: Process factory ID.
        etl_func: ETL function name.
        traces: List of trace configurations.
        datalink_tree_directory: Directory path for datalink tree display.
        serial_column_id: ID of the main serial column.

    Methods:
        master: Computed property returning the shown name.
        label: Computed property returning the shown name.
        add_datalink_tree_category: Validator to set datalink tree directory.
        add_serial_column_id: Validator to set serial column ID.

    Generated by Duo
    """

    id: int
    name: str
    name_en: Optional[str]
    name_jp: Optional[str]
    name_local: Optional[str]
    shown_name: str

    data_source_id: int
    table_name: Optional[str]
    master_type: Optional[str]
    process_factid: Optional[str]
    etl_func: Optional[str]
    traces: list[VisTraceOutSchema]
    labels: list[VisLabelOutSchema]

    # generated data
    datalink_tree_directory: str = ''
    serial_column_id: Optional[int] = None

    @pydantic.computed_field
    @property
    def master(self) -> str:
        return self.shown_name

    @pydantic.computed_field
    @property
    def label(self) -> str:
        return self.shown_name

    @pydantic.model_validator(mode='before')
    @classmethod
    def add_datalink_tree_category(cls, data: Any):
        """Group all processes with the same data source id in front-end for viewing in tree directory"""
        # do not validate if this is not cfg process
        if not isinstance(data, CfgProcess):
            return data

        if data.data_source.type == DBType.V2.name:
            data.datalink_tree_directory = data.data_source.csv_detail.directory
        else:
            data.datalink_tree_directory = str(data.data_source_id)

        return data

    @pydantic.model_validator(mode='before')
    @classmethod
    def add_serial_column_id(cls, data: Any):
        """Whether process has main serial column, this use to validate datalink."""
        # do not validate if this is not cfg process
        if not isinstance(data, CfgProcess):
            return data

        serial_column = data.get_main_serial_col() or data.get_main_serial_function_col()
        if serial_column is not None:
            data.serial_column_id = serial_column.id

        return data


class ExportConfigSchema(BaseSchema):
    """Schema for export configuration.

    Marshmallow schema for serializing and deserializing CfgExport model instances.

    Attributes:
        id: Integer field for the export configuration ID, can be None.
        updated_at: String field for the last update timestamp, can be None.
        export_details: Nested field for export detail configurations.
        filters: Nested field for export filter configurations.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgExport
        exclude = ('created_at',)

    id = fields.Integer(required=False, allow_none=True)
    updated_at = fields.String(required=False, allow_none=True)
    export_details = fields.Nested('ExportConfigDetailSchema', many=True)
    filters = fields.Nested('ExportConfigFilterDetailSchema', many=True)


class ExportConfigDetailSchema(BaseSchema):
    """Schema for export configuration detail.

    Marshmallow schema for serializing and deserializing CfgExportDetail model instances.

    Attributes:
        export_id: Integer field for the associated export configuration ID, can be None.
        process_column_id: Integer field for the process column ID, required.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgExportDetail
        exclude = ()

    export_id = fields.Integer(required=False, allow_none=True)
    process_column_id = fields.Integer(required=True, allow_none=False)


class ExportConfigFilterDetailSchema(BaseSchema):
    """Schema for export configuration filter detail.

    Marshmallow schema for serializing and deserializing CfgExportFilter model instances.

    Attributes:
        export_id: Integer field for the associated export configuration ID, can be None.
        filter_detail_id: Integer field for the filter detail ID, can be None.

    Generated by Duo
    """

    class Meta(BaseSchema.Meta):
        model = CfgExportFilter
        exclude = ()

    export_id = fields.Integer(required=False, allow_none=True)
    filter_detail_id = fields.Integer(required=False, allow_none=True)


class LabelSchema(BaseSchema):
    """Schema for label configuration."""

    class Meta(BaseSchema.Meta):
        model = CfgLabel
        exclude = ('processes',)

    id = fields.Integer(required=False, allow_none=True)
    name = fields.String(required=True, data_key='name')
