!!omap
- fpp:
    title_en: 'FPP Full Points Plot'
    title_ja: 'FPP 全数プロット'
    png_path: 'FPP.png'
    hover_en: 'This is "Time Series Full-point Plot" or "ID Series Full-point Plot" used as an alternative to the X-R plot in Big Data analysis (Average or Range becomes less useful as a statistic when there is too much data). It is used to see trends in data and to check anomalies and outliers.\n
               It can also be used as a data downloader that extract and/or integrates data from a database.\n
               There is a function called label plot (Blue labels at the top of the graph), and you can grasp relationship between the variable fluctuation and the timing of the change of the collection such as magazine, lot and part number. There is also the ability to view a list of relevant data about the work  or the product by selecting [Right Click]→[Plot View] on any plot.'
    hover_ja: 'Big Data分析において、X-Rプロットの代替(平均値やレンジはデータ数が多くなりすぎると統計値としての有効性が薄れます)として用いる全数データの時系列もしくはワーク・製品ID系列のプロットです。データのトレンド変化や異常値・外れ値の可視化に使用します。\n
               データベースからデータ取得・紐付け統合したデータのダウンローダとしても使用できます。\n
               ラベルプロットという機能(グラフ上部にある青いラベル群)があり、マガジン・ロット・品種といった纏まりの切り替わりタイミングと変数の変動との関係を把握することができます。\nまた、任意のプロットで[右クリック]→[Plot View]を選択すると、そのワークや製品に関する関連するデータを一覧として参照できる機能もあります。'
    link_address: '/ap/fpp'
- stp:
    title_en: 'StP Stratified Plot'
    title_ja: 'StP 層別プロット'
    png_path: 'StP.png'
    hover_en: 'This is "Stratified Plot" that displays histograms by group of time zone or category.\n
              It is possible to visualize the difference between the time zone trend of data (shift, day of the week, week, etc.) and category classification (line, equipment, lot, etc.). For example, it can be use to visualize differences between lines or machine.'
    hover_ja: '時間帯別もしくはカテゴリ別にヒストグラム表示する層別プロットです。\n
              データの時間帯群トレンド(シフト・曜日・週毎等)やカテゴリ分類(ライン・装置・ロットThis毎等)などの間差を可視化することができます。ライン間差や機差などの見える化に使用します。'
    link_address: '/ap/stp'
- rlp:
    title_en: 'RLP Ridgeline Plot'
    title_ja: 'RLP リッジラインプロット'
    png_path: 'RLP.png'
    hover_en: 'In Big Data analysis, there are so many plotting points and it is often a non-normal distribution, but it is difficult to grasp the distribution fluctuation even though outliers can be grasped in FPP (Full-points Plot). You can visualize process variations by drawing density plots for each set of data and aligning it along the time or ID series.\n
               The graph plotted by points shows the increasing or decreasing trend of the distribution, indicating whether the distribution is moving downward (transitioning toward a lower value as a whole) or upward (transitioning toward a higher value). If it is straight, it means that there is little process variation. In case of continuous shift, there is a characteristic drift. And if it fluctuates rapidly, it means that it is a changing point in production line.'
    hover_ja: 'Big Data分析においては打点が多く、非正規分布であることが多いため、全数プロットFPPだけでは外れ値などは把握できるものの分布変動を把握することが難しいです。\nいくつかのデータ群毎に密度曲線(Density Plot)を描画し系列に沿って並べることで、工程の変動を把握することができます。\n
               点でプロットされているグラフは、分布の増加・減少傾向を示しており、分布が下方向(全体として値が小さくなる方向に遷移)に動いているか、上方向に動いているか(値が大きくなる方向に遷移)しているか、が分かります。まっすぐな場合は工程変動があまりないということを意味しています。\n継続してずれていく場合は特性のドリフトがある、また、急激に変動した場合は何らかの工程の変化点であることを示唆します。'
    link_address: '/ap/rlp'
- chm:
    title_en: 'CHM Calendar Heat Map'
    title_ja: 'CHM カレンダヒートマップ'
    png_path: 'CHM.png'
    hover_en: 'It visualizes long-term data such as annual variations in processes and parameters that can vary depending on days of the week or shifts, etc. For example, it is possible to visualize the rate of defects or changes in production volume over a long period of time. It is possible to understand changes in specific patterns, such as a high rate of defects at the beginning of the week, or the occurrence of specific alarms soon after the lunch breaks, and so on.'
    hover_ja: '工程での年間変動など長期間のデータや曜日・シフトなどで変動しうるパラメータを可視化します。\n例えば不良率や生産量の推移などを長期にわたって可視化することができ、例えば週明けが不良率が高いとか、昼休み空けに特定のアラームが発生しやすいといった、特定のパターンの変動などを把握することが可能です。'
    link_address: '/ap/chm'
- agp:
    title_en: 'AgP Aggregation Plot'
    title_ja: 'AgP 集計プロット'
    png_path: 'AgP.png'
    hover_en: 'You can visualize aggregate results such as production volume and number of defects in stacked bar graphs, and time-series changes in sensor data in line plots, and explore their relationships.'
    hover_ja: '生産量、不良数などの集計結果を積み上げ棒グラフで、センサーデータの時系列変化は線分プロットで可視化し、それらの関係性を探索することができます。'
    link_address: '/ap/agp'
- msp:
    title_en: 'MSP Multi Scatter Plot'
    title_ja: 'MSP 散布図行列'
    png_path: 'MSP.png'
    hover_en: 'You can check the correlation between small numbers of variables. If you want to understand the correlation between large numbers of variables, use PCP (Parallel Coordinate Plot) as below.'
    hover_ja: '少量の変数間の相関関係を確認できます。\n大量の変数間の相関を把握するには、平行座標プロットPCPをご活用ください。'
    link_address: '/ap/msp'
- scp:
    title_en: 'ScP Scatter Plot'
    title_ja: 'ScP 散布図'
    png_path: 'ScP.png'
    hover_en: 'You can draw a scatter plot of the relationships between quantitative variables such as measurements. In addition, it can be decomposed by category, period, and number of data, and changes in relationships can be confirmed. For example, it is effective for changing the process window.\n Also, the relationship between categorical variables such as equipment names and quantitative variables can be drawn with a violin plot, and the relationships between categorical variables can be drawn with a heat map. The relationships between variables that do not depend on the data type and their changes can be confirmed. '
    hover_ja: '測定値などの量的変数同士の関係性を散布図で描画します。さらに、カテゴリや期間、データ数で分解でき、関係性の変化を確認することができます。例えばプロセスウィンドウの変化に有効です。\nまた、設備名などのカテゴリ変数と量的変数の関係はバイオリンプロットで、カテゴリ変数同士の関係性はヒートマップで描画でき、データの型に寄らない変数同士の関係性およびその変化を確認することができます。'
    link_address: '/ap/scp'
- pcp:
    title_en: 'PCP Parallel Coordinates Plot'
    title_ja: 'PCP 平行座標プロット'
    png_path: 'PCP.png'
    hover_en: 'You can see the correlation between a large number of variables for a given target variable. Determine that the axes are color-separated on each axis (Each axis is parallel to the left and right), and that there is a variable to watch out for, or some correlation (In particular, if they are arranged in order of correlation coefficients, you can see the axis where the color-separation of interest are located at both ends. You can think of the axis with mixed colors as having a low correlation.).\n
              A linear correlation is observed for axes that are well-balanced iridescent (the same color arrangement as the color bar [positive correlation] or inverted color arrangement [negative correlation]). If the colors are separated, but there is a biased color distribution, there may be a nonlinear relationship, so you need to perform some function conversion or clustering for stratification (In this case, it is a good idea to check the relationship directly between the separated variables and the target variables using scatter plot).'
    hover_ja: '目的の変数に関して、大量の変数間の相関関係を確認できます。\nそれぞれの軸(各軸が左右に平行に配置されています)で色が分かれている軸が注意すべき変数、すなわち何らかの相関がある軸と判断してください(特に相関係数順に並べている場合は両端に着目すべき色が分かれた軸が見えます。色が混ざっている軸は相関が低いと考えて結構です)。\n
              バランスよく虹色になっている軸では線形の相関(カラーバーと同じ色配置[正の相関]もしくは反転した色配置[負の相関])が認められます。色が分離しているものの偏った色配置になっている場合は非線形の関係が考えられますので、何らかの関数変換を行なったり、クラスタリングし層別する必要があります(分離している変数と目的変数で散布図を用いて関係を確認することをお勧めします)。'
    link_address: '/ap/pcp'
- skd:
    title_en: 'SkD Sankey Diagram'
    title_ja: 'SkD サンキーダイアグラム'
    png_path: 'SkD.png'
    hover_en: 'Extracts highly correlated variables with respect to the target variable and plots the relationship with the strength of the correlation. The important parts of fish bones are extracted and the importance (strength of correlation is expressed by thickness) is visualized. They are calculated based on data (data-driven calculations), so you can visualize correlations without having to write fish bones by yourself.'
    hover_ja: '目的の変数に関して相関の高い変数を抽出して、相関関係の強さと共にその関係をプロットします。\n魚の骨の重要な部分を抜き出して、重要度(相関の強さを太さで表現)を可視化します。データに基づいて算出(データドリブンでの算出)しますので、魚の骨を書く技術がなくても相関関係を可視化することができます。'
    link_address: '/ap/skd'
- cog:
    title_en: 'COG Co-occurrence Graph'
    title_ja: 'COG 共起グラフ'
    png_path: 'COG.png'
    hover_en: 'You can visualize co-occurrence relationships (relationships that focus on how often one phenomenon and another occur at the same time). You can visualize relationships such as simultaneous alarms that occur when certain alarms occur, or events that occur when certain conditions occur, and so on. (Only CSV/TSV/Semicolon(;)SV files in the specified format are supported, because it is under development.)'
    hover_ja: '共起関係(ある現象と別の現象が同時に出現する頻度に着目した関係)を可視化できます。\nあるアラームが発生した際に同時に発生するアラーム、ある状態が発生した際に発生するイベントなどの関係を可視化できます。\n(開発中のため、規定フォーマットのCSV/TSV/Semicolon(;)SVファイルのみに対応)'
    link_address: '/ap/cog'
- gl:
    title_en: 'GL Graphical Lasso'
    title_ja: 'GL Graphical Lasso'
    png_path: 'GL.png'
    hover_en: 'Visualizes partial correlations of variables with network graph.\nBy specifying the objective variable, you can visualize the directly correlated variables and the in-directly correlated variables in more easy to understand layout.'
    hover_ja: '変数間の偏相関関係をネットワーク図で可視化することで、互いに相関している変数を見つけることができます。\n目的の変数を指定することで、それに直接相関する変数と、間接的に相関する変数とを分かりやすく可視化することができ。'
    link_address: '/ap/analyze/structure_learning/gl'
- pca:
    title_en: 'PCA Principal Component Analysis'
    title_ja: 'PCA 主成分分析'
    png_path: 'PCA.png'
    hover_en: 'This is multivariate analysis to detect abnormal condition and to list up concerning variables, compair to the normal state data.\n
              You can monitor the movement of over dozens of variables, and detect "out of the ordinary" situations.\n
              (It can be used when the distribution is not split.)'
    hover_ja: '多変量解析で、正常状態データを基準として、異常が発生した場合それを検出でき、その要因となる変数をリストアップすることができます。\n
              数十個といった多数の変数の動きを監視し、「いつもと違う」状況を検出することができます。\n
              (分布がスプリットしていない場合に使用できます。)'
    link_address: '/ap/analyze/anomaly_detection/pca'