import json
from abc import ABC
from datetime import datetime
from enum import StrEnum, auto
from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field, TypeAdapter
from sqlalchemy.types import String, TypeDecorator


class JobInfoLevel(StrEnum):
    """Enumeration representing levels of job information messages.

    This class is used to define levels for categorizing job information
    messages, such as warnings and errors, in a structured manner.

    Generated by Junie
    """

    WARNING = auto()
    ERROR = auto()
    INFO = auto()


class JobInfoMessage(BaseModel):
    """Represents a single job information message.

    This class encapsulates information about a single message generated during job execution,
    including its severity level, content, and timestamp.

    Attributes:
        level (JobInfoLevel): The severity level of the message (WARNING, ERROR, or INFO).
        content (str): The actual text content of the message.
        created_at (datetime): Timestamp when the message was created. Defaults to the current
            time if not explicitly provided.

    Generated by Junie
    """

    level: JobInfoLevel
    content: str
    created_at: datetime = Field(default_factory=datetime.now)


class BaseJobInfo(BaseModel, ABC):
    """
    Pydantic model for job information data.

    Attributes:
        type (str): Discriminator field to identify the subclass type.
        messages (Optional[list[JobInfoMessage]]): List of job information messages.

    Generated by Junie
    """

    type: Literal['BaseJobInfo'] = 'BaseJobInfo'
    messages: list[JobInfoMessage] = Field(default_factory=list)

    def __init_subclass__(cls, **kwargs):  # noqa: ANN003, ANN204
        """Automatically register subclasses when they are defined."""
        super().__init_subclass__(**kwargs)
        cls.__annotations__['type'] = Literal[cls.__name__]
        cls.type = cls.__name__

    def info(self, content: str):
        """Add an INFO level message to the messages list.

        Args:
            content (str): The message content to add.

        Generated by Junie
        """
        self.messages.append(JobInfoMessage(level=JobInfoLevel.INFO, content=content))

    def warning(self, content: str):
        """Add a WARNING level message to the messages list.

        Args:
            content (str): The message content to add.

        Generated by Junie
        """
        self.messages.append(JobInfoMessage(level=JobInfoLevel.WARNING, content=content))

    def error(self, content: str):
        """Add an ERROR level message to the messages list.

        Args:
            content (str): The message content to add.

        Generated by Junie
        """
        self.messages.append(JobInfoMessage(level=JobInfoLevel.ERROR, content=content))


class SqlAlchemyJobInfoType(TypeDecorator):
    """
    SQLAlchemy TypeDecorator for storing BaseJobInfo as JSON in the database.

    This class handles conversion between BaseJobInfo Pydantic models and JSON strings
    for database storage. It automatically detects and uses all registered subclasses
    via Pydantic's discriminated unions.

    Attributes:
        impl (ClassVar[String]): A class-level attribute specifying the underlying
            database type for the job information.
        cache_ok (bool): Indicates whether this object is safe to cache.

    Generated by Junie
    """

    impl = String
    cache_ok = True

    def process_bind_param(self, value, dialect):  # noqa: ARG002
        match value:
            case BaseJobInfo():
                return value.model_dump_json()
            case None:
                return None
            case _:
                raise ValueError(value)

    def process_result_value(self, value, dialect):  # noqa: ARG002
        match value:
            case str():
                json_data = json.loads(value)
                return JobTypeUnionAdapter.validate_python(json_data)
            case None:
                return None
            case _:
                raise ValueError(value)


class UserRestoreDatabaseJobInfo(BaseJobInfo):
    """Job information model for user restore database job.

    This class extends BaseJobInfo to store specific information about database restore operations,
    including the time range of data being restored.

    Attributes:
        restore_from (datetime): The start timestamp of the data range being restored.
        restore_to (datetime): The end timestamp of the data range being restored.

    Generated by Junie
    """

    restore_from: datetime
    restore_to: datetime


class UserBackupDatabaseJobInfo(BaseJobInfo):
    """Represents the job information for a user database backup task.

    This class contains information about the time range during which the
    user database backup is performed. It extends from the BaseJobInfo class
    to include specific details relevant to backing up user data. This
    information is useful for tracking and auditing backup operations.

    Attributes:
        backup_from (datetime): The starting date and time of the database
            backup.
        backup_to (datetime): The ending date and time of the database backup.
    """

    backup_from: datetime
    backup_to: datetime


class ProcessJobInfo(BaseModel):
    """Process information model."""

    id: int
    name: str


class DelAllTransactionDataJobInfo(BaseJobInfo):
    """Job information model for delete all transaction data jobs."""

    processes: list[ProcessJobInfo]


class BackupDatabaseJobInfo(BaseJobInfo):
    """Job information model for automatic config database backup job.

    Fields:
        backup_size: Size of the resulting backup file in bytes.
        backup_location: Full path to the created backup file.
        started_at: When the backup started.
        finished_at: When the backup finished.
    """

    backup_size: int | None = None
    backup_location: str | None = None
    started_at: datetime | None = None
    finished_at: datetime | None = None


class ZipLogFilesJobInfo(BaseJobInfo):
    """Job information model for zip log files job.

    This class extends BaseJobInfo to store specific information about log file zipping operations,
    tracking the number of files zipped and any messages generated during the process.

    Attributes:
        total_files_zipped (int): The total count of log files that were zipped during the operation.

    Generated by Junie
    """

    total_files_zipped: int


class GenProcLinkCountJobInfo(BaseJobInfo):
    """Job information model for generating process link count job."""

    total_matched_count: int


JobInfoUnion = Annotated[Union[*BaseJobInfo.__subclasses__()], Field(discriminator='type')]
JobTypeUnionAdapter = TypeAdapter(JobInfoUnion)
