import json
from abc import ABC
from datetime import datetime
from enum import StrEnum, auto
from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field, TypeAdapter, computed_field
from sqlalchemy.types import String, TypeDecorator


class JobInfoLevel(StrEnum):
    """Enumeration representing levels of job information messages.

    This class is used to define levels for categorizing job information
    messages, such as warnings and errors, in a structured manner.

    Generated by Junie
    """

    WARNING = auto()
    ERROR = auto()
    INFO = auto()


class JobInfoMessage(BaseModel):
    """Represents a single job information message.

    This class encapsulates information about a single message generated during job execution,
    including its severity level, content, and timestamp.

    Attributes:
        level (JobInfoLevel): The severity level of the message (WARNING, ERROR, or INFO).
        content (str): The actual text content of the message.
        created_at (datetime): Timestamp when the message was created. Defaults to the current
            time if not explicitly provided.

    Generated by Junie
    """

    level: JobInfoLevel
    content: str
    created_at: datetime = Field(default_factory=datetime.now)


class BaseJobInfo(BaseModel, ABC):
    """
    Pydantic model for job information data.

    Attributes:
        type (str): Discriminator field to identify the subclass type.
        messages (Optional[list[JobInfoMessage]]): List of job information messages.

    Generated by Junie
    """

    type: Literal['BaseJobInfo'] = 'BaseJobInfo'
    messages: list[JobInfoMessage] = Field(default_factory=list)

    def __init_subclass__(cls, **kwargs):  # noqa: ANN003, ANN204
        """Automatically register subclasses when they are defined."""
        super().__init_subclass__(**kwargs)
        cls.__annotations__['type'] = Literal[cls.__name__]
        cls.type = cls.__name__

    def info(self, content: str):
        """Add an INFO level message to the messages list.

        Args:
            content (str): The message content to add.

        Generated by Junie
        """
        self.messages.append(JobInfoMessage(level=JobInfoLevel.INFO, content=content))

    def warning(self, content: str):
        """Add a WARNING level message to the messages list.

        Args:
            content (str): The message content to add.

        Generated by Junie
        """
        self.messages.append(JobInfoMessage(level=JobInfoLevel.WARNING, content=content))

    def error(self, content: str):
        """Add an ERROR level message to the messages list.

        Args:
            content (str): The message content to add.

        Generated by Junie
        """
        self.messages.append(JobInfoMessage(level=JobInfoLevel.ERROR, content=content))

    @computed_field
    @property
    def summary(self) -> str:
        return 'summary'

    @computed_field
    @property
    def details(self) -> list[str]:
        return ['Detail1', 'Detail2']


class SqlAlchemyJobInfoType(TypeDecorator):
    """
    SQLAlchemy TypeDecorator for storing BaseJobInfo as JSON in the database.

    This class handles conversion between BaseJobInfo Pydantic models and JSON strings
    for database storage. It automatically detects and uses all registered subclasses
    via Pydantic's discriminated unions.

    Attributes:
        impl (ClassVar[String]): A class-level attribute specifying the underlying
            database type for the job information.
        cache_ok (bool): Indicates whether this object is safe to cache.

    Generated by Junie
    """

    impl = String
    cache_ok = True

    def process_bind_param(self, value, dialect):  # noqa: ARG002
        match value:
            case BaseJobInfo():
                return value.model_dump_json()
            case None:
                return None
            case _:
                raise ValueError(value)

    def process_result_value(self, value, dialect):  # noqa: ARG002
        match value:
            case str():
                json_data = json.loads(value)
                return JobTypeUnionAdapter.validate_python(json_data)
            case None:
                return None
            case _:
                raise ValueError(value)


class UserRestoreDatabaseJobInfo(BaseJobInfo):
    """Job information model for user restore database job.

    This class extends BaseJobInfo to store specific information about database restore operations,
    including the time range of data being restored.

    Attributes:
        restore_from (datetime): The start timestamp of the data range being restored.
        restore_to (datetime): The end timestamp of the data range being restored.

    Generated by Junie
    """

    restore_from: datetime
    restore_to: datetime


class UserBackupDatabaseJobInfo(BaseJobInfo):
    """Represents the job information for a user database backup task.

    This class contains information about the time range during which the
    user database backup is performed. It extends from the BaseJobInfo class
    to include specific details relevant to backing up user data. This
    information is useful for tracking and auditing backup operations.

    Attributes:
        backup_from (datetime): The starting date and time of the database
            backup.
        backup_to (datetime): The ending date and time of the database backup.
    """

    backup_from: datetime
    backup_to: datetime


class ProcessJobInfo(BaseModel):
    """Process information model."""

    id: int
    name: str


class DelAllTransactionDataJobInfo(BaseJobInfo):
    """Job information model for delete all transaction data jobs."""

    processes: list[ProcessJobInfo]


class BackupDatabaseJobInfo(BaseJobInfo):
    """Job information model for automatic config database backup job.

    Fields:
        backup_size: Size of the resulting backup file in bytes.
        backup_location: Full path to the created backup file.
        started_at: When the backup started.
        finished_at: When the backup finished.
    """

    backup_size: int | None = None
    backup_location: str | None = None
    started_at: datetime | None = None
    finished_at: datetime | None = None


class ZipLogFilesJobInfo(BaseJobInfo):
    """Job information model for zip log files job.

    This class extends BaseJobInfo to store specific information about log file zipping operations,
    tracking the number of files zipped and any messages generated during the process.

    Attributes:
        total_files_zipped (int): The total count of log files that were zipped during the operation.

    Generated by Junie
    """

    total_files_zipped: int


class GenProcLinkCountJobInfo(BaseJobInfo):
    """Job information model for generating process link count job."""

    total_matched_count: int


class CsvImportJobInfo(BaseJobInfo):
    """
    Represents information about a CSV import job.

    This class is used to store details about the progress and state of a CSV
    file import job. It inherits from the BaseJobInfo class and extends it
    with additional attributes specific to CSV file imports.

    Attributes:
    ----------
    row_imported : int
        The total number of rows successfully imported from the CSV file(s).
    empty_files : list of str
        A list of file names that were empty and could not be imported.
    import_targets : list[CsvImportTargetInfo]
        Detailed information for each CSV file being imported, including
        record counts, errors, and encoding details.
    imported_row : int
        Total number of rows successfully imported across all files.
    is_abnormal : bool
        Flag indicating whether abnormal conditions were detected during import.
    created_at : datetime
        Timestamp when the job was created.
    """

    class CsvImportTargetInfo(BaseModel):
        file_name: str = Field(default='')
        transform_file: str = Field(default='')
        error: str = Field(default='')
        encoding: str = Field(default='')
        error_type: str = Field(default='')
        file_record_count: int = Field(default=0, ge=0)
        file_error_record_count: int = Field(default=0, ge=0)
        file_duplicated_record_count: int = Field(default=0, ge=0)
        created_at: datetime = Field(default_factory=datetime.now)

    empty_files: list[str] = Field(default_factory=list)
    import_targets: list[CsvImportTargetInfo] = Field(default_factory=list)
    imported_row: int = Field(default=0, ge=0)
    is_abnormal: bool = Field(default=False)


class DataExportJobInfo(BaseJobInfo):
    """Job information model for data export job.

    This class extends BaseJobInfo to store specific information about data export operations,
    including the number of records exported and the location where the export file is saved.

    Attributes:
        exported_records (int): The total count of records that were exported.
        export_location (str): The file path where the exported data is saved.
        export_from (datetime, str): When the export started.
        export_to (datetime, str): When the export finished.

    Generated by Duo
    """

    exported_records: int | None = None
    export_location: str | None = None
    export_from: str | None = None
    export_to: str | None = None


class ImportDataJobInfo(BaseJobInfo):
    """Job information for import data operations.

    Stores import statistics including total record count and detailed
    information for each import target (file/batch).

    Attributes:
        imported_records: Total number of records imported across all targets.
        error_records: Total number of records that failed to import
        import_targets: List of import target information, each containing:
            - imported_target_records: Number of records imported for this target.
            - error_target_records: Number of records that failed to import for this target.
            - import_from: Start timestamp of imported data for this target.
            - import_to: End timestamp of imported data for this target.
    """

    class ImportTargetInfo(BaseModel):
        """Information for a single import target (file/batch).

        Attributes:
            imported_target_records: Number of records imported for this target.
            error_target_records: Number of records that failed to import for this target.
            import_from: Start timestamp of imported data.
            import_to: End timestamp of imported data.
        """

        imported_target_records: int = Field(default=0, ge=0)
        error_target_records: int = Field(default=0, ge=0)
        import_from: str = Field(default='')
        import_to: str = Field(default='')

    imported_records: int = Field(default=0, ge=0)
    error_records: int = Field(default=0, ge=0)
    import_targets: list[ImportTargetInfo] = Field(default_factory=list)


class DelTransactionProcessJobInfo(BaseModel):
    """Process information model."""

    id: int
    name: str
    deleted_records: int


class DelTransactionDataByLimit(BaseJobInfo):
    """Job information model for delete transaction data by limit job."""

    processes: list[DelTransactionProcessJobInfo]


class WebAPIImportJobInfo(BaseJobInfo):
    """Job information model for web api import job information.

    Attributes:
        imported_count: Count of records imported.
        error_count: Count of records error.
    """

    imported_count: int | None = None
    error_count: int | None = None


class PullDataJobInfo(BaseJobInfo):
    """Job information model for pulling data job.

    This class extends BaseJobInfo to store specific information about data pull operations,
    including details about each target process being pulled and the records imported.

    Attributes:
        pull_targets (list[PullDataTargetInfo]): List of target processes with their import details.
            Each target contains process ID, import time range, record count, and creation timestamp.
    """

    class PullDataTargetInfo(BaseModel):
        """Information about a single data pull target.
        - process_id (int): ID of the process being pulled.
        - import_from (datetime): Start timestamp of the import range.
        - import_to (datetime): End timestamp of the import range.
        - imported_records (int): Number of records imported from this target.
        - created_at (datetime): Timestamp when this target info was created.
        """

        process_id: int
        import_from: datetime
        import_to: datetime
        imported_records: int = Field(default=0, ge=0)
        created_at: datetime = Field(default_factory=datetime.now)

    pull_targets: list[PullDataTargetInfo] = Field(
        default_factory=list, description='List of pull targets with import details'
    )


class FactoryImportJobInfo(BaseJobInfo):
    """Job information model for factory import job.

    This class extends BaseJobInfo to store specific information about database import operations.

    Attributes:
        start_time (datetime): The minimum value of selectable time range
        end_time (datetime): The maximum value of selectable time range
        data_frame_info_objects (list of FactoryImportDataFrameInfo): Information of each dataframe imported

    Properties:
        total_imported_rows (int): Total number of rows successfully written into transaction DB
        total_error_rows (int): Total number of rows with datatype error
        total_duplicate_rows (int): Total number of duplicate rows
    """

    class FactoryImportDataFrameInfo(BaseModel):
        """Struct to store Dataframe information for factory import job.

        Attributes:
            size (int): Size of dataframe before processing
            imported_start_time (datetime): datetime key value of first row
            imported_end_time (datetime): datetime key value of last row
            imported_rows (int): number of rows successfully written into transaction DB
            error_rows (int): number of rows with datatype error
            duplicate_rows (int): number of duplicate rows
        """

        size: int = Field(default=0, ge=0)
        imported_start_time: datetime | None = Field(default=None)
        imported_end_time: datetime | None = Field(default=None)
        imported_rows: int = Field(default=0, ge=0)
        error_rows: int = Field(default=0, ge=0)
        duplicate_rows: int = Field(default=0, ge=0)

    start_time: datetime | None = Field(default=None)
    end_time: datetime | None = Field(default=None)
    data_frame_info_objects: list[FactoryImportDataFrameInfo] = Field(default_factory=list)

    @computed_field
    @property
    def total_imported_rows(self) -> int:
        sum_imported_rows = 0
        for info in self.data_frame_info_objects:
            sum_imported_rows += info.imported_rows
        return sum_imported_rows

    @computed_field
    @property
    def total_error_rows(self) -> int:
        sum_error_rows = 0
        for info in self.data_frame_info_objects:
            sum_error_rows += info.error_rows
        return sum_error_rows

    @computed_field
    @property
    def total_duplicate_rows(self) -> int:
        sum_duplicate_rows = 0
        for info in self.data_frame_info_objects:
            sum_duplicate_rows += info.duplicate_rows
        return sum_duplicate_rows

    @computed_field
    @property
    def summary(self) -> str:
        return (
            f'Start time: {self.start_time}; '
            f'End time: {self.end_time}; '
            f'Total imported records: {self.total_imported_rows} records; '
            f'Total error records: {self.total_error_rows} records; '
            f'Total duplicate records: {self.total_duplicate_rows} records'
        )

    @computed_field
    @property
    def details(self) -> list[str]:
        return self.data_frame_info_objects


class FactoryPastImportJobInfo(FactoryImportJobInfo, BaseJobInfo):
    """Job information model for past factory import job.

    This class extends FactoryImportJobInfo to store specific information about past factory database import operations.

    Attributes:
        start_time (datetime): The minimum value of selectable time range
        end_time (datetime): The maximum value of selectable time range
        data_frame_info_objects (list of FactoryImportDataFrameInfo): Information of each dataframe imported

    Properties:
        total_imported_rows (int): Total number of rows successfully written into transaction DB
        total_error_rows (int): Total number of rows with datatype error
        total_duplicate_rows (int): Total number of duplicate rows
    """


class UpdateTransactionTableJobInfo(BaseJobInfo):
    """Job information for updating transaction table schema.

    Tracks changes made to the transaction table structure during schema updates,
    specifically focusing on the state of the main serial column before and after.

    Attributes:
        main_serial_before: Main serial column configuration before update.
        main_serial_after: Main serial column configuration after update.
    """

    main_serial_before: str | None = None
    main_serial_after: str | None = None


JobInfoUnion = Annotated[Union[*BaseJobInfo.__subclasses__()], Field(discriminator='type')]
JobTypeUnionAdapter = TypeAdapter(JobInfoUnion)
