import json
from abc import ABC, abstractmethod
from datetime import datetime
from enum import StrEnum, auto
from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field, TypeAdapter, computed_field
from sqlalchemy.types import String, TypeDecorator

from ap.common.constants import JobType


class JobInfoLevel(StrEnum):
    """Enumeration representing levels of job information messages.

    This class is used to define levels for categorizing job information
    messages, such as warnings and errors, in a structured manner.

    Generated by Junie
    """

    WARNING = auto()
    ERROR = auto()
    INFO = auto()


class JobInfoMessage(BaseModel):
    """Represents a single job information message.

    This class encapsulates information about a single message generated during job execution,
    including its severity level, content, and timestamp.

    Attributes:
        level (JobInfoLevel): The severity level of the message (WARNING, ERROR, or INFO).
        content (str): The actual text content of the message.
        created_at (datetime): Timestamp when the message was created. Defaults to the current
            time if not explicitly provided.

    Generated by Junie
    """

    level: JobInfoLevel
    content: str
    created_at: datetime = Field(default_factory=datetime.now)


class BaseJobInfo(BaseModel, ABC):
    """
    Pydantic model for job information data.

    Attributes:
        type (str): Discriminator field to identify the subclass type.
        messages (Optional[list[JobInfoMessage]]): List of job information messages.

    Generated by Junie
    """

    type: Literal['BaseJobInfo'] = 'BaseJobInfo'
    messages: list[JobInfoMessage] = Field(default_factory=list)

    def __init_subclass__(cls, **kwargs):  # noqa: ANN003, ANN204
        """Automatically register subclasses when they are defined."""
        super().__init_subclass__(**kwargs)
        cls.__annotations__['type'] = Literal[cls.__name__]
        cls.type = cls.__name__

    def info(self, content: str):
        """Add an INFO level message to the messages list.

        Args:
            content (str): The message content to add.

        Generated by Junie
        """
        self.messages.append(JobInfoMessage(level=JobInfoLevel.INFO, content=content))

    def warning(self, content: str):
        """Add a WARNING level message to the messages list.

        Args:
            content (str): The message content to add.

        Generated by Junie
        """
        self.messages.append(JobInfoMessage(level=JobInfoLevel.WARNING, content=content))

    def error(self, content: str):
        """Add an ERROR level message to the messages list.

        Args:
            content (str): The message content to add.

        Generated by Junie
        """
        self.messages.append(JobInfoMessage(level=JobInfoLevel.ERROR, content=content))

    @computed_field
    @abstractmethod
    def summary(self) -> str:
        """Summary information of job"""
        ...

    @computed_field
    @abstractmethod
    def details(self) -> list:
        """Detail information of job"""
        ...


class SqlAlchemyJobInfoType(TypeDecorator):
    """
    SQLAlchemy TypeDecorator for storing BaseJobInfo as JSON in the database.

    This class handles conversion between BaseJobInfo Pydantic models and JSON strings
    for database storage. It automatically detects and uses all registered subclasses
    via Pydantic's discriminated unions.

    Attributes:
        impl (ClassVar[String]): A class-level attribute specifying the underlying
            database type for the job information.
        cache_ok (bool): Indicates whether this object is safe to cache.

    Generated by Junie
    """

    impl = String
    cache_ok = True

    def process_bind_param(self, value, dialect=None):  # noqa: ARG002
        match value:
            case BaseJobInfo():
                return value.model_dump_json(exclude={'summary', 'details'})
            case None:
                return None
            case _:
                raise ValueError(value)

    def process_result_value(self, value, dialect=None):  # noqa: ARG002
        match value:
            case str():
                json_data = json.loads(value)
                return JobTypeUnionAdapter.validate_python(json_data)
            case None:
                return None
            case _:
                raise ValueError(value)


class UserRestoreDatabaseJobInfo(BaseJobInfo):
    """Job information model for user restore database job.

    This class extends BaseJobInfo to store specific information about database restore operations,
    including the time range of data being restored.

    Attributes:
        restore_from (datetime): The start timestamp of the data range being restored.
        restore_to (datetime): The end timestamp of the data range being restored.

    Generated by Junie
    """

    restore_from: datetime | None = None
    restore_to: datetime | None = None

    @computed_field
    @property
    def summary(self) -> str:
        return f'Restore from: {self.restore_from} to: {self.restore_to}'

    @computed_field
    @property
    def details(self) -> list:
        return []


class UserBackupDatabaseJobInfo(BaseJobInfo):
    """Represents the job information for a user database backup task.

    This class contains information about the time range during which the
    user database backup is performed. It extends from the BaseJobInfo class
    to include specific details relevant to backing up user data. This
    information is useful for tracking and auditing backup operations.

    Attributes:
        backup_from (datetime): The starting date and time of the database
            backup.
        backup_to (datetime): The ending date and time of the database backup.
    """

    backup_from: datetime | None = None
    backup_to: datetime | None = None

    @computed_field
    @property
    def summary(self) -> str:
        return f'Backup from: {self.backup_from} to: {self.backup_to}'

    @computed_field
    @property
    def details(self) -> list:
        return []


class DelAllTransactionDataJobInfo(BaseJobInfo):
    """Job information model for delete all transaction data jobs."""

    class ProcessJobInfo(BaseModel):
        """Process information model."""

        id: int
        name: str

    processes: list[ProcessJobInfo] = Field(default_factory=list)

    @computed_field
    @property
    def summary(self) -> str:
        return f'Total Processes: {len(self.processes)}'

    @computed_field
    @property
    def details(self) -> list:
        return self.processes


class BackupDatabaseJobInfo(BaseJobInfo):
    """Job information model for automatic config database backup job.

    Fields:
        backup_size: Size of the resulting backup file in bytes.
        backup_location: Full path to the created backup file.
        started_at: When the backup started.
        finished_at: When the backup finished.
    """

    backup_size: int | None = None
    backup_location: str | None = None
    started_at: datetime | None = None
    finished_at: datetime | None = None

    @computed_field
    @property
    def summary(self) -> str:
        return f'Backup size: {self.backup_size} bytes'

    @computed_field
    @property
    def details(self) -> list:
        return [
            {
                'backup_size': self.backup_size,
                'backup_location': self.backup_location,
                'start_at': self.started_at,
                'finished_at': self.finished_at,
            }
        ]


class ZipLogFilesJobInfo(BaseJobInfo):
    """Job information model for zip log files job.

    This class extends BaseJobInfo to store specific information about log file zipping operations,
    tracking the number of files zipped and any messages generated during the process.

    Attributes:
        total_files_zipped (int): The total count of log files that were zipped during the operation.

    Generated by Junie
    """

    total_files_zipped: int = Field(default=0)

    @computed_field
    @property
    def summary(self) -> str:
        return f'Total files zipped: {self.total_files_zipped}'

    @computed_field
    @property
    def details(self) -> list:
        return []


class GenProcLinkCountJobInfo(BaseJobInfo):
    """Job information model for generating process link count job."""

    total_matched_count: int = Field(default=0)

    @computed_field
    @property
    def summary(self) -> str:
        return f'Total matched count: {self.total_matched_count}'

    @computed_field
    @property
    def details(self) -> list:
        return []


class CsvImportJobInfo(BaseJobInfo):
    """
    Represents information about a CSV import job.

    This class is used to store details about the progress and state of a CSV
    file import job. It inherits from the BaseJobInfo class and extends it
    with additional attributes specific to CSV file imports.

    Attributes:
    ----------
    row_imported : int
        The total number of rows successfully imported from the CSV file(s).
    empty_files : list of str
        A list of file names that were empty and could not be imported.
    import_targets : list[CsvImportTargetInfo]
        Detailed information for each CSV file being imported, including
        record counts, errors, and encoding details.
    imported_row : int
        Total number of rows successfully imported across all files.
    is_abnormal : bool
        Flag indicating whether abnormal conditions were detected during import.
    created_at : datetime
        Timestamp when the job was created.
    """

    class CsvImportTargetInfo(BaseModel):
        file_name: str = Field(default='')
        transform_file: str = Field(default='')
        error: str = Field(default='')
        encoding: str = Field(default='')
        error_type: str = Field(default='')
        file_record_count: int = Field(default=0, ge=0)
        file_error_record_count: int = Field(default=0, ge=0)
        file_duplicated_record_count: int = Field(default=0, ge=0)
        created_at: datetime = Field(default_factory=datetime.now)

    empty_files: list[str] = Field(default_factory=list)
    import_targets: list[CsvImportTargetInfo] = Field(default_factory=list)
    imported_row: int = Field(default=0, ge=0)
    is_abnormal: bool = Field(default=False)

    @computed_field
    @property
    def summary(self) -> str:
        return (
            f'Valid Data: {self.imported_row} records; '
            f'Empty Files:{",".join(self.empty_files) if len(self.empty_files) else []}'
        )

    @computed_field
    @property
    def details(self) -> list:
        return self.import_targets


class DataExportJobInfo(BaseJobInfo):
    """Job information model for data export job.

    This class extends BaseJobInfo to store specific information about data export operations,
    including the number of records exported and the location where the export file is saved.

    Attributes:
        data_frame_info_objects (list[ExportDataFrameInfo]): List of dataframe export information objects.
            Each object contains details about a single exported dataframe including date range,
            row count, and file location.

    Computed Properties:
        summary (str): A summary string showing the total number of exported records.
        total_exported_records (int): The total count of records exported across all dataframes.
        details (list): List of all ExportDataFrameInfo objects containing detailed export information.
    """

    class ExportDataFrameInfo(BaseModel):
        """Struct to store Dataframe information for data export job

        Attributes:
            export_from (datetime): datetime key value of first row
            export_to (datetime): datetime key value of last row
            export_rows (int): number of rows successfully written into exported file
            export_location (str): exported file path
        """

        export_from: datetime | None = Field(default=None)
        export_to: datetime | None = Field(default=None)
        export_rows: int = Field(default=0, ge=0)
        export_location: str | None = None

    data_frame_info_objects: list[ExportDataFrameInfo] = Field(default_factory=list)
    retry_count: int | None = None
    export_id: int | None = None
    status: str | None = None

    @computed_field
    @property
    def summary(self) -> str:
        return f'Valid Data: {self.total_exported_records} records'

    @computed_field
    @property
    def total_exported_records(self) -> int:
        sum_exported_rows = 0
        for info in self.data_frame_info_objects:
            sum_exported_rows += info.export_rows
        return sum_exported_rows

    @computed_field
    @property
    def details(self) -> list:
        return self.data_frame_info_objects


class ImportDataJobInfo(BaseJobInfo):
    """Job information for import data operations.

    Stores import statistics including total record count and detailed
    information for each import target (file/batch).

    Attributes:
        imported_records: Total number of records imported across all targets.
        error_records: Total number of records that failed to import
        import_targets: List of import target information, each containing:
            - imported_target_records: Number of records imported for this target.
            - error_target_records: Number of records that failed to import for this target.
            - import_from: Start timestamp of imported data for this target.
            - import_to: End timestamp of imported data for this target.
    """

    class ImportTargetInfo(BaseModel):
        """Information for a single import target (file/batch).

        Attributes:
            imported_target_records: Number of records imported for this target.
            error_target_records: Number of records that failed to import for this target.
            import_from: Start timestamp of imported data.
            import_to: End timestamp of imported data.
        """

        imported_target_records: int = Field(default=0, ge=0)
        error_target_records: int = Field(default=0, ge=0)
        import_from: str = Field(default='')
        import_to: str = Field(default='')

    imported_records: int = Field(default=0, ge=0)
    error_records: int = Field(default=0, ge=0)
    import_targets: list[ImportTargetInfo] = Field(default_factory=list)

    @computed_field
    @property
    def summary(self) -> str:
        return f'Valid Data: {self.imported_records}'

    @computed_field
    @property
    def details(self) -> list:
        return self.import_targets


class DelTransactionDataByLimit(BaseJobInfo):
    """Job information model for delete transaction data by limit job."""

    class DelTransactionProcessJobInfo(BaseModel):
        """Process information model."""

        id: int
        name: str
        deleted_records: int

    processes: list[DelTransactionProcessJobInfo] = Field(default_factory=list)

    @computed_field
    @property
    def summary(self) -> str:
        return f'Total Deleted Records: {sum(process.deleted_records for process in self.processes)}'

    @computed_field
    @property
    def details(self) -> list:
        return self.processes


class WebAPIImportJobInfo(BaseJobInfo):
    """Job information model for web api import job information.

    Attributes:
        imported_count: Count of records imported.
        error_count: Count of records error.
    """

    imported_count: int | None = None
    error_count: int | None = None

    @computed_field
    @property
    def summary(self) -> str:
        return f'Valid Data: {self.imported_count} records; Error: {self.error_count} records'

    @computed_field
    @property
    def details(self) -> list:
        return []


class PullDataJobInfo(BaseJobInfo):
    """Job information model for pulling data job.

    This class extends BaseJobInfo to store specific information about data pull operations,
    including details about each target process being pulled and the records imported.

    Attributes:
        pull_targets (list[PullDataTargetInfo]): List of target processes with their import details.
            Each target contains process ID, import time range, record count, and creation timestamp.
    """

    class PullDataTargetInfo(BaseModel):
        """Information about a single data pull target.
        - process_id (int): ID of the process being pulled.
        - import_from (datetime): Start timestamp of the import range.
        - import_to (datetime): End timestamp of the import range.
        - imported_records (int): Number of records imported from this target.
        - created_at (datetime): Timestamp when this target info was created.
        """

        process_id: int
        import_from: datetime | None
        import_to: datetime | None
        imported_records: int = Field(default=0, ge=0)
        created_at: datetime = Field(default_factory=datetime.now)

    pull_targets: list[PullDataTargetInfo] = Field(
        default_factory=list, description='List of pull targets with import details'
    )

    @computed_field
    @property
    def summary(self) -> str:
        return f'Total pull targets : {len(self.pull_targets)}'

    @computed_field
    @property
    def details(self) -> list:
        return self.pull_targets


class FactoryImportJobInfo(BaseJobInfo):
    """Job information model for factory import job.

    This class extends BaseJobInfo to store specific information about database import operations.

    Attributes:
        start_time (datetime): The minimum value of selectable time range
        end_time (datetime): The maximum value of selectable time range
        data_frame_info_objects (list of FactoryImportDataFrameInfo): Information of each dataframe imported

    Properties:
        total_imported_rows (int): Total number of rows successfully written into transaction DB
        total_error_rows (int): Total number of rows with datatype error
        total_duplicate_rows (int): Total number of duplicate rows
    """

    class FactoryImportDataFrameInfo(BaseModel):
        """Struct to store Dataframe information for factory import job.

        Attributes:
            size (int): Size of dataframe before processing
            imported_start_time (datetime): datetime key value of first row
            imported_end_time (datetime): datetime key value of last row
            imported_rows (int): number of rows successfully written into transaction DB
            error_rows (int): number of rows with datatype error
            duplicate_rows (int): number of duplicate rows
        """

        size: int = Field(default=0, ge=0)
        imported_start_time: datetime | None = Field(default=None)
        imported_end_time: datetime | None = Field(default=None)
        imported_rows: int = Field(default=0, ge=0)
        error_rows: int = Field(default=0, ge=0)
        duplicate_rows: int = Field(default=0, ge=0)

    start_time: datetime | None = Field(default=None)
    end_time: datetime | None = Field(default=None)
    data_frame_info_objects: list[FactoryImportDataFrameInfo] = Field(default_factory=list)

    @computed_field
    @property
    def total_imported_rows(self) -> int:
        sum_imported_rows = 0
        for info in self.data_frame_info_objects:
            sum_imported_rows += info.imported_rows
        return sum_imported_rows

    @computed_field
    @property
    def total_error_rows(self) -> int:
        sum_error_rows = 0
        for info in self.data_frame_info_objects:
            sum_error_rows += info.error_rows
        return sum_error_rows

    @computed_field
    @property
    def total_duplicate_rows(self) -> int:
        sum_duplicate_rows = 0
        for info in self.data_frame_info_objects:
            sum_duplicate_rows += info.duplicate_rows
        return sum_duplicate_rows

    @computed_field
    @property
    def summary(self) -> str:
        return f'Valid Data: {self.total_imported_rows} records;'

    @computed_field
    @property
    def details(self) -> list:
        return self.data_frame_info_objects


class FactoryPastImportJobInfo(FactoryImportJobInfo, BaseJobInfo):
    """Job information model for past factory import job.

    This class extends FactoryImportJobInfo to store specific information about past factory database import operations.

    Attributes:
        start_time (datetime): The minimum value of selectable time range
        end_time (datetime): The maximum value of selectable time range
        data_frame_info_objects (list of FactoryImportDataFrameInfo): Information of each dataframe imported

    Properties:
        total_imported_rows (int): Total number of rows successfully written into transaction DB
        total_error_rows (int): Total number of rows with datatype error
        total_duplicate_rows (int): Total number of duplicate rows
    """


class UpdateTransactionTableJobInfo(BaseJobInfo):
    """Job information for updating transaction table schema.

    Tracks changes made to the transaction table structure during schema updates,
    specifically focusing on the state of the main serial column before and after.

    Attributes:
        main_serial_before: Main serial column configuration before update.
        main_serial_after: Main serial column configuration after update.
    """

    main_serial_before: str | None = None
    main_serial_after: str | None = None

    @computed_field
    @property
    def summary(self) -> str:
        return f'Main serial before: {self.main_serial_before}, Main serial after: {self.main_serial_after}'

    @computed_field
    @property
    def details(self) -> list:
        return []


class BulkProcessRegisterJobInfo(BaseJobInfo):
    """Job information for bulk process registration operations.

    Tracks the number of processes successfully registered, any errors encountered,
    and detailed information about each registered process during a bulk registration job.

    Attributes:
        registered_process_count: Number of processes successfully registered in this job.
        failed_processes: List of processes that failed to register with error details.
        is_directly_import: Whether processes were directly imported after registration.
    """

    class BulkProcessRegisterErrorData(BaseModel):
        """Represents error information for a process that failed during bulk registration.

        Attributes:
            process_name (str):
                The name of the process that failed to register.
            process_factid (str):
                The unique FACTID identifier of the process.
            error_message (str):
                A description of the error encountered during registration.
        """

        process_name: str
        process_factid: str
        error_message: str

    class BulkProcessRegisterSuccessData(BaseModel):
        """Represents success information for a process that registered successfully during bulk registration.

        Attributes:
            process_name (str):
                The name of the process that registered successfully.
            process_factid (str):
                The unique FACTID identifier of the process.
            status (str):
                The status of registration (always "success").
        """

        process_name: str
        process_factid: str

    registered_process_count: int = Field(default=0, ge=0)
    failed_processes: list[BulkProcessRegisterErrorData] = Field(default_factory=list)
    success_processes: list[BulkProcessRegisterSuccessData] = Field(default_factory=list)
    is_directly_import: bool = False

    @computed_field
    @property
    def summary(self) -> str:
        return f'Registered processes: {self.registered_process_count}; Failed: {len(self.failed_processes)}'

    @computed_field
    @property
    def details(self) -> list:
        return [
            {
                'success': self.success_processes,
                'failed': self.failed_processes,
            }
        ]


class ComputeProcessCacheJobInfo(BaseJobInfo):
    """Job information for computing process cache.

    Attributes:
        cached_processes: list of processes that was computed cache.
    """

    class CachedProcess(BaseModel):
        id: int | None = Field(default=None)
        name: str | None = Field(default=None)

    cached_processes: list[CachedProcess] = Field(default_factory=list)

    @computed_field
    @property
    def summary(self) -> str:
        return f'Computed cache for {len(self.cached_processes)} process(es); '

    @computed_field
    @property
    def details(self) -> list:
        return self.cached_processes


class ComputeAllProcessIdsCacheJobInfo(BaseJobInfo):
    """Job information for computing all processes cache.

    Attributes:
        cached_processes: list of processes that was computed cache.
    """

    class CachedProcessId(BaseModel):
        id: int | None = Field(default=None)

    cached_process_ids: list[CachedProcessId] = Field(default_factory=list)

    @computed_field
    @property
    def summary(self) -> str:
        return f'Computed cache for {len(self.cached_process_ids)} process id(s); '

    @computed_field
    @property
    def details(self) -> list:
        return self.cached_process_ids


class ComputeAllTracesCacheJobInfo(BaseJobInfo):
    """Job information for computing all processes cache.

    Attributes:
        cached_processes: list of processes that was computed cache.
    """

    class TraceNode(BaseModel):
        id: int | None = Field(default=None)

    leaf_start_nodes: list[TraceNode] = Field(default_factory=list)
    leaf_end_nodes: list[TraceNode] = Field(default_factory=list)

    @computed_field
    @property
    def summary(self) -> str:
        return f'Computed all traces for {len(self.leaf_start_nodes) + len(self.leaf_end_nodes)} node(s); '

    @computed_field
    @property
    def details(self) -> list:
        return [
            {
                'Start Nodes': ','.join(str(x.id) for x in self.leaf_start_nodes),
                'End Nodes': ','.join(str(x.id) for x in self.leaf_end_nodes),
            }
        ]


class VacuumDbJobInfo(BaseJobInfo):
    """Job information model for vacuum db.

    Attributes:
        started_at: When the backup started.
        finished_at: When the backup finished.
    """

    started_at: datetime | None = Field(default=None)
    finished_at: datetime | None = Field(default=None)

    @computed_field
    @property
    def summary(self) -> str:
        return 'Vacuum Database'

    @computed_field
    @property
    def details(self) -> list:
        return [
            {
                'start_at': self.started_at,
                'finished_at': self.finished_at,
            }
        ]


class BackupJobHistoryJobInfo(BaseJobInfo):
    """Job information model for backup job history.

    Attributes:
        backup_records: number of records were backup
        deleted_records: number of records were deleted
        job_max_time: maximum time for job history
        job_min_time: minimum time for job history
        started_at: When the backup started.
        finished_at: When the backup finished.
    """

    backup_records: int = Field(default=0, ge=0)
    deleted_records: int = Field(default=0, ge=0)
    job_max_time: datetime | None = Field(default=None)
    job_min_time: datetime | None = Field(default=None)
    file_path: str | None = Field(default=None)
    started_at: datetime | None = Field(default=None)
    finished_at: datetime | None = Field(default=None)

    @computed_field
    @property
    def summary(self) -> str:
        return 'Backup Job History'

    @computed_field
    @property
    def details(self) -> list:
        return [
            {
                'start_at': self.started_at,
                'finished_at': self.finished_at,
                'backup_records': self.backup_records,
                'deleted_records': self.deleted_records,
                'file_path': self.file_path,
                'job_max_time': self.job_max_time,
                'job_min_time': self.job_min_time,
            }
        ]


class CleanupJobHistoryJobInfo(BaseJobInfo):
    """Job information model for backup job history.

    Attributes:
        deleted_files: list of file paths that were deleted.
        started_at: When the backup started.
        finished_at: When the backup finished.
    """

    class DeletedFile(BaseModel):
        file_path: str | None = Field(default=None)

    deleted_files: list[DeletedFile] = Field(default_factory=list)
    started_at: datetime | None = Field(default=None)
    finished_at: datetime | None = Field(default=None)

    @computed_field
    @property
    def summary(self) -> str:
        return f'Cleanup Job History start_at: {self.started_at} - finished_at: {self.finished_at}'

    @computed_field
    @property
    def details(self) -> list:
        return self.deleted_files


JobInfoUnion = Union[
    UserRestoreDatabaseJobInfo,
    UserBackupDatabaseJobInfo,
    DelAllTransactionDataJobInfo,
    BackupDatabaseJobInfo,
    ZipLogFilesJobInfo,
    GenProcLinkCountJobInfo,
    CsvImportJobInfo,
    DataExportJobInfo,
    ImportDataJobInfo,
    DelTransactionDataByLimit,
    WebAPIImportJobInfo,
    PullDataJobInfo,
    FactoryImportJobInfo,
    FactoryPastImportJobInfo,
    UpdateTransactionTableJobInfo,
    BulkProcessRegisterJobInfo,
    ComputeProcessCacheJobInfo,
    ComputeAllProcessIdsCacheJobInfo,
    ComputeAllTracesCacheJobInfo,
    VacuumDbJobInfo,
    BackupJobHistoryJobInfo,
    CleanupJobHistoryJobInfo,
]
JobTypeUnionAdapter = TypeAdapter(Annotated[JobInfoUnion, Field(discriminator='type')])
JobMappingByJobType = {
    JobType.CSV_IMPORT.name: CsvImportJobInfo(),
    JobType.DATA_EXPORT.name: DataExportJobInfo(),
    JobType.IMPORT_DATA.name: ImportDataJobInfo(),
    JobType.PULL_DATA.name: PullDataJobInfo(),
    JobType.FACTORY_IMPORT.name: FactoryImportJobInfo(),
    JobType.FACTORY_PAST_IMPORT.name: FactoryPastImportJobInfo(),
    JobType.UPDATE_TRANSACTION_TABLE.name: UpdateTransactionTableJobInfo(),
    JobType.WEB_API_IMPORT.name: WebAPIImportJobInfo(),
    JobType.BACKUP_DATABASE.name: BackupDatabaseJobInfo(),
    JobType.DEL_ALL_TRANSACTION_DATA.name: DelAllTransactionDataJobInfo(),
    JobType.DEL_TRANSACTION_DATA_BY_LIMIT.name: DelTransactionDataByLimit(),
    JobType.PROC_LINK_COUNT.name: GenProcLinkCountJobInfo(),
    JobType.USER_RESTORE_DATABASE.name: UserRestoreDatabaseJobInfo(),
    JobType.USER_BACKUP_DATABASE.name: UserBackupDatabaseJobInfo(),
    JobType.ZIP_LOG.name: ZipLogFilesJobInfo(),
    JobType.BULK_PROCESS_REGISTER.name: BulkProcessRegisterJobInfo(),
    JobType.COMPUTE_PROCESS_CACHE.name: ComputeProcessCacheJobInfo(),
    JobType.PERIODICALLY_COMPUTE_PROCESS_CACHE.name: ComputeProcessCacheJobInfo(),
    JobType.COMPUTE_ALL_PROCESS_IDS_CACHE.name: ComputeAllProcessIdsCacheJobInfo(),
    JobType.PERIODICALLY_COMPUTE_ALL_PROCESSES_CACHE.name: ComputeAllProcessIdsCacheJobInfo(),
    JobType.COMPUTE_ALL_TRACES_CACHE.name: ComputeAllTracesCacheJobInfo(),
    JobType.PERIODICALLY_COMPUTE_ALL_TRACES_CACHE.name: ComputeAllTracesCacheJobInfo(),
    JobType.VACUUM_DB.name: VacuumDbJobInfo(),
    JobType.BACKUP_JOB_HISTORY.name: BackupJobHistoryJobInfo(),
    JobType.CLEANUP_JOB_HISTORY.name: CleanupJobHistoryJobInfo(),
}
