from __future__ import annotations

from collections.abc import Mapping
from datetime import datetime, timedelta
from typing import Any

from apscheduler.job import Job
from apscheduler.triggers.date import DateTrigger
from apscheduler.triggers.interval import IntervalTrigger
from flask_apscheduler import APScheduler
from pytz import utc


class CustomizeScheduler(APScheduler):
    """Custom scheduler extending Flask-APScheduler with rescheduling capabilities.

    Provides enhanced job scheduling functionality with support for dynamic
    rescheduling of jobs.

    Attributes:
        RESCHEDULE_SECONDS: Default number of seconds to delay when rescheduling a job.

    Methods:
        add_job: Adds a new job to the scheduler.
        reschedule_job: Reschedules an existing job or creates a new one.

    Generated by Duo.
    """

    RESCHEDULE_SECONDS = 30

    # TODO: add lock here

    def add_job(self, id, func, **kwargs: Mapping[str, Any]):
        super().add_job(id, func, **kwargs)

    def reschedule_job(self, id, func, func_params, reschedule_seconds: int = RESCHEDULE_SECONDS):
        job: Job | None = self.get_job(id)
        run_time = datetime.now().astimezone(utc) + timedelta(seconds=reschedule_seconds)

        if job:
            job.next_run_time = run_time
            if job.trigger:
                if isinstance(job.trigger, DateTrigger):
                    job.trigger.run_date = run_time
                elif isinstance(job.trigger, IntervalTrigger):
                    job.trigger.start_date = run_time
            # TODO: this is not correct, we should use `job.modify` instead
            job.reschedule(trigger=job.trigger)
        else:
            trigger = DateTrigger(run_date=run_time, timezone=utc)
            self.add_job(id, func, trigger=trigger, replace_existing=True, kwargs=func_params)
