from dataclasses import asdict, dataclass
from pathlib import Path

import pandas as pd
import sqlalchemy as sa
import tzlocal

from ap.api.common.services.show_graph_services import (
    df_from_db_data_conversion,
    get_equation_data,
)
from ap.api.common.services.sql_generator import TransactionDataQueryBuilder
from ap.api.common.services.utils import gen_sql_and_params
from ap.api.setting_module.services.equations import (
    get_all_normal_columns_for_functions,
)
from ap.api.trace_data.services.filter_function_condition import filter_df
from ap.common.common_utils import Bound, TimeRange
from ap.common.constants import (
    DATE_FORMAT_STR_CSV,
    DATE_FORMAT_STR_SQLITE,
    EMPTY_STRING,
    EXPORT_DATETIME_FORMAT,
    UNDER_SCORE,
    ColumnNameType,
    CsvDelimiter,
    CSVExtTypes,
    DataType,
)
from ap.common.jobs.job_info_schema import DataExportJobInfo
from ap.common.pydn.dblib.transaction import TxnDataConnection, TxnMetaConnection
from ap.setting_module.models import CfgExport, CfgFilterDetail, CfgProcessColumn
from ap.trace_data.transaction_model import (
    ExportHistoryRecord,
    ExportHistoryTable,
    TransactionData,
)


@dataclass
class PdParams:
    """pandas params to export data"""

    sep: str = CsvDelimiter.CSV.value

    def to_dict(self):
        return asdict(self)


@dataclass
class ExportConfig:
    """export config"""

    config_id: CfgExport

    def to_dict(self):
        return asdict(self)


class DataExport:
    """Manages data export operations for configured export settings.

    This class handles the complete export workflow including querying data,
    applying filters, calculating function columns, and saving to files.

    Attributes:
        config: Export configuration object (CfgExport).
        data_export_job_info: DataExportJobInfo object for tracking export job info.
        transaction_data: TransactionData object for the process.
        normal_filters: List of normal column filter details.
        func_filters: List of function column filter details.
        filter_columns: List of columns used in filters.

    Methods:
        extract_filters: Extract and categorize filters from configuration.
        export_columns: Get list of columns to export.
        query_columns: Get list of physical columns needed for the query.
        sql_query: Build SQL query for data export.
        get_data: Execute query and get data from database.
        get_exported_timerange: Get time range of exported data.
        generate_export_file: Generate file path for export.
        generate_export_params: Generate pandas export parameters.
        save_data_to_file: Save data to CSV file with timezone conversion.
        export: Execute complete export workflow.
        export_as_gen: Export data as generator for job context.

    Generated by Duo.
    """

    def __init__(self, export_config: CfgExport, data_export_job_info: DataExportJobInfo) -> None:
        self.config = export_config
        self.data_export_job_info = data_export_job_info
        self.transaction_data = TransactionData(export_config.process)

        # filter setting
        self.normal_filters: list[CfgFilterDetail] = []
        self.func_filters: list[CfgFilterDetail] = []
        self.filter_columns: list[CfgProcessColumn] = []
        self.extract_filters()

    def extract_filters(self):
        """Extract filters from config: normal and function columns"""
        for export_filter in self.config.filters:
            self.filter_columns.append(export_filter.filter.cfg_filter.column)
            if export_filter.filter.cfg_filter.column.is_function_column:
                self.func_filters.append(export_filter.filter)
            else:
                self.normal_filters.append(export_filter.filter)

    def export_columns(self) -> list[CfgProcessColumn]:
        """
        Selected columns to export:
        - This include datetime and serial columns
        This includes logical columns (such as function columns) as well
        """
        column_ids: list[int] = [self.config.process.get_date_col(column_name_only=False).id]
        if (serial_column := self.config.process.get_main_serial_column()) is not None:
            column_ids.append(serial_column.id)

        # sort to retain consistent order
        selected_column_ids = [
            detail.process_column.id for detail in sorted(self.config.export_details, key=lambda d: d.order)
        ]
        # Remove duplicate IDs before extending.
        column_ids = [i for i in column_ids if i not in selected_column_ids]

        column_ids.extend(selected_column_ids)

        columns = self.config.process.get_cols(dict.fromkeys(column_ids))
        return columns

    def query_columns(self) -> list[CfgProcessColumn]:
        """
        Selected columns to query in t_process. They must be physical columns:
        - Datetime
        - Serial
        - Selected physical columns
        - Columns to construct function columns
        - Columns for filtering
        """
        query_columns = self.export_columns()

        # need to include filter columns for querying
        query_columns.extend(self.filter_columns)

        function_columns_ids = [c.id for c in query_columns if c.is_function_column]

        # non-selected columns but required to calculate function columns
        relation_column_ids = get_all_normal_columns_for_functions(function_columns_ids, self.config.process.columns)
        query_columns.extend(self.config.process.get_cols(relation_column_ids))

        # Remove duplicates
        required_column_ids = [c.id for c in query_columns]
        query_columns = self.config.process.get_cols(dict.fromkeys(required_column_ids))

        # only use physical columns
        return [c for c in query_columns if c.is_transaction_column]

    def sql_query(self) -> sa.Select | None:
        with TxnMetaConnection(process_id=self.config.process_id) as meta_con:
            exported_range = ExportHistoryTable.exported_range(meta_con, self.config.process_id, self.config.id)
        selected_range = TimeRange(
            min=Bound.included(self.config.export_from),
            max=Bound.included(self.config.export_to),
        )
        query_ranges = selected_range.different(exported_range)
        queries: list[sa.Select] = []
        for query_range in query_ranges:
            query_builder = TransactionDataQueryBuilder(self.transaction_data)
            for c in self.query_columns():
                query_builder.add_column(column=c.bridge_column_name, label=c.gen_sql_label())
            query_range_str = query_range.to_time_range_str(DATE_FORMAT_STR_SQLITE)
            query_builder.between_bound(time_range=query_range_str)
            # todo: filter for function column later
            if self.normal_filters:
                for c in self.normal_filters:
                    if c.cfg_filter.column not in self.query_columns():
                        query_builder.add_column(
                            column=c.cfg_filter.column.bridge_column_name, label=c.cfg_filter.column.gen_sql_label()
                        )
                query_builder.add_conditions(self.normal_filters)
            queries.append(query_builder.build())

        if len(queries) == 0:
            return None

        if len(queries) == 1:
            return queries[0]

        return sa.union_all(*queries)

    def get_data(self) -> pd.DataFrame | None:
        """Get data from transaction DB"""
        query = self.sql_query()
        if query is None:
            return None

        with TxnDataConnection(process_id=self.config.process_id, readonly_transaction=True) as data_con:
            sql, params = gen_sql_and_params(query)
            df = data_con.run_sql(sql, params=params).fetch_df()

        export_columns = self.export_columns()
        required_column_ids = [c.id for c in export_columns]

        # need to include columns from filter function columns, to correctly get equation data
        function_col_ids = list({f.cfg_filter.column.id for f in self.func_filters})
        df = get_equation_data(df, self.config.process, required_column_ids + function_col_ids)

        # filter for function columns
        if self.func_filters:
            df = filter_df(df, filters=self.func_filters)

        # now that we calculated function column, we can drop unneeded columns
        selected_columns = [c.gen_sql_label() for c in export_columns]
        df = df[selected_columns]
        df = df_from_db_data_conversion(df, export_columns)

        # todo: filter for function columns
        return df

    def get_exported_timerange(self, df: pd.DataFrame) -> TimeRange:
        """Get exported time range, to record in export history and construct filename"""
        datetime_column = self.config.process.get_date_col(column_name_only=False).gen_sql_label()
        datetime_series = pd.to_datetime(df[datetime_column])
        return TimeRange(
            min=Bound.included(datetime_series.min()),
            max=Bound.included(datetime_series.max()),
        )

    def generate_export_file(self, export_range: TimeRange) -> Path:
        """Generate full path for exporting file"""
        target_dir = Path(self.config.folder_path)
        file_ext = CSVExtTypes[(self.config.file_type or CSVExtTypes.CSV)].value
        time_range = export_range.to_time_range_str(EXPORT_DATETIME_FORMAT).format()
        process_name = self.config.process.name.replace(UNDER_SCORE, EMPTY_STRING)
        title = self.config.title.replace(UNDER_SCORE, EMPTY_STRING)
        export_file_name = f'{UNDER_SCORE.join([str(self.config.id), process_name, title, time_range])}.{file_ext}'
        return target_dir / export_file_name

    def generate_export_params(self) -> dict:
        """Generate parameters that will be passed to pandas functions for data export."""
        return PdParams(sep=(CsvDelimiter[self.config.file_type].value or CsvDelimiter.CSV.value)).to_dict()

    def save_data_to_file(self, df: pd.DataFrame, export_range: TimeRange) -> Path:
        """Save export data to file, this does:
        - Convert datetime column to local time.
        - Convert column name to system name (name_en).
        """
        export_columns = self.export_columns()

        # change timezone to local
        local_timezone = tzlocal.get_localzone()
        for column in export_columns:
            if column.data_type == DataType.DATETIME.name:
                column_name = column.gen_sql_label()
                df[column_name] = (
                    pd.to_datetime(df[column_name]).dt.tz_convert(local_timezone).dt.strftime(DATE_FORMAT_STR_CSV)
                )

        # rename column
        column_name_type = ColumnNameType(self.config.export_column_name_type)
        match column_name_type:
            case ColumnNameType.SYSTEM_NAME:
                df = df.rename(columns={c.gen_sql_label(): c.name_en for c in export_columns})
            case ColumnNameType.JAPANESE_NAME:
                df = df.rename(columns={c.gen_sql_label(): c.name_jp or c.name_en for c in export_columns})
            case ColumnNameType.LOCAL_NAME:
                df = df.rename(columns={c.gen_sql_label(): c.name_local or c.name_en for c in export_columns})
            case _:
                raise NotImplementedError(column_name_type)

        # save to output
        export_file = self.generate_export_file(export_range.with_timezone(local_timezone))
        df.to_csv(export_file, index=False, **self.generate_export_params())
        return export_file

    def export(self) -> Path | None:
        """Export data to the specified path

        Returns:
            Path | None: Path to the exported file, or None if no data to export
        """
        data = self.get_data()
        if data is None or data.empty:
            self.data_export_job_info.warning('No data to export')
            return None

        export_range = self.get_exported_timerange(data)
        export_file = self.save_data_to_file(data, export_range)
        exported_records = len(data)

        time_range_str = export_range.to_time_range_str(DATE_FORMAT_STR_SQLITE)
        export_from = time_range_str.min.value
        export_to = time_range_str.max.value

        # Update job management info
        self.data_export_job_info.exported_records = exported_records
        self.data_export_job_info.export_location = export_file.as_posix()
        self.data_export_job_info.export_from = export_from
        self.data_export_job_info.export_to = export_to

        export_history_record = ExportHistoryRecord(
            export_id=self.config.id,
            export_from=export_from,
            export_to=export_to,
            exported_rows=exported_records,
            export_file_path=export_file.as_posix(),
        )
        with TxnMetaConnection(process_id=self.config.process_id) as meta_con:
            ExportHistoryTable.insert(meta_con, self.config.process_id, export_history_record)

        return export_file

    def export_as_gen(self):
        """Export data as a generator, used in the job context"""
        yield 0
        self.export()
        yield 100
