from __future__ import annotations

import dataclasses
import itertools
from abc import abstractmethod
from collections.abc import Generator
from datetime import datetime

import numpy as np
import pandas as pd
from apscheduler.job import Job
from pandas import DataFrame
from pytz import utc
from sqlalchemy.orm import scoped_session

from ap import scheduler
from ap.api.setting_module.services.equations import get_all_normal_columns_for_functions
from ap.api.setting_module.services.polling_frequency import add_import_job, add_import_job_params
from ap.common.common_utils import generate_job_id
from ap.common.constants import CacheType, JobType
from ap.common.jobs.job_info_schema import UpdateTransactionTableJobInfo
from ap.common.log import log_execution_time
from ap.common.multiprocess_sharing import EventExpireCache, EventQueue
from ap.common.pydn.dblib.duckdb import DuckDB
from ap.common.pydn.dblib.transaction import TxnDataConnection, TxnMetaConnection
from ap.common.scheduler import scheduler_app_context
from ap.equations.utils import get_function_class_by_id
from ap.setting_module.models import (
    CfgProcess,
    CfgProcessColumn,
    CfgProcessFunctionColumn,
    JobManagement,
    use_meta_session,
)
from ap.setting_module.services.background_process import JobInfo, send_processing_info
from ap.trace_data.transaction_model import TransactionData


@dataclasses.dataclass()
class MainFunctionColumnHandler:
    """Abstract handler for main function columns (datetime or serial).

    This class provides base functionality for handling main function columns,
    including calculating function column values from component columns.

    Attributes:
        cfg_process: Process configuration object.

    Methods:
        get_main_function_column: Abstract method to get the main function column.
        calculate_data_for_main_function_column: Calculate function column data from DataFrame.

    Generated by Duo.
    """

    cfg_process: CfgProcess

    @abstractmethod
    def get_main_function_column(self) -> CfgProcessColumn | None: ...

    def calculate_data_for_main_function_column(
        self,
        df: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Calculate data for function column as ``main::Serial``, ``main::Datetime``

        :param pd.DataFrame df: A DataFrame want to be calculated.
        In this df, base columns are required to serve calculating data
        :return: DataFrame that include column have calculated data
        :rtype: pd.DataFrame
        """

        def _get_column_by_id(column_id: int) -> CfgProcessColumn | None:
            return next(filter(lambda x: x.id == column_id, self.cfg_process.columns), None)

        def _add_missing_column(_df: pd.DataFrame, column_name: str | None) -> pd.DataFrame:
            if column_name and column_name not in _df.columns:
                _df[column_name] = np.nan
            return _df

        df_columns = df.columns.tolist()

        # Get component columns that necessary for calculating value
        main_function_column = self.get_main_function_column()
        relation_column_ids = get_all_normal_columns_for_functions([main_function_column.id], self.cfg_process.columns)
        relation_column_ids.append(main_function_column.id)
        relation_cfg_process_column_dict = {_id: _get_column_by_id(_id) for _id in relation_column_ids}
        relation_cfg_process_columns: list[CfgProcessColumn] = list(
            filter(lambda x: x.function_details, relation_cfg_process_column_dict.values())
        )
        cfg_function_cols = itertools.chain.from_iterable(
            cfg_col.function_details for cfg_col in relation_cfg_process_columns
        )
        sorted_cfg_function_cols = sorted(cfg_function_cols, key=lambda col: col.order)

        # Calculate function data
        for cfg_func_col in sorted_cfg_function_cols:  # type: CfgProcessFunctionColumn
            equation_class = get_function_class_by_id(cfg_func_col.function_id)
            equation = equation_class.from_kwargs(**cfg_func_col.as_dict())

            # Get column_x and column_y
            cfg_col_x: CfgProcessColumn = _get_column_by_id(cfg_func_col.var_x)
            cfg_col_y: CfgProcessColumn | None = _get_column_by_id(cfg_func_col.var_y) if cfg_func_col.var_y else None

            column_x, x_dtype = (cfg_col_x.column_raw_name, cfg_col_x.raw_data_type) if cfg_col_x else (None, None)  # type: str
            column_y, y_dtype = (cfg_col_y.column_raw_name, cfg_col_y.raw_data_type) if cfg_col_y else (None, None)  # type: Optional[str]

            df = _add_missing_column(df, column_x)
            df = _add_missing_column(df, column_y)

            cfg_col: CfgProcessColumn = relation_cfg_process_column_dict.get(cfg_func_col.process_column_id)
            df = equation.evaluate(
                df,
                out_col=cfg_col.column_raw_name,
                x_col=column_x,
                y_col=column_y,
                x_dtype=x_dtype,
                y_dtype=y_dtype,
            )

        target_function_column = main_function_column.column_raw_name
        if target_function_column not in df_columns:
            df_columns.append(target_function_column)

        return df[df_columns]


class MainDatetimeFunctionColumnHandler(MainFunctionColumnHandler):
    """Handler for main datetime function columns.

    This class handles datetime function columns that serve as the main datetime
    for a process configuration.

    Methods:
        get_main_function_column: Get the main datetime function column from process config.

    Generated by Duo.
    """

    def get_main_function_column(self) -> CfgProcessColumn:
        return self.cfg_process.get_main_datetime_function_col()


@dataclasses.dataclass
class MainSerialFunctionColumnHandler(MainFunctionColumnHandler):
    """Handler for main serial function columns.

    This class handles serial function columns that serve as the main serial number
    for a process configuration. It provides functionality to change main serial columns
    and update transaction tables accordingly.

    Methods:
        get_main_function_column: Get the main serial function column from process config.
        change_main_function_column: Handle changing main::serial for function column.
        add_main_function_column_to_transaction_table: Insert calculated data into transaction table.
        is_show_warning_message: Check if warning message should be shown for column changes.
        identical_main_cfg_func_column: Check if function column actually changed.

    Generated by Duo.
    """

    def get_main_function_column(self) -> CfgProcessColumn:
        return self.cfg_process.get_main_serial_function_col()

    @log_execution_time()
    def change_main_function_column(
        self,
        data_con: DuckDB,
        transaction_obj: TransactionData,
        old_main_column: CfgProcessColumn | None,
    ) -> Generator[float]:
        """
        Handle changing **main::serial** for function column

        :param data_con: A DuckDB database instance
        :param TransactionData transaction_obj: A transaction object
        :param Optional[CfgProcessColumn] old_main_column: \
        A process column model object that is as **main::serial** before change
        :return: done percent
        :rtype: Generator[float]
        """
        old_main_function_column: CfgProcessFunctionColumn | None = None
        if old_main_column and old_main_column.function_details:
            old_main_function_column = old_main_column.function_details[0]

        new_main_column: CfgProcessColumn = next(
            (col for col in transaction_obj.cfg_process.columns if col.is_serial_no),
            None,
        )

        # We ignore function 'me' in this case, therefore there is only one function record for a normal function
        new_main_function_column: CfgProcessFunctionColumn | None = None
        if new_main_column and new_main_column.function_details:
            new_main_function_column = new_main_column.function_details[0]

        if self.identical_main_cfg_func_column(old_main_function_column, new_main_function_column):
            # Do nothing
            yield 100
            return

        # In case change to main::serial normal column or not have main::serial column
        if new_main_function_column is None:
            # we have already sync columns in `update_transaction_table`, so we have the latest columns already.
            # don't need to delete / handle old function columns
            yield 100
            return

        yield from self.add_main_function_column_to_transaction_table(data_con, transaction_obj)

    @log_execution_time()
    def add_main_function_column_to_transaction_table(
        self,
        data_con: DuckDB,
        transaction_obj: TransactionData,
    ) -> Generator[float]:
        """
        Insert calculated data for ``main::serial`` for function column into transaction table.

        :param data_con: A DuckDB database instance
        :param transaction_obj: A transaction object
        :return: done percent
        :rtype: Generator[float]
        """
        # Create new table with function column
        new_table_name = f'{transaction_obj.table_name}_calculating'
        old_table_name = f'{transaction_obj.table_name}_old'
        data_con.copy_table_schema(from_table=transaction_obj.table_name, to_table=new_table_name)

        done_percent = 10
        yield done_percent

        transaction_columns = transaction_obj.cfg_process.get_transaction_process_columns()
        columns_bridge_to_raw = {col.bridge_column_name: col.column_raw_name for col in transaction_columns}
        columns_raw_to_bridge = {col.column_raw_name: col.bridge_column_name for col in transaction_columns}

        for df_transaction in transaction_obj.get_all_data_by_chunk(data_con):
            df_column_raw_name = df_transaction.rename(columns=columns_bridge_to_raw)
            df_column_raw_name = self.calculate_data_for_main_function_column(df_column_raw_name)
            data_con.insert_from_df(
                df_column_raw_name.rename(columns=columns_raw_to_bridge),
                new_table_name,
            )

            done_percent += 10 if done_percent < 70 else 1 if done_percent < 80 else 0.1 if done_percent < 90 else 0.01
            yield done_percent

        # End - [Calculate function data and insert to new table]
        data_con.rename_table(transaction_obj.table_name, old_table_name)
        data_con.rename_table(new_table_name, transaction_obj.table_name)
        data_con.delete_table(old_table_name)

        done_percent = 100
        yield done_percent

    def is_show_warning_message(
        self,
        old_main_column: CfgProcessColumn | None = None,
    ) -> bool:
        """
        There is only one case that we need to show a warning message:
        - main::Serial column is changed or updated.

        :param Optional[CfgProcessColumn] old_main_column:
        :return: True if need to show a warning message, otherwise False
        """
        new_main_serial_cfg_process_column = self.cfg_process.get_main_serial_column(is_isolation_object=True)
        new_main_serial_cfg_process_function_column: CfgProcessFunctionColumn | None = (
            (new_main_serial_cfg_process_column.function_details or [None])[0]
            if new_main_serial_cfg_process_column
            else None
        )
        if new_main_serial_cfg_process_function_column is None:
            return False

        old_main_serial_cfg_process_function_column: CfgProcessFunctionColumn | None = (
            (old_main_column.function_details or [None])[0] if old_main_column else None
        )
        return not self.identical_main_cfg_func_column(
            old_main_cfg_process_function_column=old_main_serial_cfg_process_function_column,
            new_main_cfg_process_function_column=new_main_serial_cfg_process_function_column,
        )

    @staticmethod
    def identical_main_cfg_func_column(
        old_main_cfg_process_function_column: CfgProcessFunctionColumn | None,
        new_main_cfg_process_function_column: CfgProcessFunctionColumn | None,
    ) -> bool:
        """
        Check if the function column actually changed (not counting notes).
        Return True if NOT changed
        """
        if old_main_cfg_process_function_column is None and new_main_cfg_process_function_column is None:
            return True

        return (
            old_main_cfg_process_function_column
            and new_main_cfg_process_function_column
            and old_main_cfg_process_function_column.id == new_main_cfg_process_function_column.id
            and old_main_cfg_process_function_column.function_id == new_main_cfg_process_function_column.function_id
            and old_main_cfg_process_function_column.var_x == new_main_cfg_process_function_column.var_x
            and old_main_cfg_process_function_column.var_y == new_main_cfg_process_function_column.var_y
            and old_main_cfg_process_function_column.a == new_main_cfg_process_function_column.a
            and old_main_cfg_process_function_column.b == new_main_cfg_process_function_column.b
            and old_main_cfg_process_function_column.c == new_main_cfg_process_function_column.c
            and old_main_cfg_process_function_column.n == new_main_cfg_process_function_column.n
            and old_main_cfg_process_function_column.k == new_main_cfg_process_function_column.k
            and old_main_cfg_process_function_column.s == new_main_cfg_process_function_column.s
            and old_main_cfg_process_function_column.t == new_main_cfg_process_function_column.t
            and old_main_cfg_process_function_column.order == new_main_cfg_process_function_column.order
            and old_main_cfg_process_function_column.return_type == new_main_cfg_process_function_column.return_type
        )


@use_meta_session()
def add_new_columns_to_transaction_table(process: CfgProcess, meta_session: scoped_session = None):
    """
    Add new function column as ``main::Serial`` into transaction table directly.

    **NOTE**: this function must be called directly after process config is updated to make sure that show graph
    feature work normally without any exception related to missing columns in transaction table.
    :param int process: a cfg_process object
    :param scoped_session meta_session: a db session
    :return: void
    """
    trans_data = TransactionData(process, meta_session=meta_session)
    with TxnDataConnection(process_id=process.id, readonly_transaction=False) as data_con:
        if trans_data.table_name not in data_con.list_tables():
            # If transaction is not created yet, do nothing
            return
        trans_data.sync_columns_to_transaction(data_con)


def add_required_jobs_after_update_transaction_table(
    process: CfgProcess = None,
    is_new_process: bool = False,
):
    """
    Add required jobs for ``main::Serial`` to update ``main::Serial``
    :param CfgProcess process: a cfg_process object
    :param bool is_new_process: True if process is created newly, False otherwise
    :return: void
    """
    if not is_new_process:
        # reset cache of transaction data after update
        EventQueue.put(EventExpireCache(cache_type=CacheType.TRANSACTION_DATA))

    # add import data job
    import_params = add_import_job_params(process)
    add_import_job(
        process_id=import_params.process_id,
        process_name=import_params.process_name,
        data_source_id=import_params.data_source_id,
        data_source_type=import_params.data_source_type,
        interval_sec=import_params.polling_frequency,
        run_now=True,
        is_user_request=True,
    )


def update_transaction_table(
    process: CfgProcess,
    old_main_serial_cfg_process_column: CfgProcessColumn | None,
    meta_session: scoped_session = None,
    update_txn_tbl_job_info: UpdateTransactionTableJobInfo | None = None,
) -> Generator[JobInfo]:
    """
    Update transaction table by doing some points as below:

    #. Delete redundant table columns that not exist in ``cfg_process_column`` table
    #. Remove old ``main::Serial`` column and add new one into transaction table
    #. Insert calculated data of ``main::Serial`` column into transaction table

    :param CfgProcess process: a cfg_process object
    :param Optional[CfgProcessColumn] old_main_serial_cfg_process_column: old cfg process column as ``main::Serial``
    :param scoped_session meta_session: a db session
    :param update_txn_tbl_job_info: a UpdateTransactionTableJobInfo object
    :return: a JobInfo
    :rtype: Generator[JobInfo]
    """
    job_info = JobInfo()
    job_info.percent = 0
    yield job_info

    trans_data = TransactionData(process, meta_session=meta_session)
    with (
        TxnDataConnection(process_id=process.id, readonly_transaction=False) as data_con,
        TxnMetaConnection(process_id=process.id) as meta_con,
        job_info.interruptible() as job_info,
    ):
        auto_commit = False
        trans_data.create_table(data_con, meta_con, auto_commit=auto_commit)
        job_info.percent = 10
        yield job_info

        if update_txn_tbl_job_info:
            main_serial_after = (
                process.get_main_serial_column().column_name if process.get_main_serial_column() else None
            )
            update_txn_tbl_job_info.main_serial_after = main_serial_after
            main_serial_before = (
                old_main_serial_cfg_process_column.column_name if old_main_serial_cfg_process_column else None
            )
            update_txn_tbl_job_info.main_serial_before = main_serial_before

        job_info.percent = 20
        yield job_info

        main_function_column_handlers = get_main_function_column_handlers(process)
        for handler in main_function_column_handlers:
            if isinstance(handler, MainSerialFunctionColumnHandler) and old_main_serial_cfg_process_column is not None:
                for done_percent in handler.change_main_function_column(
                    data_con,
                    trans_data,
                    old_main_serial_cfg_process_column,
                ):
                    job_info.percent = round(20 + 0.8 * done_percent, 2)
                    yield job_info


@scheduler_app_context
def update_transaction_table_job(
    job_management: JobManagement,
    old_main_serial_cfg_process_column: CfgProcessColumn | None = None,
    is_show_warning_message: bool = False,  # DO NOT REMOVE THIS PARAM
):
    """
    [Job] Update transaction table by doing some points as below:

    #. Delete redundant table columns that not exist in ``cfg_process_column`` table
    #. Remove old ``main::Serial`` column and add new one into transaction table
    #. Insert calculated data of ``main::Serial`` column into transaction table

    :param is_show_warning_message: **[PLEASE KEEP IT]**
    ITEM IS USED FOR ``is_show_warning_message_update_main_serial`` api.
    A flag to determine whether to show a warning message or not.
    :param int job_management: job of process
    :param Optional[CfgProcessColumn] old_main_serial_cfg_process_column: old cfg process column as ``main::Serial``
    :return: void
    """
    update_txn_tbl_job_info = UpdateTransactionTableJobInfo()
    job_management.info = update_txn_tbl_job_info
    process = CfgProcess.get_proc_by_id(job_management.process_id).clone()
    gen = update_transaction_table(
        process=process,
        old_main_serial_cfg_process_column=old_main_serial_cfg_process_column,
        update_txn_tbl_job_info=update_txn_tbl_job_info,
    )
    send_processing_info(
        gen,
        job_management=job_management,
        is_check_disk=False,
    )
    add_required_jobs_after_update_transaction_table(process=process)


def reschedule_update_transaction_table():
    """
    Reschedule all ``UPDATE_TRANSACTION_TABLE`` jobs in APScheduler to recalculate data | recovery killed jobs.

    **NOTE**: Only do this function in start app time
    :return: void
    """
    process_ids: list[int] = CfgProcess.get_all_ids()
    jobs: list[Job] = scheduler.get_jobs()
    now = datetime.now(utc)
    for process_id in process_ids:
        job_id = generate_job_id(JobType.UPDATE_TRANSACTION_TABLE, process_id)
        for job in jobs:
            if job.id == job_id:
                job.modify(next_run_time=now)


def get_main_function_column_handlers(process: CfgProcess) -> list[MainFunctionColumnHandler]:
    handlers = []
    for column in process.columns:
        if column.is_main_datetime_function_column:
            handlers.append(MainDatetimeFunctionColumnHandler(cfg_process=process))
        if column.is_main_serial_function_column:
            handlers.append(MainSerialFunctionColumnHandler(cfg_process=process))
    return handlers


def handle_main_function_columns(process: CfgProcess, df: DataFrame) -> DataFrame:
    main_function_column_handlers = get_main_function_column_handlers(process=process)
    for handler in main_function_column_handlers:
        df = handler.calculate_data_for_main_function_column(df=df)
    return df
