from typing import Self, override

import pandas as pd
from pandas import Series
from pydantic import dataclasses

from ap.common.constants import FormulaType
from ap.common.datetime_format_utils import format_datetime
from ap.conversion_formula.core import ConversionFormula


@dataclasses.dataclass(frozen=True, kw_only=True)
class DatetimeFormula(ConversionFormula):
    """Conversion formula for datetime strings.

    Converts a pandas Series into timezone-aware or naive datetime strings
    according to a specified format and optional client timezone.

    Attributes:
        formula: The datetime format string to use when formatting values.

    Generated by Junie
    """

    formula: str

    @classmethod
    def from_formula(cls, formula: str | None) -> Self:
        return cls(formula_type=FormulaType.DATETIME, formula=formula)

    def validate(self) -> bool:
        # TODO: Implement later
        return True

    def convert(self, series: Series, client_timezone: str | None = None) -> Series:
        return format_datetime(series, self.formula, client_timezone)

    @override
    @classmethod
    def detect(cls, series: pd.Series) -> Self | None:
        # TODO: detect date https://gitlab.com/dot-asterisk/biz-app/analysis-interface/analysisinterface/-/issues/221
        return None

    @classmethod
    def revert(cls, series: pd.Series) -> pd.Series:
        return series

    def get_formula(self) -> str:
        return self.formula
