import dataclasses
import re
from typing import Self, override

import pandas as pd

from ap.common.constants import FormulaType
from ap.conversion_formula.core import ConversionFormula

JUDGE_NAME_REGEX = re.compile(r'^.*(judge|判定).*$', re.IGNORECASE)
JUDGE_NA_VALUES = {'Null'}

JUDGE_PATTERN_REGEX = re.compile(r'^Pos~(?P<positive>[^|]+)\|Neg=(?P<pos_display>[^|]+)\|(?P<neg_display>[^|]+)$')


@dataclasses.dataclass(frozen=True, kw_only=True)
class JudgeFormula(ConversionFormula):
    """Conversion formula for judge/judgment columns.

    Converts categorical data to binary judgment values (1 for positive, 0 for negative).
    Supports auto-detection of judge columns based on naming patterns.

    Attributes:
        formula_type: Always set to FormulaType.JUDGE.
        positive: Value representing a positive judgment.
        positive_display: Display text for positive values.
        negative_display: Display text for negative values.

    Methods:
        from_formula: Parses a formula string to create a JudgeFormula.
        get_formula: Returns the formula as a string.
        validate: Validates the formula (currently always returns True).
        convert: Converts raw values to binary judgment (1, 0, NA).
        revert: Converts binary values back to display text.
        detect: Auto-detects judge formulas from series data and column name.

    Generated by Duo.
    """

    formula_type: FormulaType = FormulaType.JUDGE
    positive: str
    positive_display: str
    negative_display: str

    @classmethod
    def from_formula(cls, formula: str) -> Self:
        match = JUDGE_PATTERN_REGEX.match(formula)
        if match:
            positive = match.group('positive')
            pos_display = match.group('pos_display')
            neg_display = match.group('neg_display')
            return cls(positive=positive, positive_display=pos_display, negative_display=neg_display)
        else:
            return None

    def get_formula(self) -> str:
        return f'Pos~{self.positive}|Neg={self.positive_display}|{self.negative_display}'

    def validate(self) -> bool:
        # TODO: implement later
        return True

    def convert(self, series: pd.Series) -> pd.Series:
        """Convert raw values to judge values (1, 0, NA) by defined rule.

        1. In a normal case that defined positive value is NOT pd.NA, then convert
           - 1 for positive values.
           - 0 for other values (except pd.NA).
           - pd.NA for None values.

        2. In 2025-10-13, we add a new judge rule that allows using pd.NA as a positive value, it means
           - 1 for pd.NA values.
           - 0 for other values (except pd.NA).
        """
        if self.positive in JUDGE_NA_VALUES:
            is_positive = series.isna()
            is_negative = ~is_positive
        else:
            is_positive = series == self.positive
            is_negative = ~series.isna() & ~is_positive

        result_series = pd.Series(pd.NA, index=series.index, dtype=pd.Int8Dtype())
        result_series[is_positive] = 1
        result_series[is_negative] = 0

        return result_series

    def revert(self, series: pd.Series) -> pd.Series:
        series = series.astype('object')
        return series.replace({1: self.positive_display, 0: self.negative_display})

    @override
    @classmethod
    def detect(cls, series: pd.Series) -> Self | None:
        series = series.dropna()
        try:
            if series.nunique() <= 2:
                for i, judge_formula in enumerate(JUDGE_FORMULAS):
                    if judge_formula.positive in [str(val) for val in series.unique()]:
                        return judge_formula

                # try to cast to int to detect judge
                int_series = series.astype(pd.Int8Dtype(), errors='ignore')
                if pd.api.types.is_numeric_dtype(int_series) and 0 <= int_series.max() <= 2:
                    return JudgeFormula(positive=str(int_series.max()), positive_display='OK', negative_display='NG')
                return None
            else:
                return None
        except Exception:
            # when series cannot be safely cast to Int
            return None


JUDGE_FORMULAS: list[JudgeFormula] = [
    JudgeFormula(positive='OK', positive_display='OK', negative_display='NG'),
    JudgeFormula(positive='Positive', positive_display='Positive', negative_display='Negative'),
    JudgeFormula(positive='Pos', positive_display='Pos', negative_display='Neg'),
    JudgeFormula(positive='P', positive_display='P', negative_display='N'),
    JudgeFormula(positive='Good', positive_display='Good', negative_display='Bad'),
    JudgeFormula(positive='Yes', positive_display='Yes', negative_display='No'),
    JudgeFormula(positive='Pass', positive_display='Pass', negative_display='Failed'),
    JudgeFormula(positive='P', positive_display='P', negative_display='F'),
    JudgeFormula(positive='True', positive_display='True', negative_display='False'),
    JudgeFormula(positive='T', positive_display='T', negative_display='F'),
    JudgeFormula(positive='可', positive_display='可', negative_display='否'),
    JudgeFormula(positive='良', positive_display='良', negative_display='不良'),
    JudgeFormula(positive='はい', positive_display='はい', negative_display='いいえ'),
    JudgeFormula(positive='正', positive_display='正', negative_display='誤'),
    JudgeFormula(positive='有', positive_display='有', negative_display='無'),
    JudgeFormula(positive='あり', positive_display='あり', negative_display='なし'),
    JudgeFormula(positive='On', positive_display='On', negative_display='Off'),
]
