from typing import Any

from ap.common.common_utils import RangeBound, TimeRange
from ap.etl.factory_import.common import ImportBase


class ImportOthers(ImportBase):
    """Import handler for miscellaneous database sources.

    Builds parameterized SQL queries to fetch data from non-standard database sources
    within a specified time range, with support for timezone-aware date formatting.

    Generated by Duo
    """

    def build_query(
        self,
        db_instance,
        time_range: TimeRange,
        sql_limit: int,
    ) -> tuple[str, Any]:
        from ap.api.setting_module.services.factory_import import get_data_by_range_time_sql

        get_date_col = self.process.get_auto_increment_col_else_get_date()
        column_names = self.get_query_column_names()
        time_range_str: RangeBound[str] = time_range.map(lambda x: self.convert_datetime(x))

        return get_data_by_range_time_sql(
            db_instance,
            get_date_col,
            column_names,
            self.process.table_name,
            time_range_str,
            sql_limit,
        )
