from typing import Any

from ap.api.setting_module.services.software_workshop_etl_services import POSTGRES_SOFTWARE_WORKSHOP_DEF
from ap.common.common_utils import TimeRange
from ap.common.constants import MasterDBType
from ap.etl.factory_import.common import ImportBase


class ImportSoftwareWorkshop(ImportBase):
    """Import handler for Software Workshop database sources.

    Builds parameterized SQL queries to fetch transaction data from Software Workshop
    systems for a specific process within a given time range, supporting different
    master database types.

    Generated by Duo
    """

    def build_query(
        self,
        db_instance,
        time_range: TimeRange,
        sql_limit: int,
    ) -> tuple[str, Any]:
        sql = POSTGRES_SOFTWARE_WORKSHOP_DEF.get_transaction_data_query(
            self.process.process_factid,
            datetime_key=self.process.get_auto_increment_col_else_get_date(),
            time_range=time_range,
            master_type=MasterDBType[self.process.master_type],
            limit=sql_limit,
        )
        sql, params = db_instance.gen_sql_and_params(sql)
        return sql, params
